### ISSUE TITLE
Why on earth is libsqlite3-sys compiling its own sqlite3.c instead of using the given libsqlite3.a?

### ISSUE THREAD

**Issue by NobodyXu** [rusqlite/rusqlite#1003]
Hi

I am trying to get rusqlite to use the libsqlite3.a I compiled.

I provided a custom `sqlite3.pc` in `/home/nobodyxu/Dev/fast-sqlite3-inserts/sqlite3/pkgconfig`:

```
# Package Information for pkg-config                     
                                                         
prefix="/home/nobodyxu/Dev/fast-sqlite3-inserts/sqlite3" 
exec_prefix=${prefix}                                    
libdir=${exec_prefix}                                    
includedir=${prefix}                                     
                                                         
Name: SQLite                                             
Description: SQL database engine                         
Version: 3.36.0                                          
Libs: -L${libdir} -lsqlite3 -lm -ldl -lz -lpthread       
Cflags: -I${includedir}
```

where `libsqlite3.a` is in the `prefix` above.

I also set the environment variables:

```
export SQLITE3_LIB_DIR=/home/nobodyxu/Dev/fast-sqlite3-inserts/sqlite3
export PKG_CONFIG_PATH="$SQLITE3_LIB_DIR/pkgconfig" 
export SQLITE3_STATIC=1
```

to make sure rusqlite uses it and linked statically with it.

However, it seems that libsqlite3-sys just like to compile its own `sqlite3/sqlite3.c` as if the `bundled` feature is set, so I tried to disable all default feature for rusqlite:

```
rusqlite = { version = "0.25.3", default-features = false, features = ["buildtime_bindgen"] )
```

Turns out that this doesn't work at all and it seems that rusqlite has no default feature and libsqlite3-sys does not enable `bundled` feature by default.

I have no idea now on how to fix the building process.

Can anybody please help me with this?

Thanks in advance.

**Comment by thomcc** [comment]
Hmm, do you need to have buildtime_bindgen on? This sounds like a bug either way.

**Comment by NobodyXu** [comment]
> Hmm, do you need to have buildtime_bindgen on? This sounds like a bug either way.

TBH, I am not sure about that and I was just changing configurations here and there to try to get it to work.

buildtime_bindgen sounds like related, so I tried that xD

**Comment by NobodyXu** [comment]
I got it!

It is sqlx, who is the culpuit for pulling in bundled libsqlite3-sys.

**Comment by NobodyXu** [comment]
sqlx is used for testing its async performance against rusqlite (which is actually way slower), maybe I can make that an optional dependency with a feature.

**Comment by thomcc** [comment]
Glad you managed to track it down. I'm going to close this, then.
