### ISSUE TITLE
bitvec 0.19 breaks code coverage 

### ISSUE THREAD

**Issue by gwenn** [rusqlite/rusqlite#1004]
https://github.com/rusqlite/rusqlite/pull/986/checks?check_run_id=3173780943
See https://github.com/bitvecto-rs/bitvec/issues/130

**Comment by thomcc** [comment]
What do we have that is pulling in an old version of bitvec? It might be easier to get them to update.

**Comment by gwenn** [comment]
bindgen !
```sh
cargo tree --features "bundled-full session buildtime_bindgen" | grep -B5 bitvec
│   [build-dependencies]
│   ├── bindgen v0.59.1
│   │   ├── bitflags v1.2.1
│   │   ├── cexpr v0.5.0
│   │   │   └── nom v6.1.2
│   │   │       ├── bitvec v0.19.5
```

**Comment by thomcc** [comment]
Hmm, could disable the session tests until this gets resolved somehow...

Issue might be that it's unclear when it would actually get resolved.

**Comment by thomcc** [comment]
This is fixed now
