### ISSUE TITLE
Please add wal2 sqlite branch to lib libsqlite3-sys

### ISSUE THREAD

**Issue by rfx77** [rusqlite/rusqlite#1014]
Could you please add the wal2 branch of sqlite as an optional feature to libsqlite3-sys: https://github.com/sqlite/sqlite/tree/wal2

**Comment by thomcc** [comment]
You're certainly free to use rusqlite to link against a version of sqlite that is built from this branch.

If you mean we should support it from bundled, I think probably not — we already include 2 copies of the SQLite source code for bundled builds, which is pretty sizable. There are a lot of unstable SQLite branches, and it's hard to support them all. Not to mention — I think we'd have to wrangle producing an amalgam from the branch.
