### ISSUE TITLE
`disk I/O error` Under Android 11

### ISSUE THREAD

**Issue by Cupnfish** [rusqlite/rusqlite#1015]
Under Android 11, when the query volume is high, it triggers an error such as `disk I/O error`.
This is the [part](https://gitlab.com/localnative/localnative/-/blob/master/localnative-rs/localnative_core/src/cmd/search.rs#L202) where we cause the error :
```rust
    let sql = format!(
        "SELECT rowid, uuid4, title, url, tags, description, comments
        , hex(annotations)
        , created_at, is_public
        FROM note where
        {}
        order by created_at desc limit :limit offset :offset",
        r.join(" and ")
    );
```
When I change it to this, it works fine:.
```rust
    // delete the `desc`
    let sql = format!(
        "SELECT rowid, uuid4, title, url, tags, description, comments
        , hex(annotations)
        , created_at, is_public
        FROM note where
        {}
        order by created_at limit :limit offset :offset",
        r.join(" and ")
    );
```
However, it can only work when the offset is 0. After the offset becomes larger, it can't continue to work and will report an error: `disk I/O error`.

**Comment by mqudsi** [comment]
SQLite uses external (on-disk) sort. The same is required for the pagination in your second query once the size grows beyond some limit, as SQLite defaults to ~always using external temp tables. You have an actual I/O error preventing SQLite from creating the temp file on disk for its internal workings.

This isn't a rusqlite bug; you'll get the same behavior if you used `sqlite` at the command line. Check to make sure you have sufficient free disk space, look at your `dmesg` logs to see if any I/O errors are being logged, and make sure the filesystem isn't mounted RO.

**Comment by Cupnfish** [comment]
Thank you very much, I solved the problem according to your idea. 🙏
Others who encounter a similar problem might consider specifying this when creating a connection:
```
    #[cfg(target_os = "android")]
    conn.execute(
        "PRAGMA temp_store_directory = '/data/user/0/your_project_name/cache'",
        [],
    )
    .unwrap();
```
