### ISSUE TITLE
Release on crates.io

### ISSUE THREAD

**Issue by douloiha** [rusqlite/rusqlite#1019]
Hello,

I would like to use the latest features of this crate in my project (especially bundled-sqlcipher-vendored-openssl)

Is a Release on Crates.io from the current version on Github planned? And if so, when?

Thank you everyone for your work!

**Comment by thomcc** [comment]
Hm, good point. For some reason, I thought we had already done a release of this.

@gwenn, is there anything you'd like to get into a release before we cut one?

**Comment by thomcc** [comment]
Hmm, if there's nothing by the weekend I'll do the release anyway. (I guess it would be nice to do #1010, which is great but I probably won't have time to review it until the start of oct, unfortunately).

**Comment by gwenn** [comment]
> @gwenn, is there anything you'd like to get into a release before we cut one?

Sorry, I was on vacation...
And there is already a draft for a 0.26.0 release:
> Nice to have: make possible to remove authorizer hook

**Comment by thomcc** [comment]
No worries, I figured it was something like that. Do you want to wait for that or no?

No rush either way, I can probably help out some next weekend if there's any work blocking stuff too.

**Comment by thomcc** [comment]
> Nice to have: make possible to remove authorizer hook

It seems already possible to do this? E.g. I think you can currently do this:

```rs
use rusqlite::hooks::{AuthContext, Authorization};
some_conn.authorizer(None::<fn(AuthContext<'_>) -> Authorization>);
```

Or maybe I misunderstood you before.

**Comment by gwenn** [comment]
> > Nice to have: make possible to remove authorizer hook
> 
> It seems already possible to do this? E.g. I think you can currently do this:
> 
> ```rust
> use rusqlite::hooks::{AuthContext, Authorization};
> some_conn.authorizer(None::<fn(AuthContext<'_>) -> Authorization>);
> ```
> 
> Or maybe I misunderstood you before.

You are right.

**Comment by douloiha** [comment]
Sorry guys I was offline for a few days. Thank you for your answers, I'm glad to know these new features will be soon released. Is there anything I can do to help?

**Comment by gwenn** [comment]
@thomcc let me know if you want me to release the new version.

**Comment by gwenn** [comment]
Version 0.26.0 released
