### ISSUE TITLE
[Docs] "Positional params of varying types" doesn't have varying types?

### ISSUE THREAD

**Issue by tobymurray** [rusqlite/rusqlite#1029]
I think this is an example of there being room for more helpful docs: https://docs.rs/rusqlite/0.26.0/rusqlite/struct.Connection.html#with-positional-params-of-varying-types

![image](https://user-images.githubusercontent.com/3683198/136729513-f90b51fd-0f05-4433-9c37-99ad26b98569.png)

This only has a single parameter, so does not demonstrate varying types (as far as I understand). I'm open to submitting a PR with a more elaborate example if this is the case.

**Comment by thomcc** [comment]
Good point! I imagine this got introduced when we removed the need to use `params![]` in as many cases.

I'd happily merge a PR with better docs — probably something that uses `params!`, which is the common way people will perform queries with varying types. Feel free if you need me to elaborate.
