### ISSUE TITLE
Rusqlite leaves sqlite database locked after commiting transaction

### ISSUE THREAD

**Issue by FairyTail2000** [rusqlite/rusqlite#1038]
Note: I'm using Rust 2021, but the problem is exactly the same.

When executing the code in this [example gist](https://gist.github.com/FairyTail2000/7bfa51388b2bd0994ec9639ea6862439) and then try to open the sqlite database in CLion I get the an Exception that the database file is locked. It does open fine if I use the sqlite3 cli utility and I can dump the data. Which means the data got committed and written to disk but the database isn't unlocked.

I'm on Windows 10 compiling, linking, running and having all the files inside WSL 2 Ubuntu 20.04.

Cargo version: 1.56.0
rustc version: 1.56.1

If any more info is required, I will be happy to provide it

**Comment by gwenn** [comment]
If sqlite3 cli is fine but not CLion, the bug is in CLion, no ?

**Comment by RafaelSundorf** [comment]
I have tested a thing more in sqlite3 cli and I encountered the same error in the cli, which was as expected when I tried to write to the db

**Comment by gwenn** [comment]
And not related but there is no need to explicitly begin a transaction for a [single](https://gist.github.com/FairyTail2000/7bfa51388b2bd0994ec9639ea6862439#file-main-rs-L47) statement:
https://www.sqlite.org/lang_transaction.html#implicit_versus_explicit_transactions

**Comment by RafaelSundorf** [comment]
I know, I planned to do way more in that transaction but failed at that single thing

**Comment by gwenn** [comment]
[On Windows you can use Sysinternal's Process Monitor to monitor who is accessing the file](https://stackoverflow.com/a/8996723).

**Comment by RafaelSundorf** [comment]
I could replicated a similar behavior on a raspberry pi, running Raspbian with the 5.10.60

Cross compiled using cross, the program just never stops on the raspberry while on windows it stops but leaves the database in a locked state
