### ISSUE TITLE
screwy update_hook lifetime raises SIGSEGV

### ISSUE THREAD

**Issue by sqwishy** [rusqlite/rusqlite#1048]
The following compiles (in release mode) but will segfault trying to unlock the mutex after the mutex is destroyed. The example runs fine if `move` is added to the closure because the mutex isn't dropped after `update_hook()`.

The `Arc` & `Mutex` isn't important, it could be a `Vec` or anything but it's allowed to be dropped after `update_hook()`.  I guess ideally the lifetimes should be a bit more precise so this can't compile?

``` rust
use rusqlite::{hooks::Action, Connection};
use std::sync::{Arc, Mutex};

fn main() {
    let db = Connection::open_in_memory().unwrap();

    {
        let locked: Arc<Mutex<()>> = Arc::new(Mutex::new(()));

        let hook = |_: Action, _: &str, _: &str, _: i64| {
            if let Ok(ref mut mutex) = locked.try_lock() {
                **mutex = ();
            }
        };

        db.update_hook(Some(hook));
    };

    db.execute("CREATE TABLE tbl(i integer)", []).unwrap();
    db.execute("INSERT INTO tbl (i) VALUES (1)", []).unwrap();
}
```

```
rusqlite = { version = "0.26", features = ["hooks"] }
```

Also tested on master (currently at d70fbac2314333ecf2e67db43dbb43b0a47a4797).

**Comment by gwenn** [comment]
There is already a lifetime constraint:
https://github.com/rusqlite/rusqlite/blob/dcaa67a6172571f4e7d26a879d77da21bcacaf71/src/hooks.rs#L378-L380
but it doesn't work!?

**Comment by gwenn** [comment]
Bug introduced by https://github.com/rusqlite/rusqlite/commit/926977846fd0c4ec8e77fcaa9a6c39e9021a4663 ?

**Comment by jgallagher** [comment]
That lifetime constraint doesn't work as intended. Here's a playground example with a similar lifetime that ends up storing a raw pointer to an address on the stack that is no longer valid: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=0c702334cac58af1536eca86114e81b3

IIUC, the `'c` lifetime on `update_hook()` just means the compiler has to find some lifetime that can be satisfied where both `&self` and `F` are alive; it does _not_ mean "the full lifetime of self". In this example code at the top, the lifetime it finds is the lifetime of the reference to locked: both the closure and `&self` live at least that long, so it compiles.

I don't think it's possible for a struct that doesn't contain lifetimes of its own to have a method that takes a reference that must live at least as long as itself, but I'd love to be wrong about that! I agree the commit you linked probably introduced the bug; requiring `'static` would definitely prevent the segfaulting example above from compiling.

**Comment by thomcc** [comment]
Yeah, this needs to be 'static. It can't be a borrowed lifetime because `Connection` is static, as mentioned.

Oof.

**Comment by thomcc** [comment]
This was introduced by https://github.com/rusqlite/rusqlite/pull/825, and doesn't exist prior to 0.25.0, thankfully (should have been more careful in the review... 😞).

It's just one version, so I'll cut a 0.25.4 hotfix release (#1054) in addition to the 0.26.2 release (#1053). After releases with fixes are up, I'll yank the impacted versions and file an advisory.

**Comment by thomcc** [comment]
Sorry for the delay. 0.25.4 and 0.26.2 are released, an advisory has been filed, and the impacted versions have been yanked, so I don't think there's anything else to do here. Please feel free to reach out with other issues.

P.S. While I have a moment, I'll just say fairly sorry (embarrassed, even) that this got through. At the time when I reviewed the code introducing the bug, had an... unfortunate amount on my mind (it was very shortly after I had been laid off from Mozilla, which was a job I had for several years), so I didn't think carefully enough, even though this is a pattern I know to look out for.

Still, one of the reasons I tell people to use `rusqlite` is that I try to be thorough about this kind of thing, so... yeah, hopefully this doesn't damage people's trust in us too much. Thanks.

**Comment by benesch** [comment]
> P.S. While I have a moment, I'll just say fairly sorry (embarrassed, even) that this got through. At the time when I reviewed the code introducing the bug, had an... unfortunate amount on my mind (it was very shortly after I had been laid off from Mozilla, which was a job I had for several years), so I didn't think carefully enough, even though this is a pattern I know to look out for.

Writing unsafe code correctly is _hard_. You don't need to apologize! We're so lucky to have people like you donating their time to projects like this.
