### ISSUE TITLE
Readme still states bundled SQLite is 3.36.0

### ISSUE THREAD

**Issue by Roenbaeck** [rusqlite/rusqlite#1055]
The Readme should be updated to indicate that the bundled SQLite is version 3.37.0 since rusqlite 0.26.2.

**Comment by gwenn** [comment]
See https://github.com/rusqlite/rusqlite/pull/1023/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5
Before next release, we will update Readme with 3.37.0 or 3.37.1 or 3.38.0...
