### ISSUE TITLE
Replace impl_for_array_ref with stabilized const generics for Params impl

### ISSUE THREAD

**Issue by Ciantic** [rusqlite/rusqlite#1068]
I'm writing some generic code, where I could use `const N: usize` impl for the Params. Currently I'm getting errors such as:

```
the trait bound `[&dyn ToSql; N]: Params` is not satisfied
the following implementations were found:
  <&[&T; 10] as Params>
  <&[&T; 11] as Params>
```

Would it be possible to replace the `impl_for_array_ref` with now stabilized const generics? 

I think it could be replaced with something like:

```rust
impl<T: ToSql + ?Sized, const N: usize> Params for &[&T; N] {
    #[inline]
    fn __bind_in(self, stmt: &mut Statement<'_>) -> Result<()> {
        stmt.bind_parameters(self)
    }
}
```

**Comment by Ciantic** [comment]
I tried implementing this, I think the only hairy part is that calls with empty array can't be untyped, e.g.

```
self.query_row(&query, [], f) // It can't infer the empty array
```

It's a bit unfortunate that `[]` was chosen as emptiness instead of `params![]` which could have added the type definition for emptiness by default. I think this is not yet possible without api change 

In future it might be when there is ability to write Non-Empty guarantees for the `const N: usize`, there has been talk [about adding it to Rust](https://internals.rust-lang.org/t/const-generics-where-restrictions/12742/4) e.g. pseudocode `impl<T: ToSql, const N: usize> Sealed for [T; N] where {N > 0} {}`

**Comment by thomcc** [comment]
I think you can probably use https://docs.rs/rusqlite/latest/rusqlite/struct.ParamsFromIter.html, no?

**Comment by thomcc** [comment]
> It's a bit unfortunate that [] was chosen as emptiness instead of params![] which could have added the type coercion for emptiness by default. I think this is not yet possible without api change

It used to be that way, and it was significantly more painful to use. We decided to optimize for the common case (smallish, fixed parameter lengths, and especially the empty parameter set), and push most complex cases to use something like ParamsFromIter.

If there's some reason ParamsFromIter can't work, I'd be willing to make a ParamsFromArray<T, N>([T; N]) or something, but arrays impl IntoIterator<Item = T> now, so you should be able to use it.

**Comment by thomcc** [comment]
Yes, this using `ParamsFromIter`/`params_from_iter` works fine: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=72031b051cbce7ceb29ac6bd2c22a73c

**Comment by Ciantic** [comment]
Oh I feel dumb again. Thanks! I was not aware of this `params_from_iter`, it works fine for me.

**Comment by thomcc** [comment]
Glad to hear it.
