### ISSUE TITLE
Upgrade bundled sqlcipher to 4.5.0

### ISSUE THREAD

**Issue by link2xt** [rusqlite/rusqlite#1072]
There is a new release tagged already on https://github.com/sqlcipher/sqlcipher/, but bundled sqlcipher is still 4.4.3

**Comment by gwenn** [comment]
Could you please try to send a PR by running this [script](https://github.com/rusqlite/rusqlite/blob/master/libsqlite3-sys/upgrade_sqlcipher.sh#L12) (ideally on linux machine or VM): just fix the `SQLCIPHER_VERSION` before executing the script.

**Comment by link2xt** [comment]
Created a PR #1073
