### ISSUE TITLE
Potential error in the documentation 

### ISSUE THREAD

**Issue by YounessBird** [rusqlite/rusqlite#1121]
In the `rusqlite::Statement` the `query` method is documented as follow 

> Due to lifetime restrictions, the rows handle returned by `query` does not implement the Iterator trait. Consider using [query_map](https://docs.rs/rusqlite/latest/rusqlite/struct.Statement.html#method.query_map) or [query_and_then](https://docs.rs/rusqlite/latest/rusqlite/struct.Statement.html#method.query_and_then) instead, which do.

I think the returned handle does implement `Iterator` but not `IntoIterator` as shown in the following code 

```
fn get_names(conn: &Connection) -> Result<Vec<String>> {
    let mut stmt = conn.prepare("SELECT name FROM people")?;
    let mut rows = stmt.query([])?;

    let mut names = Vec::new();
    while let Some(row) = rows.next()? { // rows implements Iterator not IntoIterator 
        names.push(row.get(0)?);
    }

    Ok(names)
}
```

**Comment by adumbidiot** [comment]
[No, it just has a method of the same name.](https://docs.rs/rusqlite/latest/rusqlite/struct.Rows.html#method.next). I don't think it implements `IntoIterator` either.

**Comment by YounessBird** [comment]
Yes that makes sense now thanks [adumbidiot](https://github.com/adumbidiot)
