### ISSUE TITLE
Export include directory

### ISSUE THREAD

**Issue by Sytten** [rusqlite/rusqlite#1126]
It would be nice to export the include directory so upstream crates can include them in their build.
This is needed if you want to build extensions and link them statically.
Looking at the code it might be more annoying to do than I previously anticipated because of the different ways of building the `libsqlite3-sys` crate.
Maybe we could start with just supporting the static build?

**Comment by thomcc** [comment]
I think for the bundled build its reasonable. There are a lot of situations still, but I have some changes there planned anyway. I'll take a look at this in a week or two.

**Comment by gwenn** [comment]
Fixed by #1441 (I may be wrong)

**Comment by gwenn** [comment]
Version 0.31.0 released
