### ISSUE TITLE
Error offsets

### ISSUE THREAD

**Issue by yrns** [rusqlite/rusqlite#1130]
Are there any plans to include the results of the new `sqlite3_error_offset` into rusqlite's errors? I am working on an LSP server for sqlite and it would be useful for diagnostics.

**Comment by gwenn** [comment]
You should already be able to use it with [this](https://docs.rs/rusqlite/latest/rusqlite/struct.Connection.html#method.handle) and `bundled_bindings` or `buildtime_bindgen` features, no ?
But we can also append this offset to `SqliteFailure` behind the `modern_sqlite` feature.

**Comment by yrns** [comment]
Using the handle and bundled works for me. Thank you!

**Comment by edbaskerville** [comment]
Was just wondering about this myself—just chiming in to say, I second this request. It would be a bit nicer not to have to drop down to the lower level.

**Comment by gwenn** [comment]
Version 0.28.0 released.
