### ISSUE TITLE
Connection::update_hook question

### ISSUE THREAD

**Issue by justinmoon** [rusqlite/rusqlite#1150]
Does [`Connection::update_hook`](https://docs.rs/rusqlite/latest/rusqlite/struct.Connection.html#method.update_hook) only work for that one connection?

I setup `update_hook` on one connection and make writes using a different connection and the writes aren't registering with the hook. But they do show up if I use the same connection for the hook and the writes.

My usecase is that I have a node.js application and want a listener to see all database changes via `sqlite3_update_hook`. AFAICT no node.js libraries can do this, so I'm trying to get rusqlite to do it and using [Neon](https://neon-bindings.com/) to hook node.js and Rust together. So I probably won't be able to use the same connection for everything since I'm using 2 different languages, unless I do all my SQLite operations in Rust land ...

**Comment by gwenn** [comment]
https://www.mail-archive.com/sqlite-users@mailinglists.sqlite.org/msg100570.html
>> Does a registered sqlite3_update_hook get called when _any_ SQLite connection 
>> modifies the database (not just the connection it's registered with)?

> No, only the connection it's registered with.
