### ISSUE TITLE
Unable to call set_result_subtype at the appropriate time

### ISSUE THREAD

**Issue by mullr** [rusqlite/rusqlite#1157]
I see that you have added a binding for `sqlite3_result_subtype`, which is great, that's exactly the thing I need! However, this needs be called /after/ `sqlite3_result_*` in order to take effect, which isn't currently possible. 

Do you have something in mind for how to do it? I'd be happy to implement it if it's reasonably straightforward.

**Comment by mullr** [comment]
I've hacked around this over at https://github.com/mullr/rusqlite/tree/set_result_hack by adding a FunctionFlag value to ignore the return value of the user provided function. I also exposed `set_result` on `Context`, so user code can call `set_result` and then `set_result_subtype`. 

As the branch name suggests, this not that nice. But maybe it's ok? The surrounding types don't leave much room for maneuvering without some pretty major surgery, afaict.

**Comment by gwenn** [comment]
What about:
```rust
pub trait SubType : ToSql {
   fn sub_type(&self) -> Option<c_uint> {
     None
   }
}
```
?

**Comment by mullr** [comment]
That seems like a great API. It would either require that the `create_*_function` calls use that as a type constraint instead of `ToSql`, breaking existing users, or adding new variants of `create_*_function` that allow this type. Is one of those preferable?

**Comment by gwenn** [comment]
@mullr Could you please check #1160 ?

**Comment by mullr** [comment]
@gwenn #1160 looks good to me. Thanks for putting that together!

**Comment by gwenn** [comment]
Version 0.31.0 released
