### ISSUE TITLE
Support WAL hook

### ISSUE THREAD

**Issue by quasicomputational** [rusqlite/rusqlite#1187]
[`sqlite3_wal_hook`](https://www.sqlite.org/c3ref/wal_hook.html) is a hook which rusqlite currently doesn't have bindings for; it's useful if you want fine-grained control over the WAL mechanism and want to know when to trigger it. It'd be nice if rusqlite had a convenient binding for it like it does for commit hooks etc.

**Comment by gwenn** [comment]
You can already play with it: [Connection::handle](https://docs.rs/rusqlite/latest/rusqlite/struct.Connection.html#method.handle) + [ffi::sqlite3_wal_hook](https://github.com/rusqlite/rusqlite/blob/master/libsqlite3-sys/sqlite3/bindgen_bundled_version.rs#L4245)

**Comment by gwenn** [comment]
Version 0.33.0 released
