### ISSUE TITLE
params question

### ISSUE THREAD

**Issue by cisaacson** [rusqlite/rusqlite#1190]
We need to return a list of heterogeneous params and pass them to another method that will build the prepared statement and execute it. It seems the only want to do this is with the `params![]` macro since we have binary (blob), integer, and text types. We are having trouble getting the references to work right.

Our params have a fixed length for each query known in advance, so we could code gen them using a build script. But of course we will not know the values in advance at code gen time, just the number and types.

We have an enum type with all of our values, so we can store the params in a Vec<RValue>, and access like this:

```
fn to_sqlite_param_list(&self) -> Result<&[&dyn ToSql], Box<dyn Error>> {
        Ok((params![RValue::BigInt(57u64).as_bigint()?]))
    }
```
That example is made up as a literal is passed in, but it's basically the same as what we want to do (but with many params). We'd really like to use our Vec<RValue> like this:

`Ok([params![my_vec[0].as_bigint()?])`

Can you provide an example of how this should work? Both of the above examples complain about the temp value being dropped.

The as_big_int() signature looks like this from the enum method:

```
pub fn as_bigint(self) -> Result<u64, Box<dyn Error>> {
        match self {
            RValue::BigInt(v) => Ok(v),
            _ => {
                return Err(ValueCodecError::new(&format!("Expected BigInt variant.")))?;
            }
        }
    }
```
We have other methods for Strings too.

Any help appreciated.

**Comment by gwenn** [comment]
Maybe just use https://docs.rs/rusqlite/latest/rusqlite/struct.Statement.html#method.raw_bind_parameter ?

**Comment by thomcc** [comment]
I think https://docs.rs/rusqlite/latest/rusqlite/fn.params_from_iter.html should also be usable in these cases.
