### ISSUE TITLE
Working uuid example?

### ISSUE THREAD

**Issue by aguynamedben** [rusqlite/rusqlite#1233]
Hi, this crate is awesome.

Is there a working example of the `uuid` feature? I think I'm very close to having it working, but SELECTing uuids from my database isn't working and I can't find any documentation.

**Code**
```rs
use rusqlite::{Connection, Result};
use uuid::Uuid;

// ... some boilerplate...

#[derive(Debug)]
struct Doc {
  uuid: Uuid,
  title: String,
  hits: Option<usize>,
}

fn get_sample_docs(conn: &Connection) -> Result<Vec<Doc>> {
  let mut stmt = conn.prepare("SELECT uuid, title FROM Docs LIMIT 10")?;
  let doc_iter = stmt.query_map([], |row| {
    Ok(Doc {
      uuid: row.get_unwrap::<_, Uuid>(0),
      title: row.get(1)?,
      hits: None,
    })
  })?;

  let mut docs = Vec::new();
  for doc in doc_iter {
    docs.push(doc?)
  }

  Ok(docs)
}
```

I got the `.get_unwrap()` syntax from [this ticket](https://github.com/rusqlite/rusqlite/issues/1186).

**Error**
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidColumnType(0, "uuid", Text)'
```

**My table is using the uuid type**
<img width="580" alt="image" src="https://user-images.githubusercontent.com/107841/193778489-3454835e-3505-4bd5-a641-f183edc3d133.png">

**I also tried using CAST**
```sql
SELECT CAST(Docs.uuid AS uuid) -- ... and so on...
```
which got me the same type of error but with Integer instead of Text in the error message
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidColumnType(0, "CAST(Docs.uuid AS uuid)", Integer)',
```

It seems like I need to modify my to coerce SQLite to return a type for `Docs.uuid` that rqlite will be happy with, but I can't figure out what that is.

Thank you! This is such a fantastic project. 🙏

**Comment by aguynamedben** [comment]
**My Cargo.toml**
```toml
[dependencies]
rusqlite = { version = "0.28.0", features = ["bundled-sqlcipher-vendored-openssl", "uuid"] }
uuid = { version = "1.1.2", features = ["v4"] }
```

**Comment by gwenn** [comment]
https://github.com/rusqlite/rusqlite/blob/350c8de1b03bf0d2e4245deb56fcded1b1810a48/src/types/to_sql.rs#L403-L428

`Uuid` should be stored as a BLOB.
