### ISSUE TITLE
Error building libsqlite3-sys v0.25.2 in WSL2 on NTFS drive

### ISSUE THREAD

**Issue by alensiljak** [rusqlite/rusqlite#1254]
Trying to add SQLite support to a Rust application. So far went through several crates but they all depend on libsqlite3-sys, therefore all have the same issue.

Building (`crate build`) the application fails with 
```
   Compiling libsqlite3-sys v0.25.2
error: failed to run custom build command for `libsqlite3-sys v0.25.2`

Caused by:
  process didn't exit successfully: `/mnt/d/src/pricedb-rust/target/debug/build/libsqlite3-sys-85871a1a1dec6be7/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'Could not copy bindings to output directory: Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }', /home/alen/.cargo/registry/src/github.com-1ecc6299db9ec823/libsqlite3-sys-0.25.2/build.rs:102:18
  stack backtrace:
     0:     0x55f4870ad300 - std::backtrace_rs::backtrace::libunwind::trace::h32eb3e08e874dd27
                                 at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
```
etc.

I've tried both in Alpine and Debian distributions running under Windows Subsystem for Linux (WSL2). The build directory is on an NTFS volume, mounted in WSL. This does not seem to affect normal development otherwise.
The error puzzles me.

rusqlite is added to Crate.toml as
```
rusqlite = { version = "0.28.0", features = ["bundled"] }
```

Let me know, please, if I can provide any additional useful information.

**Comment by alensiljak** [comment]
Inside the libsqlite3-sys crate source directory, there is a `sqlite3` directory:
```
~/.cargo/registry/src/github.com-1ecc6299db9ec823/libsqlite3-sys-0.25.2$ dir sqlite3/
total 9248
drwxr-xr-x 2 alen alen    4096 Nov 15 21:09 ./
drwxr-xr-x 6 alen alen    4096 Nov 15 22:13 ../
-rw-r--r-- 1 alen alen  230867 Jul 24  2006 bindgen_bundled_version.rs
-rw-r--r-- 1 alen alen 8546396 Jul 24  2006 sqlite3.c
-rw-r--r-- 1 alen alen   37310 Jul 24  2006 sqlite3ext.h
-rw-r--r-- 1 alen alen  613416 Jul 24  2006 sqlite3.h
-rw-r--r-- 1 alen alen   21443 Jul 24  2006 wasm32-wasi-vfs.c
```

**Comment by alensiljak** [comment]
The build succeeded when `sqlite` crate was used:
```
  Downloaded sqlite v0.30.1
  Downloaded sqlite3-sys v0.14.0
  Downloaded sqlite3-src v0.4.0
  Downloaded 3 crates (2.6 MB) in 1.48s (largest was `sqlite3-src` at 2.5 MB)
   Compiling sqlite3-src v0.4.0
   Compiling sqlite3-sys v0.14.0
   Compiling sqlite v0.30.1
```

**Comment by gwenn** [comment]
> Could not copy bindings to output directory: Os { code: 1, kind: **PermissionDenied**, message: "Operation not permitted" }

https://github.com/rusqlite/rusqlite/blob/master/libsqlite3-sys/build.rs#L101-L102
I don't know why but there is an issue while copying bindgen file to '/mnt/d/src/pricedb-rust/target/debug/...' directory.

**Comment by gwenn** [comment]
https://stackoverflow.com/questions/73979236/could-not-copy-bindings-to-output-directory-when-building-rocket-with-sqlite-a
but no answer...

**Comment by alensiljak** [comment]
Is there a way to debug the values `lib_name` or `out_path`? There are other files in the output directory and when not building libsqlite, the build works just fine. I'm not sure what can I check.
I was trying to modify the build.rs but that has no effect on the executed code, I guess.

```
drwxrwxrwx 1 root root 4096 Nov 16 18:41 ./
drwxrwxrwx 1 root root 4096 Nov 16 01:40 ../
drwxrwxrwx 1 root root 4096 Nov 16 18:43 build/
drwxrwxrwx 1 root root 4096 Nov 16 18:44 deps/
drwxrwxrwx 1 root root 4096 Nov 16 18:41 examples/
drwxrwxrwx 1 root root 4096 Nov 16 18:43 .fingerprint/
drwxrwxrwx 1 root root 4096 Nov 16 18:41 incremental/
-rwxrwxrwx 1 root root    0 Nov 16 18:41 .cargo-lock*
```

**Comment by alensiljak** [comment]
I have to add, when using the same WSL session, but cloning the same repo to the local disk (ext4), the build succeeds.

**Comment by alensiljak** [comment]
Interesting, the crate `sqlite` seems to use an older version of libsqlite-sys and that compiles without problems.

**Comment by gwenn** [comment]
https://github.com/rusqlite/rusqlite/blob/master/libsqlite3-sys/build.rs#L30-L31 => `out_path` ==  `$OUT_DIR/bindgen.rs`
https://github.com/rusqlite/rusqlite/blob/master/libsqlite3-sys/build.rs#L322 => `lib_name` == `sqlite3`
`cargo build -vv` to show `OUT_DIR`

**Comment by gwenn** [comment]
[`sqlite3-sys`](https://crates.io/crates/sqlite3-sys/0.14.0/dependencies) doesn't use bingen, has [no](https://github.com/stainless-steel/sqlite3-sys) `build.rs` script.

**Comment by thomcc** [comment]
We should eventually allow the pregenerated bindings to be usable without the build script running, so that build script overrides (https://doc.rust-lang.org/cargo/reference/build-scripts.html#overriding-build-scripts) can work.

That said this seems like a system configuration issue on the part of the user.

**Comment by alensiljak** [comment]
`target/debug/build` contains
```
─ libsqlite3-sys-85871a1a1dec6be7
    │   │   ├── build-script-build
    │   │   ├── build_script_build-85871a1a1dec6be7
    │   │   └── build_script_build-85871a1a1dec6be7.d
    │   ├── libsqlite3-sys-8dcda8348e63cbca
    │   │   ├── invoked.timestamp
    │   │   └── out
    │   │       └── bindgen.rs
```

**Comment by alensiljak** [comment]
I tried with and without the "bundled" feature, and installing the libsqlite3-dev package, and setting the `SQLITE3_LIB_DIR` and `SQLITE3_INCLUDE_DIR` as per doc, but the issue is the same.

**Comment by alensiljak** [comment]
> That said this seems like a system configuration issue on the part of the user.

Do you have any more precise ideas and did you read my [comment](https://github.com/rusqlite/rusqlite/issues/1254#issuecomment-1317422922)? The configuration is identical in both cases, yet on NTFS it does not work but on EXT4 it does. Something's fishy in there.

**Comment by alensiljak** [comment]
> [`sqlite3-sys`](https://crates.io/crates/sqlite3-sys/0.14.0/dependencies) doesn't use bingen, has [no](https://github.com/stainless-steel/sqlite3-sys) `build.rs` script.

The [src package](https://github.com/stainless-steel/sqlite3-src) also gets built and it has [build.rs](https://github.com/stainless-steel/sqlite3-src/blob/main/build.rs).

This is my second mini-project in Rust. Still trying to understand what's going on. :)

**Comment by gwenn** [comment]
[sqlite-src](https://crates.io/crates/sqlite3-sys/0.14.0/dependencies) is optional...

```
.
└── debug
    ├── build
    │   ├─ libsqlite3-sys-85871a1a1dec6be7
    │   ├── libsqlite3-sys-8dcda8348e63cbca
    │   │   └── out
    │   │       └── bindgen.rs
```
Could you please check the attributes (timestamp, owner, rights) of this file ?
Are you sure this is the one generated by build.rs (-vv + OUT_DIR) ?
Maybe a `cargo clean` before `cargo build` may help ?

**Comment by alensiljak** [comment]
> Could you please check the attributes (timestamp, owner, rights) of this file ? Are you sure this is the one generated by build.rs (-vv + OUT_DIR) ? Maybe a `cargo clean` before `cargo build` may help ?

`-rwxrwxrwx 1 root root    0 Nov 16 20:31 bindgen.rs*`

Strange that it has 0 size. Everything on the NTFS drive is `root root`-owned but with permissions for everyone else, just like this file. Practically, I had no issues in WSL in years.

Tried `clean` (thanks, I was deleting the folder manually before that) but no change.

My current settings are 
```
rusqlite = { version = "0.28.0", features = ["bundled"] }
```
This works just fine in the other clone but I'd rather keep using the repo on NTFS drive due to Git client, SSH agent, keys, testing on Windows with minimal additional effort, etc. 
Thanks for the help!

**Comment by alensiljak** [comment]
The ext4 output:
```
drwxr-xr-x 2 alen alen    4096 Nov 16 19:19 sqlite3/
-rw-r--r-- 1 alen alen  230867 Nov 16 19:19 bindgen.rs
-rw-r--r-- 1 alen alen 5093840 Nov 16 19:19 libsqlite3.a
```
whereas on NTFS just
```
-rwxrwxrwx 1 root root    0 Nov 16 20:38 bindgen.rs*
```

**Comment by thomcc** [comment]
Are you running commands as root? That's probably going to cause issues...

**Comment by alensiljak** [comment]
> Are you running commands as root? That's probably going to cause issues...

No, I have a user account. But everything on Windows drives is somehow marked as root,root. See [comment](https://github.com/rusqlite/rusqlite/issues/1254#issuecomment-1317579454).

**Comment by alensiljak** [comment]
Seems like an issue with how `fs::copy` copies file permissions.

I've tried adding 0777 to all the files in `bindgen-bindings/` and `sqlite3` in `/home/alen/.cargo/registry/src/github.com-1ecc6299db9ec823/libsqlite3-sys-0.25.2/` to no avail.
Also tried `chown root:root` in both directories but the error remains the same.

**Comment by alensiljak** [comment]
Hmm, whatever the issue was, it is now gone. I've been developing inside the WSL on an ext4 partition in the meantime. Just tried building and running the project in the repo on an NTFS partition and it builds and runs just fine. 
Goblins
