### ISSUE TITLE
write access violation in execute batch

### ISSUE THREAD

**Issue by dev-ardi** [rusqlite/rusqlite#1264]
`Stop reason: Exception 0xc0000005 encountered at address 0x7ff62710f39b: Access violation writing location 0x2cdff1d8`

This happened while unit testing, two tests used this function:
```rust
    fn make_harness() -> Connection {

        let con = Connection::open_in_memory().unwrap();
        con.execute_batch(
            "
        CREATE TABLE imgs(url text);
        INSERT INTO imgs VALUES ('banana');
        INSERT INTO imgs VALUES ('mango');
        INSERT INTO imgs VALUES ('kiwi');
        INSERT INTO imgs VALUES ('3');
        INSERT INTO imgs VALUES ('4');
        INSERT INTO imgs VALUES ('5');
        INSERT INTO imgs VALUES ('6');
        INSERT INTO imgs VALUES ('7');
        INSERT INTO imgs VALUES ('8');
        INSERT INTO imgs VALUES ('9');
        INSERT INTO imgs VALUES ('10');
        INSERT INTO imgs VALUES ('11');
        INSERT INTO imgs VALUES ('12');
        INSERT INTO imgs VALUES ('13');
        INSERT INTO imgs VALUES ('14');
        INSERT INTO imgs VALUES ('15');
        INSERT INTO imgs VALUES ('16');
        INSERT INTO imgs VALUES ('17');
        INSERT INTO imgs VALUES ('18');
        ",
        )
        .unwrap()        
    }
```    
   The first test works fine, but the second one just hangs in `execute_batch`.
   Only by debugging I was able to find the problem.

**Comment by dev-ardi** [comment]
Running only the second test still hangs... the line it hangs at is exactly the same: 
```rust
 let x = make_harness();
```

**Comment by gwenn** [comment]
Sorry but without a complete example to reproduce your error, we cannot help you.
`rusqlite` is available on [playground](https://play.rust-lang.org).
Could you please provide a complete minimalist example to reproduce your problem (with the "Share" button at top right) ?
It is ok if the exact same code run without error on the playground but crash on your side.

**Comment by gwenn** [comment]
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=9c6eefd6905efca4ae1876acbc6a1e29
```
error[[E0308]](https://doc.rust-lang.org/stable/error-index.html#E0308): mismatched types
  --> src/main.rs:5:5
   |
3  |   fn make_harness() -> Connection {
   |                        ---------- expected `Connection` because of return type
4  |       let con = Connection::open_in_memory().unwrap();
5  | /     con.execute_batch(
6  | |         "
7  | |         CREATE TABLE imgs(url text);
8  | |         INSERT INTO imgs VALUES ('banana');
...  |
28 | |     )
29 | |     .unwrap()
   | |_____________^ expected struct `Connection`, found `()`
```

**Comment by dev-ardi** [comment]
I edited the code to make it clearer. I didn't expect it to work

**Comment by dev-ardi** [comment]
I can't replicate the error anyways. The hanging was due to a bug in my code, but I promise that the access violation existed
