### ISSUE TITLE
Consider removing/obscuring the `winsqlite3` feature?

### ISSUE THREAD

**Issue by davidbarsky** [rusqlite/rusqlite#1270]
Hi folks! This is a bit of an odd issue (and I apologize if you're already aware of this!), but it seems like the compiled version of SQLite inside of Windows is only meant to be used by projects that are bundled as part of the Windows operating system ( https://github.com/microsoft/win32metadata/issues/824#issuecomment-1067220882), _not_ non-Microsoft projects.

If removal isn't in the cards, would you all consider moving it behind `RUSTFLAGS` (e.g., as [Tokio does](https://docs.rs/tokio/latest/tokio/#unstable-features)) to reduce the hazard of accidentally enabling this feature?

**Comment by thomcc** [comment]
Yeah, I've wanted to remove it for a while.

**Comment by gwenn** [comment]
Partially fixed in libsqlite3-sys v0.28.0

**Comment by gwenn** [comment]
Version 0.31.0 released
