### ISSUE TITLE
Add query_map with positional parameters to documentation

### ISSUE THREAD

**Issue by dessalines** [rusqlite/rusqlite#1276]
The [current query_map docs](https://docs.rs/rusqlite/latest/rusqlite/struct.Statement.html#method.query_map) don't actually show positional parameters:

```rs
let mut stmt = conn.prepare("SELECT name FROM people")?; // Zero parameters here
let rows = stmt.query_map([], |row| row.get(0))?; // Parameter array is empty
```

It should show:

```rs
let mut stmt = conn.prepare("SELECT name FROM people where name = ?1")?;
let rows = stmt.query_map(["terry"], |row| row.get(0))?;
```

**Comment by gwenn** [comment]
Or:
```rust
let mut stmt = conn.prepare("SELECT name FROM people where name = :name")?;
let rows = stmt.query_map([(":name", "terry")], |row| row.get(0))?;
```
Or:
```rust
let mut stmt = conn.prepare("SELECT name FROM people where name = ?1")?;
let rows = stmt.query_map(params!["terry"], |row| row.get(0))?;
```
Or...
This is why there is a dedicated page for [Params](https://docs.rs/rusqlite/latest/rusqlite/trait.Params.html).

**Comment by dessalines** [comment]
Gotcha. In that case the query_map could link to that params page, instead of showing its own versions of named params, etc.

**Comment by gwenn** [comment]
But there is already such a link to the `Params` page...
