### ISSUE TITLE
Access column names from `Row`

### ISSUE THREAD

**Issue by plut** [rusqlite/rusqlite#1279]
As any failed `row.get()` call will show, the `Row` structure has information about its column headers. (Inspecting the source shows that it even contains the whole statement). However, it is not possible to access this information using the public API: namely, `self.stmt` is `pub(crate)`.

Suggestion: add a `column_name(&self, idx: I)` method to `Row`.

And the use case is the following: for an application using a database, displaying appropriate error messages when something unexpected happens database-side (i.e. dumping the whole structure of the row obtained); this can also probably be done via passing both `Row` and `Statement` to the error reporting function, but this is ugly (and might even somehow mess with borrowing).

**Comment by gwenn** [comment]
Two days ago: #1278
