### ISSUE TITLE
Support more types from the `time` crate

### ISSUE THREAD

**Issue by czocher** [rusqlite/rusqlite#1281]
From what I noticed in [`time.rs`](https://github.com/rusqlite/rusqlite/blob/master/src/types/time.rs) only the `time::OffsetDateTime` type is supported by default. 

I'd like to implement support for the other following types:
* `time::Date`
* `time::Time`
* `time::Instant`
* `time::Duration`
* `time::PrimitiveDateTime`
* `time::UtcOffset`
* `time::Weekday`
* `time::Month`

Is this something that you'd accept as a PR?

**Comment by gwenn** [comment]
Only `Date` (like chrono `NaiveDate`), `Time` (like chrono `NaiveTime`) and `PrimitiveDateTime` (like chrono `NaiveDateTime`) seem meaningful to me.

**Comment by Czocher** [comment]
@gwenn true, those are the most useful ones. I'll implement only those three. I assume you would find this change meaningful?

**Comment by gwenn** [comment]
Only if `FromSql`/`ToSql` implementations behave like the `chrono` ones.

**Comment by Czocher** [comment]
@gwenn thanks for the heads-up, I'll concentrate on achieving that :)

**Comment by gwenn** [comment]
Fixed with `rusqlite` version 0.30.0
