### ISSUE TITLE
A way to avoid panic on drop behavior?

### ISSUE THREAD

**Issue by mhammond** [rusqlite/rusqlite#1292]
Hi,
  We are using rusqlite (indirectly) behind an `Arc<>`  in a context where `panic=abort` (desktop Firefox). As a result, because `close()` consumes `self`, we can't absolutely guarantee that at shutdown time we can `Arc::try_unwrap()` to get ownership of the connection to call `close()` on and `mem::forget` it on failure. This means there's a chance that as the app shuts down the app will abort as it is dropped. We'd much rather leak the connection than abort.

I assume the panic is desirable in some use-cases, otherwise I'd suggest that on drop rusqlite either ignores the error or uses `sqlite_close_v2`. I'm not sure in which contexts it would actually be desirable though - if consumers really want to notice the error they still have the explicit close available.

Alternatively, maybe a new boolean could be introduced 👋 somewhere 👋 to control this behavior?

Either way, I'd be happy to put a PR up once I know what approach, if any, would be likely to be accepted.

**Comment by gwenn** [comment]
Just for reference, [rust-postgres](https://github.com/sfackler/rust-postgres/blob/844a27a074c9905832752b736073a4a68d616c7a/postgres/src/client.rs#L560-L578) doesn't panic.

**Comment by thomcc** [comment]
I think it's reasonable for us to not panic on drop ever. In general that behavior is pretty discouraged now in the standard library.

**Comment by mhammond** [comment]
Yeah, I did read that `sqlite_close_v2()` was intended for GC languages, but it also says it 'makes arrangements to automatically deallocate the database connection after all prepared statements are finalized, all BLOB handles are closed, ...' - it's not clear that would actually happen in this scenario, but it thought it sounds like it can't hurt  :)

But thanks, I'll put up a trivial PR to just not panic on drop.

**Comment by Sytten** [comment]
I happen to need `sqlite3_close_v2` because I am writing a Sqlite interface for `quickjs`. So while it is true that Rust is deterministic that doesn't mean all use cases are. It should at least not be filtered out of the binding.
