### ISSUE TITLE
SqlInputError

### ISSUE THREAD

**Issue by yollpoll** [rusqlite/rusqlite#1296]
**here is the log:**
SqlInputError { error: Error { code: Unknown, extended_code: 1 }, msg: "near \"?\": syntax error", sql: "CREATE TABLE IF NOT EXISTS ? (\n        INTEGER PRIMARY KEY,\n        name    TEXT NOT NULL,\n        data    BLOB\n        )", offset: 27 }', src/main.rs:77:34
**and here is my code:**
        conn.execute(
            "CREATE TABLE IF NOT EXISTS ? (
        id      INTEGER PRIMARY KEY,
        name    TEXT NOT NULL,
        data    BLOB
        )",
            params!["person"],
        )?;
![image](https://user-images.githubusercontent.com/15819760/222647109-d2fe7748-cb7d-4aac-845e-013a2ea8ed2a.png)

**Comment by gwenn** [comment]
Not related to `rusqlite`.
You cannot use placeholder here.
You can use the SQLite shell to check by yourself:
```sh
sqlite> .parameter init
sqlite> .parameter set ?1 person
sqlite> SELECT ?;
person
sqlite> CREATE TABLE IF NOT EXISTS ? (x TEXT);
Parse error: near "?": syntax error
  CREATE TABLE IF NOT EXISTS ? (x TEXT);
               error here ---^
```

**Comment by yollpoll** [comment]
> Not related to `rusqlite`. You cannot use placeholder here. You can use the SQLite shell to check by yourself:
> 
> ```shell
> sqlite> .parameter init
> sqlite> .parameter set ?1 person
> sqlite> SELECT ?;
> person
> sqlite> CREATE TABLE IF NOT EXISTS ? (x TEXT);
> Parse error: near "?": syntax error
>   CREATE TABLE IF NOT EXISTS ? (x TEXT);
>                error here ---^
> ```

think your,i get it
