### ISSUE TITLE
ToSql for serde_json::value deserializes incorrectly for strings

### ISSUE THREAD

**Issue by alexculea** [rusqlite/rusqlite#1312]
Reproducible example:
```Rust
    let db = Connection::open_in_memory().unwrap();
    db.execute(
        "CREATE TABLE IF NOT EXISTS 'users' (`name` VARCHAR(100));",
        (),
    )
    .unwrap();
    db.execute("INSERT INTO 'users' (name) VALUES ('Alice');", ())
        .unwrap();
    db.execute("INSERT INTO 'users' (name) VALUES ('\"Bob\"');", ())
        .unwrap(); // notice the extra quotes

    let alice = serde_json::to_value::<String>("Alice".into()).unwrap();
    let bob = serde_json::to_value::<String>("Bob".into()).unwrap();

    let mut stmt = db.prepare("SELECT * FROM users WHERE name=?").unwrap();
    let alice_exists = stmt.exists(rusqlite::params_from_iter([alice])).unwrap();
    let bob_exists = stmt.exists(rusqlite::params_from_iter([bob])).unwrap();

    assert_eq!(alice_exists, true); // panics due to failed assertion but shouldn't
    assert_eq!(bob_exists, false); // same, should be false but it yields true
```

This is because `serde_json::to_string` used [here](https://github.com/rusqlite/rusqlite/blob/8ac4780526b961f53ac6a92bd1f8d3b50a081091/src/types/serde_json.rs#L24), actually yields a string in JSON syntax which is required to be quoted. The de serialized string should not contain quotes.

The example might not look very useful as it's been reduced for the sake of brevity however the bug was discovered when trying to serialize structs into SQL parameters via serde. This makes it impossible to use `params_from_iter` in WHERE clauses because the query will look for the quoted string as well as adding extra quotes on `INSERT` statements.

**Comment by gwenn** [comment]
See #1280 and #882.
`'Alice'` is not a valid JSON value (see [json_valid](https://sqlite.org/json1.html#jvalid))
Maybe you should use [json_quote](https://sqlite.org/json1.html#jquote):
```sql
SELECT * FROM users WHERE name=json_quote(?);
```
Or [json_extract](https://sqlite.org/json1.html#jex)
```sql
sqlite> SELECT json_extract('"Bob"', '$');
Bob
sqlite> SELECT json_extract('Alice', '$');
Runtime error: malformed JSON
```
Or [->>](https://sqlite.org/json1.html#jptr)
```sql
sqlite> SELECT '"Bob"' ->> '$';
Bob
sqlite> SELECT 'Alice' ->> '$';
Runtime error: malformed JSON
```
