### ISSUE TITLE
Is there a way to load extension that is linked statically?

### ISSUE THREAD

**Issue by roeierez** [rusqlite/rusqlite#1319]
Currently the docs always requires a dynamic library to e used in load_extension .
Is there a way to use https://www.sqlite.org/c3ref/auto_extension.html and pass only the entry point?

**Comment by gwenn** [comment]
https://github.com/rusqlite/rusqlite/discussions/1125
https://github.com/rusqlite/rusqlite/issues/1305

**Comment by roeierez** [comment]
Thanks you very much!
