### ISSUE TITLE
Add ToSql/FromSql optional impls for smallstr crate

### ISSUE THREAD

**Issue by ultrabear** [rusqlite/rusqlite#1323]
This is a feature request for ToSql/FromSql implementations for the `SmallString` type from smallstr.

If this change is welcome, but its too much effort to implement I may be able to PR it sometime, please let me know if that's the case!

**Comment by gwenn** [comment]
And you cannot use https://docs.rs/smallstr/0.3.0/smallstr/struct.SmallString.html#method.as_str ?

**Comment by ultrabear** [comment]
That doesn't cover FromSql, which is the main thing I want to support (not having to allocate)

**Comment by gwenn** [comment]
> That doesn't cover FromSql.
Indeed.
So just make sure to do your changes behind a feature.

**Comment by ultrabear** [comment]
closing as the sentiment is to not implement this
