### ISSUE TITLE
Savepoint depth is unnecessary

### ISSUE THREAD

**Issue by Taywee** [rusqlite/rusqlite#1326]
Savepoints nest with the same name naturally.  RELEASE and ROLLBACK with a savepoint name will always match the inner-most savepoint with a matching name.  [Keeping track of the depth is redundant](https://sqlite.org/lang_savepoint.html#transaction_nesting_rules):

> The RELEASE command starts with the most recent addition to the transaction stack and releases savepoints backwards in time until it releases a savepoint with a matching savepoint-name. Prior savepoints, even savepoints with matching savepoint-names, are unchanged. If the RELEASE command causes the transaction stack to become empty (if the RELEASE command releases the outermost transaction from the stack) then the transaction commits.
> 
> The ROLLBACK command with a TO clause rolls back transactions going backwards in time back to the most recent SAVEPOINT with a matching name. The SAVEPOINT with the matching name remains on the transaction stack, but all database changes that occurred after that SAVEPOINT was created are rolled back. If the savepoint-name in a ROLLBACK TO command does not match any SAVEPOINT on the stack, then the ROLLBACK command fails with an error and leaves the state of the database unchanged.

**Comment by Taywee** [comment]
When experimenting with simply removing the depth, I found that some tests failed, because dropping the savepoint still leaves it on the stack when rolling back.

**Comment by gwenn** [comment]
Fixed with `rusqlite` version 0.30.0
