### ISSUE TITLE
Open database from bytes on memory.

### ISSUE THREAD

**Issue by lemunozm** [rusqlite/rusqlite#1348]
I'm in a situation where my database file is already in memory. I would like to read directly from those bytes when creating my connection and not deal with the file system writing the content into a file to read it later from the connection. Ideally, I would expect something like the following to exist:

```rust
Connection::open_in_memory_from_bytes(data: &[u8])
```

Is it something possible? If it is, how can I archive that?

Thanks so much!

**Comment by gwenn** [comment]
See #1341

**Comment by lemunozm** [comment]
Great! Thanks.
I close this issue then
