### ISSUE TITLE
Adding Zipvfs supprot to rusqlite

### ISSUE THREAD

**Issue by adelg003** [rusqlite/rusqlite#1355]
Hello,
I do apologize if this has been answered before, but I was not able to find any details on this.

I am looking to add support for Zipvfs to rusqlite. Zipvfs is basically a proprietary compression / encryption library from SQLite that my employer has been using for years, and I am looking to add rust support for my team.
https://sqlite.org/zipvfs/doc/trunk/www/readme.wiki

SQLite has provided the source code to compile. It is basically a replacement file for `sqlite3.c` that adds the needed functionally on top of standard sqlite3. I have added the replacement file to `libsqlite3-sys` (aka overwritten `sqlite3.c`) and am able to run a `cargo build` with the new `sqlite3.c` file.

I am running into an issue where it looks like the updated `sqlite3.c` file needs to have `zlib` made available to the linker (or that is my current understanding at least).

Here is the error I am seeing when I trigger `cargo build`:
```
error: linking with `cc` failed: exit status: 1
  |
  = note: LC_ALL="C" PATH= "-lSystem" "-lc" "-lm" "-L" "{very long list of local folder/files}" "-Wl,-dead_strip" "-nodefaultlibs"
  = note: Undefined symbols for architecture x86_64:
            "_compress", referenced from:
                _zipvfs_sqlcmd_compress in liblibsqlite3_sys-73d8d2ff7720421c.rlib(sqlite3.o)
            "_compress2", referenced from:
                _zlibCompress in liblibsqlite3_sys-73d8d2ff7720421c.rlib(sqlite3.o)
            "_uncompress", referenced from:
                _zipvfs_sqlcmd_decompress in liblibsqlite3_sys-73d8d2ff7720421c.rlib(sqlite3.o)
                _zlibUncompress in liblibsqlite3_sys-73d8d2ff7720421c.rlib(sqlite3.o)
          ld: symbol(s) not found for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
          

error: could not compile `foobar` (bin "foobar") due to previous error
```

If I try to build this directly, I get (mostly) the same errors:
```
$ cc sqlite3.c                                                      
Undefined symbols for architecture x86_64:
  "_compress", referenced from:
      _zipvfs_sqlcmd_compress in sqlite3-6c3d98.o
  "_compress2", referenced from:
      _zlibCompress in sqlite3-6c3d98.o
  "_main", referenced from:
     implicit entry/start for main executable
  "_uncompress", referenced from:
      _zipvfs_sqlcmd_decompress in sqlite3-6c3d98.o
      _zlibUncompress in sqlite3-6c3d98.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

And if I add the `-lz` flag, it looks like the issue are (mostly) addressed.
```
$ cc -lz sqlite3.c
Undefined symbols for architecture x86_64:
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

This leads me to think that if I am able to enable the equivalent linker flags for `-lz` in `build.rs` I may be able to address my issue. It is my understand the `-lz` flag is for linking `zlib` at compile time.
https://zlib.net/

If there is more information needed, or if there is anything that I am doing is wrong, please feel free to let me know.

**Comment by thomcc** [comment]
You probably have to add `println!("cargo:rustc-link-lib=z")` or something. You could also try adding `libz-sys` to libsqlite3-sys's dependencies. Note that upstreaming these changes (in particular your change to the sqlite3.c file) probably violates your license agreement for zipvfs, so you'll have to carry a forked libsqlite3-sys.

The non-fork solution for you would be to separately compile zipvfs to a `libsqlite3.a` file, set SQLITE3_LIB_DIR and SQLITE3_INCLUDE_DIR in the environment to the appropriate values, and then pull `libz-sys` into their dependency graph by some means.

**Comment by adelg003** [comment]
Hello @thomcc,
Thank you for your feedback. You were correct that adding `println!("cargo:rustc-link-lib=z")` to `build.rs` fixes the issue. I also agree that using `libsqlite3.a` is better solution, so that will be next on my TODO list.

I will close this issue as my immediate ask is addressed. Thank you for your help.
