### ISSUE TITLE
Documentation example mismatch for Transaction.execute

### ISSUE THREAD

**Issue by Shanks512** [rusqlite/rusqlite#1363]
The documentation example for Transaction.execute uses Connection (instead of Transaction) and is misleading. I think the example must be changed to illustrate the use of Transaction.execute.

[Transaction.execute](https://docs.rs/rusqlite/latest/rusqlite/struct.Transaction.html#method.execute)

**Comment by gwenn** [comment]
Could you please collapse all the documentations on the linked page ?
Then you will see that all theses methods are [Methods from Deref<Target = Connection>](https://docs.rs/rusqlite/latest/rusqlite/struct.Transaction.html#deref-methods-Connection).

**Comment by gwenn** [comment]
Could you please this issue or comment ?

**Comment by Shanks512** [comment]
Oops, missed that. I'm relatively new to rust, so still wrapping my head around all the quirks in documentation. I will close the issue. Thanks for the clarification. And thank you for rusqlite!
