### ISSUE TITLE
Collecting `Map` requires depending on outdated version of `fallible_iterator`

### ISSUE THREAD

**Issue by albertsgarde** [rusqlite/rusqlite#1368]
If you depend on the newest version (`0.3.0`) og `fallible_iterator`, the compiler still complains, but depending on the old version `0.2.0` works.
This could probably be fixed by simply bumping the dependency, which I might make a PR that does, but I wanted to see if I was missing something first.

Is this correct, and if so is there a reason?

Making `fallible_iterator` dependency optional was discussed in #833.

**Comment by gwenn** [comment]
> the compiler complains

Could you please be more specific ?
Like the error message.
Or even better a mininal example in https://play.rust-lang.org/

**Comment by albertsgarde** [comment]
Right, of course. Actually, it turns out I can't replicate it, so I guess I must have been doing something wrong.
