### ISSUE TITLE
How to use the latest sqlite?

### ISSUE THREAD

**Issue by proofrock** [rusqlite/rusqlite#1376]
Hi,
  thanks for your work! Great library. I was wondering: it seems that version 0.29 comes with bundled SQLite 3.41.2, but in the code I see that it was already bumped to 3.42.0. How can I use that version? Is it necessary to wait for the next release? And, in general, is `main` stable enough to use or is it the latest devel "situation"?

Thank you, and have a good day,

    G.

**Comment by gwenn** [comment]
We can release a new version if you need.
Or you can (temporary) point to the git repository / specific revision.

**Comment by proofrock** [comment]
Oh thanks for your kindness! Don't mind doing a release, I am still in the early stages of my project, by the time it's in shape we'll have SQLite 3.1000.0 probably :-D

About pointing to GIT repo, I tried and I have some problems, but I'll file a separate issue. Thanks!
