### ISSUE TITLE
Unable to import `rusqlite::transaction::TransactionState`

### ISSUE THREAD

**Issue by yy0931** [rusqlite/rusqlite#1383]
I tried to pattern match the return value of the method `Connection::transaction_state`, but I couldn't reference `rusqlite::transaction::TransactionState` because `rusqlite::transaction` is private. Can it be made public?

```rust
match conn.transaction_state(None).unwrap() {
    rusqlite::transaction::TransactionState::None => unimplemented!(),
    //        ^^^^^^^^^^^ private module
    _ => unimplemented!(),
}
```

`TransactionState` is public,
https://github.com/rusqlite/rusqlite/blob/2f212074a55a5543ed21303c26164f2548825cfc/src/transaction.rs#L379-L386

but the file is private.
https://github.com/rusqlite/rusqlite/blob/2f212074a55a5543ed21303c26164f2548825cfc/src/lib.rs#L132

**Comment by gwenn** [comment]
Fixed with `rusqlite` version 0.30.0
