### ISSUE TITLE
subsecond modifier like unixepoch('now', 'subsec') does not work

### ISSUE THREAD

**Issue by kolbma** [rusqlite/rusqlite#1391]
What's up with the `'subsec'` modifier of SQLite?

This doesn't work
```rust
        let epoch = c
            .query_row("SELECT unixepoch('now','subsec');", [], |row| {
                let epoch: f64 = row.get_unwrap(0);
                Ok(epoch)
            })
            .unwrap();
```

thread 'db::tests::unixepoch_f64_test' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidColumnType(0, "unixepoch('now','subsec')", Null)', /home/makolb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rusqlite-0.29.0/src/row.rs:261:23

Or do I miss anything to get a result?

**Comment by kolbma** [comment]
It also doesn't work for
```SQL
strftime('%s','now','subsec')
```

```rust
        let epoch = c
            .query_row("SELECT strftime('%s','now','subsec');", [], |row| {
                let epoch: String = row.get_unwrap(0);
                Ok(epoch)
            })
            .unwrap();
```

thread 'db::tests::strftime_string_test' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidColumnType(0, "strftime('%s','now','subsec')", Null)', /home/makolb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rusqlite-0.29.0/src/row.rs:261:23


But with `julianday`-calculation you get a f64, so this works:
```rust
        let epoch = c
            .query_row(
                "SELECT (julianday('now') - 2440587.5)*86400.0;",
                [],
                |row| {
                    let epoch: f64 = row.get_unwrap(0);
                    Ok(epoch)
                },
            )
            .unwrap();
```

**Comment by kolbma** [comment]
Ah, I've seen this will work in master branch with updated sqlite version.

**Comment by dimo414** [comment]
Can this be left open until a new release is cut? I spent a good chunk of time trying to work out what I was doing wrong.
