### ISSUE TITLE
Custom window functions and mutability

### ISSUE THREAD

**Issue by nyurik** [rusqlite/rusqlite#1394]
I am working on [sqlite-hashes](https://github.com/nyurik/sqlite-hashes) -- adding hash functions like `md5` and `sha256` to SQLite.

In order to create `sha256_concat(val)` - a hash over a sequence, each value must be consistently ordered.  SQLite does NOT guarantee the order of execution for the regular aggregate functions even if they have an `ORDER BY` in the query, so the result in BOTH of these examples is NOT defined! 🤦 (see [group_concat ordering question](https://stackoverflow.com/questions/1897352/sqlite-group-concat-ordering)):

```sql
SELECT sha256_concat(val) FROM tbl ORDER BY val;
SELECT sha256_concat(val) FROM (SELECT val FROM tbl ORDER BY val));
```

I think I can get around it with a custom windowing function, but it has some limitations too:  the aggregation state cannot be "inversed" (once a value is added to the hash, it cannot be removed). It is also harder to "partially-compute" a value (compute an interim hash, and continuing to add values to it).

Should the `xValue` receive a mutable state, just like `xInverse`?  This way partial computations could be achieved somehow? Or do you have any other suggestions on implementing something like this?

Thanks!  See also my related question on [stackoverflow](https://stackoverflow.com/questions/77246426/ensuring-ordering-for-a-custom-aggregate-windowing-function-in-sqlite) (I focus on the actual SQL usage there).

**Comment by gwenn** [comment]
https://docs.rs/rusqlite/latest/rusqlite/functions/trait.WindowAggregate.html#tymethod.value ?

**Comment by nyurik** [comment]
@gwenn yes, those are the functions i meant when i said `xValue` and `xInverse`

**Comment by nyurik** [comment]
@gwenn, I just realized how I can test it, but it still seem to require `WindowAggregate::value` modification to pass `Option<&mut A>` instead of `Option<&A>`.  Would it be possible to make this change? (I tried to make a PR, but my unsafe Rust is a bit shaky).  To test:

```sql
CREATE TABLE tbl(a INTEGER PRIMARY KEY, b TEXT);
INSERT INTO tbl VALUES (1, 'bbb'), (2, 'ccc'), (3, 'aaa');

SELECT GROUP_CONCAT(b)
   OVER (ORDER BY b ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING)
FROM tbl LIMIT 1;
```

If I substitute `GROUP_CONCAT` with my own window function, i see these callbacks:

```
Aggregate::init
Aggregate::step: arg0=[97, 97, 97]
Aggregate::step: arg0=[98, 98, 98]
Aggregate::step: arg0=[99, 99, 99]
WindowAggregate::value
Aggregate::finalize
```

So in order to optimize the above, I must preserve the state between the `value()` and `finalize()`, and for that I would need to modify the value, since the mutable context seem to be shared between all calls to the aggregate function, not for the specific aggregation sequence.

**Comment by nyurik** [comment]
P.S. I wrote #1395 making the proposed change. I guess it is a bit confusing that value could get a None as an arg, but perhaps there are cases for that.  Also, it is weird that `value()` is the only callback that does not receive a context (I don't need it, but seems strange and inconsistent)
