### ISSUE TITLE
sqlite3_file_control

### ISSUE THREAD

**Issue by anacrolix** [rusqlite/rusqlite#1402]
How do I get at https://sqlite.org/capi3ref.html#sqlite3_file_control from rusqlite? Cheers

**Comment by gwenn** [comment]
https://docs.rs/libsqlite3-sys/latest/libsqlite3_sys/fn.sqlite3_file_control.html

**Comment by anacrolix** [comment]
Thanks, I found it by following through the ffi re-exported module.
