### ISSUE TITLE
Insert with returning clause seems to succeed, but subsequent query fails to find the record -> Data is lost

### ISSUE THREAD

**Issue by darklajid** [rusqlite/rusqlite#1403]
Coming from sqlx, but some investigation makes me believe this is a Sqlite API related issue?

My code is doing an

`Insert ... returning id` which returns a `Result<i64>` (where id is an auto incremented "custom rowid" field)

and then immediately afterwards runs a

`Select ... where id = ?` which returns a `Result<Option<T>>`

I do check all errors along the way. What I didn't do/how I found this problem? I looked at these two statements in sequence, looked at the Option I get from an Ok for the Select case and literally wrote in my code:

```rust
let id: i64 = sqlx::query!("Insert Into Foo .. Returning id")
  .fetch_one(db)
  .await
  .map(|row| row.id)?;

Ok(get_foo_by_id(ctx, id)
        .await?
        .expect("The previous insert should've failed otherwise")) // Ouch
```

(there are literally no deletes anywhere, so this isn't a race where something, somewhere, would delete a freshly inserted row)

Now my code panics and I learned a life lesson, but I don't see how that's possible. A few searches lead me to https://sqlite.org/forum/forumpost/a72bab3dea which seems to describe a very similar problem that turned out to be an issue in the C#/dotnet wrapper for Sqlite. The way I read it there's the potential to require multiple calls to the step function and accepting the first result as "okay that worked, we're good" is wrong. Now, I'm unfortunately VERY unfamiliar with this project's code base, but I wonder if something like the early return in https://github.com/rusqlite/rusqlite/blob/fd219b39aade7e7308f4e8f558294be16f8da698/src/raw_statement.rs#L110 could cause a similar problem here? Is this a potential problem or am I seeing ghosts here?

**Comment by gwenn** [comment]
Could you please provide a minimal complete example to reproduce your issue (for example on https://play.rust-lang.org/) ?
