### ISSUE TITLE
Support for SQLITE_IOCAP_IMMUTABLE

### ISSUE THREAD

**Issue by EvanCarroll** [rusqlite/rusqlite#1404]
A duplicate of the issue on the stainless-steel/sqlite board. I would like to open a SQL Lite database in read-only immutable mode to bypass the lock that stops me from reading it. I don't see this supported but it sounds very useful.

https://www.sqlite.org/c3ref/open.html
https://stackoverflow.com/a/69574421/124486

It seems there is a SQLITE_OPEN_READONLY flag supported but the IMMUTABLE flag is not supported. The Immutable flag is the one that ignores the lock.

-----

https://github.com/stainless-steel/sqlite/issues/78

**Comment by gwenn** [comment]
So you tried something like this:
```rust
        let url = "file:/path/to/db?mode=ro&immutable";
        let flags = OpenFlags::SQLITE_OPEN_READONLY | OpenFlags::SQLITE_OPEN_URI;
        let db = Connection::open_with_flags(url, flags)?;
        ...
```
But it didn't work, right ?
What is the error ?

**Comment by gwenn** [comment]
> The only thing I would prefer is not to have to put the flags in the URI

This limitation is not related to `rusqlite` API but to the underlying SQLite API...

**Comment by EvanCarroll** [comment]
Oh, well that's silly on their part. I wonder if there is a reason for it. Can I get your opinion on why this isn't an OpenFlag in the underlying API? Would I be right to feature request this?
