### ISSUE TITLE
release latest changes

### ISSUE THREAD

**Issue by lovasoa** [rusqlite/rusqlite#1412]
Hello and thanks for rusqlite !

 [SQLPage](https://sql.ophir.dev/) depends on the sqlite version packaged with rusqlite, and I'd like to release a new version with the latest sqlite version. I see sqlite has been updated in this repo, but the changes have not been released yet. Is there a release coming ?

**Comment by gwenn** [comment]
I will try to perform a release this week-end.

**Comment by lovasoa** [comment]
Great, thank you !

**Comment by gwenn** [comment]
`rusqlite` version 0.30.0 / `libsqlite3-sys` version 0.27.0 released.
