### ISSUE TITLE
test_from_handle fails to build on systems with unsigned c_char

### ISSUE THREAD

**Issue by plugwash** [rusqlite/rusqlite#1420]
Debian CI discovered that test_from_handle_owned fails to build on systems with unsigned c_char. The fix is trivial, the typecast just needs to be changed from *const i8 to *const c_char.

https://salsa.debian.org/rust-team/debcargo-conf/-/blob/529c3c84306436a723ea0f1595465fa61017b988/src/rusqlite/debian/patches/fix-tests-unsigned-char.patch

**Comment by gwenn** [comment]
https://github.com/rusqlite/rusqlite/blame/c2fbd167dec8b043524a11df8a471120008669dd/src/lib.rs#L1884

**Comment by gwenn** [comment]
Thanks.

**Comment by gwenn** [comment]
Version 0.31.0 released
