### ISSUE TITLE
release the latest version

### ISSUE THREAD

**Issue by lovasoa** [rusqlite/rusqlite#1442]
Hello !
  This is a new issue for https://github.com/rusqlite/rusqlite/issues/1412
  I see the latest SQLite (3.45.0) has been integrated, but a new version hasn't been released.
  I'd love to see it published to crates.io so that I can add it to [SQLPage](https://github.com/lovasoa/SQLpage).

**Comment by gwenn** [comment]
Could you please confirm that you only need `libsqlite3-sys` ?

**Comment by lovasoa** [comment]
I confirm ! 😊

**Comment by gwenn** [comment]
libsqlite3-sys v0.28.0 published

**Comment by lovasoa** [comment]
Thank you!
