### ISSUE TITLE
called `Result::unwrap()` on an `Err` value: SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some("json_object() requires an even number of arguments"))

### ISSUE THREAD

**Issue by ArunGust** [rusqlite/rusqlite#1448]
I tried execute SELECT json_group_array( json_object('PrevInTax41')) AS json_result FROM (SELECT PrevInTax41 FROM  and got below error. Any ide to solve the issue ? 

called `Result::unwrap()` on an `Err` value: SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some("json_object() requires an even number of arguments"))

**Comment by ArunGust** [comment]
issue solved. wrong statement

**Comment by gwenn** [comment]
Would you mind closing your issue ?
