### ISSUE TITLE
Question: Is there any way to use SQLite 3.45 with rusqlite 0.30.0?

### ISSUE THREAD

**Issue by jeremychone** [rusqlite/rusqlite#1450]
I assume that the upcoming rusqlite 0.31.x will use SQLite 3.45.x with the new jsonb support, which is awesome. 
I tested it from the git main branch, and everything works nicely (on Mac, at least).

However, in the meantime, is there a way to use SQLite 3.45 with rusqlite 0.30.0?

If not, it's not a big issue; we will wait for rusqlite 0.31, which might be better since we also need sea-query-rusqlite, which bundles it as well.

(SQLite jsonb  kind of takes the whole json support to a new level.)

**Comment by gwenn** [comment]
You should be able to use SQLITE3_LIB_DIR / SQLITE3_INCLUDE_DIR.

**Comment by jeremychone** [comment]
@gwenn Great, thank you. I might give it a try. I need to see how it will work with sea-query-rusqlite.

Any rough estimate on when rusqlite 0.31.0 with SQLite 3.45 will be released?
