### ISSUE TITLE
Trait for abstracting over `Connection`/`Transaction`?

### ISSUE THREAD

**Issue by WesleyAC** [rusqlite/rusqlite#1451]
I'll start this off by saying that I haven't thought a ton about this, so there could be reasons this doesn't exist. However, I have many helper functions that take a `&Connection`, but I then want to use them in a transactional manner. As far as I can tell, the only way to do this is to make a copy of the function that takes a transaction (and if I want, to rewrite the `&Connection` version in terms of the transaction one). This feels unsatisfying to me, and it seems like it should be possible write a trait that encompasses the set of things that can be done with either a transaction or a connection, and then I could write a function taking a boxed instance of that trait.

Is this something that's been considered?

**Comment by gwenn** [comment]
Maybe Rust can use the fact that `Transaction` [impl Deref](https://docs.rs/rusqlite/latest/rusqlite/struct.Transaction.html#impl-Deref-for-Transaction%3C'_%3E)

**Comment by gwenn** [comment]
Would you mind closing this issue ?

**Comment by WesleyAC** [comment]
Ah, that makes sense, thanks!
