### ISSUE TITLE
Release 0.31.0 with SQLite 3.45?

### ISSUE THREAD

**Issue by jeremychone** [rusqlite/rusqlite#1453]
Following up on the [discord conversation](https://discord.com/channels/927966344266256434/927967608286892072/1207497864717140008) I think it would be great to release version 0.31.0 of rusqlite with SQLite 3.45.x, as it adds JSONB support.

I did some quick tests with some of the JSONB functions, and everything seems to work pretty well.

**Comment by gwenn** [comment]
Version 0.31.0 released

**Comment by jeremychone** [comment]
@gwenn Perfect, thank you so much. I conducted some tests on my end with `jsonb`, and it works nicely.

> Note: This is very minor. The SQLite version is `3.45.0`, not `3.45.1`, but I assume this will be automatically updated when/if we get `libsqlite3-sys 0.28.1`. This is not critical at this point.

This is great, thank you !
