### ISSUE TITLE
How to get "returning *" from insert

### ISSUE THREAD

**Issue by tivrfoa** [rusqlite/rusqlite#1460]
Hi!

In sqlite we can use `returning *` or `returning some_field` in an `insert` to get the contents that were inserted.

How can we retrieve these values using rusqlite, please?

**Comment by gwenn** [comment]
https://github.com/search?q=repo%3Arusqlite%2Frusqlite%20returning&type=code
https://github.com/rusqlite/rusqlite/blob/322073a70d9ce3ab7a86088c2af0ee42e09adffd/src/lib.rs#L2143
https://github.com/rusqlite/rusqlite/blob/322073a70d9ce3ab7a86088c2af0ee42e09adffd/src/row.rs#L600

**Comment by tivrfoa** [comment]
Hi!

Thanks for replying! It's not clear how to use that.
I'll try later.

**Comment by Inspirateur** [comment]
Trying the first method gives:
> no method named `one_column` found for reference `&rusqlite::Connection` in the current scope
method not found in `&Connection`

it seems "one_column" is private to the crate ?
