### ISSUE TITLE
Add bindings for `sqlite3_trace_v2` API

### ISSUE THREAD

**Issue by WesleyAC** [rusqlite/rusqlite#1484]
The `trace` feature flag currently enables the [deprecated tracing functions](https://sqlite.org/c3ref/profile.html). It should provide access to the [new `sqlite3_trace_v2` API](https://sqlite.org/c3ref/trace_v2.html) as well.

**Comment by gwenn** [comment]
https://github.com/rusqlite/rusqlite/blob/b41bd805710149ebfaed577dfedb464338e2ca97/src/trace.rs#L120
And the old functions seem not really deprecated at least on this page:
http://sqlite.org/c3ref/funclist.html
> functions whose names are struck through are deprecated.

**Comment by WesleyAC** [comment]
Interesting point, [reported on the SQLite forum](https://sqlite.org/forum/forumpost/0901025836). Either way, I'd like access to the v2 API, since it structures the data in a way that's nicer for generating spans to integrate into my tracing system, which is what I want to do.

Should this issue be merged into #977, or kept separate?

**Comment by gwenn** [comment]
You can keep it separate.

**Comment by gwenn** [comment]
Version 0.33.0 released
