### ISSUE TITLE
the first query is failure due to below error

### ISSUE THREAD

**Issue by zeng-xingdong** [rusqlite/rusqlite#1499]
`
thread 'tokio-runtime-worker' panicked at C:\Program Files\Rust\Cargo\registry\src\index.crates.io-6f17d22bba15001f\rusqlite-0.31.0\src\lib.rs:779:17:
already borrowed: BorrowMutError
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at C:\Program Files\Rust\Cargo\registry\src\index.crates.io-6f17d22bba15001f\rusqlite-0.31.0\src\lib.rs:779:17:
already borrowed: BorrowMutError
thread 'tokio-runtime-worker' panicked at C:\Program Files\Rust\Cargo\registry\src\index.crates.io-6f17d22bba15001f\rusqlite-0.31.0\src\lib.rs:779:17:
already borrowed: BorrowMutError
thread 'tokio-runtime-worker' panicked at C:\Program Files\Rust\Cargo\registry\src\index.crates.io-6f17d22bba15001f\rusqlite-0.31.0\src\lib.rs:779:17:
already borrowed: BorrowMutError
`

**Comment by gwenn** [comment]
https://github.com/rusqlite/rusqlite/blob/6d9f01c06ee10a7fc6f2d2114fa8b91939606c03/src/lib.rs#L779
+
https://doc.rust-lang.org/std/cell/struct.RefCell.html#method.borrow_mut
