### ISSUE TITLE
New release with sqlite 3.46 

### ISSUE THREAD

**Issue by lovasoa** [rusqlite/rusqlite#1513]
Hi !
  I see SQLite 3.46 was merged in this repo, but it hasn't been published on crates.io. Would it be possible to publish a new version ?
  [SQLPage](https://sql.ophir.dev/) indirectly depends on rusqlite and [I got a report about the outdated SQLite](https://github.com/lovasoa/SQLpage/discussions/434)...

**Comment by gwenn** [comment]
I should be able to perform a release this week-end.
But please, next time, give useful information instead of noise.
Because I can only [guess](https://github.com/lovasoa/SQLpage/blob/main/Cargo.toml#L21) that you need only `libsqlite3-sys` (used by `sqlx`) and not `rusqlite`...

**Comment by lovasoa** [comment]
Sorry, I'll explicitly mention `libsqlite3-sys` for the next update.

Thanks for the update !

**Comment by lovasoa** [comment]
Maybe we could have a separate repo for `libsqlite3-sys`, or a github issue template with a specific tag ? It would make it  easier to report issues with the library that are not related to rusqlite.

**Comment by gwenn** [comment]
libsqlite3-sys v0.29.0 released

**Comment by lovasoa** [comment]
thank you !
