### ISSUE TITLE
failed to run custom build command for `libsqlite3-sys v0.27.0`

### ISSUE THREAD

**Issue by 3Q-** [rusqlite/rusqlite#1527]
Sorry to bother everyone, I want to use the encryption function of sqlite, but I reported this error. I have been searching for information for two days and I really can't seek help from everyone.
`cargo run`   The error log is as follows
```
error: failed to run custom build command for `libsqlite3-sys v0.27.0`

Caused by:
  process didn't exit successfully: `D:\rust\ddd\src-tauri\target\debug\build\libsqlite3-sys-8d3b25df47f4e817\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=LIBSQLITE3_SYS_USE_PKG_CONFIG
  cargo:rerun-if-changed=sqlcipher/sqlite3.c
  cargo:rerun-if-changed=sqlite3/wasm32-wasi-vfs.c

  --- stderr
  thread 'main' panicked at C:\Users\Administrator\.cargo\registry\src\index.crates.io-6f17d22bba15001f\libsqlite3-sys-0.27.0\build.rs:163:29:
  Missing environment variable OPENSSL_DIR or OPENSSL_DIR is not set
  stack backtrace:
  ```
  
Cargo.toml 
  
 ```
[dependencies]
rusqlite = { version = "0.30.0", features = ["winsqlite3", "bundled-sqlcipher"] }
libsqlite3-sys = { version = "0.27.0" }

```
openssl env 
<img width="559" alt="image" src="https://github.com/rusqlite/rusqlite/assets/3362625/332fd6e4-606f-46b7-9e06-0456f86505bd">

**Comment by gwenn** [comment]
I am not sure but:
```toml
rusqlite = { version = "0.30.0", features = ["winsqlite3", "bundled-sqlcipher"] }
libsqlite3-sys = { version = "0.27.0" }
```
seems wrong (incompatible features).
Could you please try by removing:
```toml
libsqlite3-sys = { version = "0.27.0" }
```
?

And
```
Missing environment variable OPENSSL_DIR or OPENSSL_DIR is not set
```
...

**Comment by 3Q-** [comment]
@gwenn   Thanks
I tried deleting it not  work.
`libsqlite3-sys = { version = "0.27.0" }`
Just now I reinstalled Visual Studio， deleted the space path an  remove dependencies
`libsqlite3-sys = { version = "0.27.0" }`
Now it can be successfully compiled。
