### ISSUE TITLE
The use of `VsVers::Vs12` in build.rs is deprecated

### ISSUE THREAD

**Issue by bigfoodK** [rusqlite/rusqlite#1528]
After [cc-rs v1.0.106](https://github.com/rust-lang/cc-rs/releases/tag/cc-v1.0.106)
https://github.com/rust-lang/cc-rs/blob/ba08d63ae08553d955d0d372982c04679b9ecdb1/src/windows/find_tools.rs#L154-L168

`VsVers::Vs12` used at here
https://github.com/rusqlite/rusqlite/blob/eebbbb008633b36f2580b29501800fb8bc37e36a/libsqlite3-sys/build.rs#L248-L251

It causes
```text
error: use of deprecated unit variant `cc::windows_registry::VsVers::Vs12`: Visual Studio 12 is no longer supported. cc will never return this value.
   --> /home/runner/work/namseent/namseent/namui/third-party-forks/rusqlite/libsqlite3-sys/build.rs:238:43
    |
238 |                 Ok(ver) => ver != VsVers::Vs12,
    |                                           ^^^^
    |
    = note: `-D deprecated` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(deprecated)]`
```

**Comment by bigfoodK** [comment]
Will there be a problem if we change it as follows?

```rust
use cc::windows_registry::find_vs_version;
let vs_has_nan = find_vs_version().is_ok();
if vs_has_nan {
    cfg.flag("-DHAVE_ISNAN");
}
```

**Comment by gwenn** [comment]
Maybe we should simply assume that `isnan()` function is available by default like here:
https://github.com/xerial/sqlite-jdbc/blob/14e07d4cf8667e5c40785b15470313b41968615d/Makefile#L82
