### ISSUE TITLE
Question About `vtab` Implementations

### ISSUE THREAD

**Issue by t-kalinowski** [rusqlite/rusqlite#1533]
Hello,

I'm implementing a `vtab` extension and am reviewing other implementations for examples. I have a question about the cursor initialization in `csvtab`.

In `csvtab`, the cursor is initialized as [follows](https://github.com/rusqlite/rusqlite/blob/eebbbb008633b36f2580b29501800fb8bc37e36a/src/vtab/csvtab.rs#L268):

```rust
CsvTabCursor {
    base: ffi::sqlite3_vtab_cursor::default(),
    ...
}
```

It looks like `CsvTabCursor.base` is initialized with zeros (`Default` is implemented using `unsafe { mem::zeroes() }`). However, the [SQLite documentation](https://www.sqlite.org/c3ref/vtab_cursor.html) indicates that the first field of the struct, `base.pVtab`, should be a pointer to the vtable for the cursor. There is also a Rust [method that accesses this pointer](https://github.com/rusqlite/rusqlite/blob/eebbbb008633b36f2580b29501800fb8bc37e36a/src/vtab/csvtab.rs#L278-L280):

```rust
/// Accessor to the associated virtual table.
fn vtab(&self) -> &CsvTab {
    unsafe { &*(self.base.pVtab as *const CsvTab) }
}
```

My question is: Should `CsvTabCursor::new()` be setting `self.base.pVtab`? If not, where is it being set? I also don't see it being set in [`rust_open()`](https://github.com/rusqlite/rusqlite/blob/eebbbb008633b36f2580b29501800fb8bc37e36a/src/vtab/mod.rs#L1083-L1108).

Thank you for your help!

**Comment by gwenn** [comment]
Not related to `rusqlite`...
See official CSV extension:
https://github.com/sqlite/sqlite/blob/1ffd7ed54ff340039fbc0e809a784789048bdf8c/ext/misc/csv.c#L322
https://github.com/sqlite/sqlite/blob/1ffd7ed54ff340039fbc0e809a784789048bdf8c/ext/misc/csv.c#L708 (base is not set)
And SQLite core:
https://github.com/sqlite/sqlite/blob/1ffd7ed54ff340039fbc0e809a784789048bdf8c/src/vdbe.c#L8192-L8197

**Comment by t-kalinowski** [comment]
Thank you!
