### ISSUE TITLE
Example crate with loadable extension?

### ISSUE THREAD

**Issue by t-kalinowski** [rusqlite/rusqlite#1534]
I'm a little confused about how to setup a crate that will provide a loadable sqlite extension.
 
Do you know of a minimal example repo I can reference that provides a vtab implementation? Or would you be able to describe what glue code + `Cargo.toml` would be needed to make [`csvtab`](https://github.com/rusqlite/rusqlite/blob/master/src/vtab/csvtab.rs) build correctly in a stand-alone repo?

**Comment by gwenn** [comment]
You may find some example repos with this query:
https://github.com/search?q=lang%3Atoml+loadable_extension+NOT+is%3Afork&type=code

**Comment by Norlock** [comment]
https://github.com/Norlock/sqlite-fuzzy-ext Maybe this helps, its quite minimal
