### ISSUE TITLE
Add implementation of `Type: FromSql`

### ISSUE THREAD

**Issue by wucke13** [rusqlite/rusqlite#1535]
I'd like to extract type information at run-time from the database, something like this:

```rust
let mut db_columns = Vec::new();

conn.pragma(None, "table_info", "elements", |row| {
    let idx: usize = row.get_unwrap(0);
    let name: String = row.get_unwrap(1);
    let r#type: rusqlite::types::Type = row.get_unwrap(2);

    assert_eq!(idx, db_columns.len());

    db_columns.push((name, r#type));
    Ok(())
})?;
```

**Comment by gwenn** [comment]
You already can directly with a simple `SELECT * FROM elements;`
See
https://docs.rs/rusqlite/latest/rusqlite/struct.Statement.html#method.column_count
https://docs.rs/rusqlite/latest/rusqlite/struct.Column.html#method.decl_type
Or, if there are data in your table:
https://docs.rs/rusqlite/latest/rusqlite/struct.Row.html#method.get_ref
+
https://docs.rs/rusqlite/latest/rusqlite/types/enum.ValueRef.html

And in case you don't know
SQLite uses dynamic typing by default:
See https://sqlite.org/datatype3.html

**Comment by wucke13** [comment]
@gwenn Thank you for the elaborate response! It still feels a bit weird to make a select to a DB while being interested in none of the rows, or to prepare a statement that never gets executed just to know the types of the columns, but I suppose technically that works.
