### ISSUE TITLE
expected `&str`, found `String` on build libsqlite3-sys-0.30.0\build.rs:267:22

### ISSUE THREAD

**Issue by nerasse** [rusqlite/rusqlite#1543]
I did my package update today with the new version and I got this error on build :

```
error[E0308]: mismatched types
   --> C:\Users\neras\.cargo\registry\src\index.crates.io-6f17d22bba15001f\libsqlite3-sys-0.30.0\build.rs:267:22
    |
267 |             cfg.flag(format!("-DSQLITE_MAX_VARIABLE_NUMBER={limit}"));
    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `&str`, found `String`
    |
    = note: this error originates in the macro `format` (in Nightly builds, run with -Z macro-backtrace for more info)
```

can you help me on this one ?
![image](https://github.com/user-attachments/assets/d880ecb9-bab3-4f32-ad83-66c8e6806fd5)
![image](https://github.com/user-attachments/assets/b4752981-a4c2-4f01-aedd-53782d175fa8)

**Comment by nerasse** [comment]
Compiled after I added ".as_str()" on formats like so :
![image](https://github.com/user-attachments/assets/e2724a6c-80d2-4f66-ac81-6c8494c71694)
but how to fix it properly ?

**Comment by gwenn** [comment]
Old `cc` version ?

**Comment by nerasse** [comment]
> > Old `cc` version ?
> 
> stable-x86_64-pc-windows-msvc unchanged - rustc 1.79.0 (129f3b996 2024-06-10) I did clear all my cache and sources with : cargo-cache --remove-dir git-repos,registry-sources

i did a "cargo add cc" and then removed it from my project and now without modification. it's working. Idk why 
thanks for your help

**Comment by trevyn** [comment]
Got hit by this as well. Is this a `cc` 1.1 thing?

**Comment by gwenn** [comment]
Version 0.32.1 of rusqlite / 0.30.1 of libsqlite3-sys released.
