### ISSUE TITLE
Optional does not catch SqliteError(StatementChangedRows(0))

### ISSUE THREAD

**Issue by MeAmAnUsername** [rusqlite/rusqlite#1560]
As the title says.
Summary of what I did: I ran `conn.prepare("INSERT ... ON CONFLICT DO NOTHING").insert(...).optional()` where the insert has a conflict and returns nothing
Expected: `Ok(None)`
Actual: `Err(SqliteError(StatementChangedRows(0)))`

Preferred resolution: either catch this in optional and return `None`, or document that this will only work for `stmt.query` and not `stmt.insert` (at least, that's what I think is happening here). I can implement either and make a PR if I know that that solution will be accepted.

```sql
CREATE TABLE IF NOT EXISTS tag (
    id              INTEGER     NOT NULL PRIMARY KEY AUTOINCREMENT,
    tag             TEXT        NOT NULL UNIQUE
) STRICT;
```

```rust
let mut stmt = conn.prepare("INSERT INTO tag (tag) VALUES (?1) ON CONFLICT (tag) DO NOTHING")?;
for tag in tags {
    match dbg!(stmt.insert([tag]).optional())? {
    // snip
    }
}
```

Note 1: I don't think [this reply](https://github.com/rusqlite/rusqlite/issues/777#issuecomment-650910410) applies here, because in this case the query really did "return"/affect 0 rows.

Note 2: This was a workaround for the same issue as https://github.com/rusqlite/rusqlite/discussions/1349. That solution works for me too, so I won't be using my code here. I'm still opening this issue because I think the behavior of `optional` is surprising.

**Comment by gwenn** [comment]
`optional` is meant to be used with `query_row` not `insert`.
Because `insert` never returns any row.
