### ISSUE TITLE
"Foreign key constraint failed" when using "INSERT OR ..." concurrently

### ISSUE THREAD

**Issue by ssokolow** [rusqlite/rusqlite#1564]
I've run into a bug that may be in SQLite or may be in how rusqlite is using it. Specifically, I'm getting foreign key constraint failures out of `INSERT OR IGNORE` and other `INSERT OR ...` constructs which go away if I remove a completely unrelated column. (No constraints on it, not used by any relationships.)

I've tried to put together a minimal reproducer, but I've walked pretty far down the curve of diminishing returns, so here's one that still has stuff that's probably superfluous, like using Clap as the CLI argument parser.

https://github.com/ssokolow/rusqlite_1564_reproducer

See `check.sh` for more on the dynamics of triggering the bug as implemented.

I'm willing to help further as long as it doesn't take an inordinate amount of effort but I can't guarantee any specific amount of time investment, given the demands on my time, and that I've learned I can work around the problem by more or less reinventing `INSERT OR IGNORE` using an extra `SELECT` and a Rust-side `if` inside the same transaction.

**Comment by trevyn** [comment]
You’ve seen this, right?

>If a separate thread performs a new [INSERT](https://www.sqlite.org/lang_insert.html) on the same database connection while the [sqlite3_last_insert_rowid()](https://www.sqlite.org/c3ref/last_insert_rowid.html) function is running and thus changes the last insert [rowid](https://www.sqlite.org/lang_createtable.html#rowid), then the value returned by [sqlite3_last_insert_rowid()](https://www.sqlite.org/c3ref/last_insert_rowid.html) is unpredictable and might not equal either the old or the new last insert [rowid](https://www.sqlite.org/lang_createtable.html#rowid).

(https://www.sqlite.org/c3ref/last_insert_rowid.html)

Maybe your db connection serialization lock might not be held after you have the transaction handle?

**Comment by gwenn** [comment]
https://sqlite.org/lang_conflict.html
> For the INSERT and UPDATE commands, the keywords "ON CONFLICT" are replaced by "OR" so that the syntax reads more naturally. For example, instead of "INSERT ON CONFLICT IGNORE" we have "INSERT OR IGNORE". The keywords change but the meaning of the clause is the same either way.
> The ON CONFLICT clause applies to [UNIQUE](https://sqlite.org/lang_createtable.html#uniqueconst), [NOT NULL](https://sqlite.org/lang_createtable.html#notnullconst), [CHECK](https://sqlite.org/lang_createtable.html#ckconst), and [PRIMARY KEY](https://sqlite.org/lang_createtable.html#primkeyconst) constraints. The ON CONFLICT algorithm **does not apply to** [FOREIGN KEY constraints](https://sqlite.org/foreignkeys.html).

**Comment by ssokolow** [comment]
> Maybe your db connection serialization lock might not be held after you have the transaction handle?

That entire part is inside a single "take the lock, then start a transaction" block.

The architecture of the reproducer (itself a representative simplification of the code where I noticed the bug) is:

1. Take the Mutex, perform a `SELECT` to check if the sha256sum for the file is already in the database, and release the mutex. Return early if the file's already been catalogued.
2. With the mutex released so other thread can use it, load the file with the `image` crate and compute hashes of the raw pixel data.
3. Take the mutex, begin a transaction, and then do all updates to the database within that single transaction, within that single holding of the lock.

> For the INSERT and UPDATE commands, the keywords "ON CONFLICT" are replaced by "OR" so that the syntax reads more naturally. For example, instead of "INSERT ON CONFLICT IGNORE" we have "INSERT OR IGNORE". The keywords change but the meaning of the clause is the same either way.
The ON CONFLICT clause applies to [UNIQUE](https://sqlite.org/lang_createtable.html#uniqueconst), [NOT NULL](https://sqlite.org/lang_createtable.html#notnullconst), [CHECK](https://sqlite.org/lang_createtable.html#ckconst), and [PRIMARY KEY](https://sqlite.org/lang_createtable.html#primkeyconst) constraints. The ON CONFLICT algorithm does not apply to [FOREIGN KEY constraints](https://sqlite.org/foreignkeys.html).

Possible... except that, last time I tried to delete the `md5sum` column from the reproducer, it started working, and the `md5sum` column has *never* been part of any foreign key relationship. It's just there for cross-referencing other systems like \*booru sites. All foreign key relationships are done either through SHA256 or integer primary keys.

Give me a sec and I'll see what a few other ideas for minifying the reproducer do, which didn't occur to me at the time.

**Comment by ssokolow** [comment]
Ugh. Now the md5sum column can be removed without suddenly causing things to start working.

I hate these sorts of complex interactions. It took me three tries to minimize it and I now seem to have *again* accidentally minimized away the part I was trying to keep.

**Comment by ssokolow** [comment]
Never mind. I've been trying to pin this down for a week now, I know how to reliably work around it for my own uses, and I'm burned out.
