### ISSUE TITLE
Identify on Connection::open if a new database was created

### ISSUE THREAD

**Issue by bralax** [rusqlite/rusqlite#1567]
By default, the `Connection::open` functions will attempt to open a connection to the db file and if it does not exist create the file for you.

The one issue I am running into is that if it makes a new database, then you need to Create all the tables for the database which you don't have to do (and probably shouldn't attempt).

Is there any way to identify if the database is a new vs existing database without querying the db using the generated connection once to check the state of the DB?

**Comment by gwenn** [comment]
You can remove this flag [SQLITE_OPEN_CREATE](https://docs.rs/rusqlite/latest/rusqlite/struct.OpenFlags.html#associatedconstant.SQLITE_OPEN_CREATE) and handle the error.
