### ISSUE TITLE
Consider disabling double-quoted strings

### ISSUE THREAD

**Issue by ijackson** [rusqlite/rusqlite#1572]
See https://sqlite.org/quirks.html#double_quoted_string_literals_are_accepted

AFAICT this dbconfig option isn't exposed by rusqlite.  It would be nice to expose it, and then we shoudl consider changing the default (in the next breaking release, presumalby).

**Comment by gwenn** [comment]
> AFAICT this dbconfig option isn't exposed by rusqlite.

https://docs.rs/rusqlite/latest/rusqlite/?search=dqs
