### ISSUE TITLE
Error being ignored and silently dropped with `raw_query()`

### ISSUE THREAD

**Issue by sebadob** [rusqlite/rusqlite#1580]
I am not sure if I missed something, but it seems that `raw_query()` ignores all database errors by definition.

I need to use the `raw` API bindings because I am in a special situation while building [Hiqlite](https://github.com/sebadob/hiqlite), where I built a Raft cluster on top of `rusqlite` and therefore need to be able to serialize Params and send them over the wire in certain situations, to get the best possible DX and native `rusqlite` error messages.

As mentioned already I am using the `raw` API and most things work fine so far (only found one other problem which I will open another issue for). I am now in the situation where I found out, that `raw_query()` just returns `Rows`, but not wrapped inside a `Result<_>` like all other functions. Because of this, I now got stuck at a point where a `unique constraint violation` from an index is not forwarded, but actually silently dropped and I have no chance of ever seeing this error. I just get empty `Rows` back, the error is impossible to get.

The only situation where I have to use the `raw_query()` is with `RETURNING`, because all other queries can run local.

A short and simplified example of when this issue occurs:

```rust
// way above I have `q` defined, which basically is a wrapper to serialize my sql + params

let mut stmt = conn.prepare_cached(q.sql.as_ref()).unwrap();

let mut idx = 1;
for param in q.params {
    stmt.raw_bind_parameter(idx, param.into_sql()).unwrap();
    idx += 1;
}

// here I only get `Rows`, but no `Result` in case of any error like unique constraint
let mut rows = stmt.raw_query();
```

When I construct a query that violates a unique constraint for instance and execute it manually, it fails (of course), but when I execute the exact same query using the described method, I only get empty `Rows` and have no idea what happened and why.

So now my question is:

Am I missing something or is there another way of getting the query actually to fail in case an error, or is this just "missing"?

**Comment by gwenn** [comment]
Because `Rows` is a lazy iterator (a faillible streaming iterator).

**Comment by sebadob** [comment]
Oh yeah, sorry.

I was consuming it with `row.next()` of course, but used an `if let Ok(...)`. What a bad mistake. ^^
Thanks for the quick answer and sorry for annoying you, should have seen that myself.
