### ISSUE TITLE
`Batch` iterator gets stuck on syntax error

### ISSUE THREAD

**Issue by sebadob** [rusqlite/rusqlite#1581]
While building [Hiqlite](https://github.com/sebadob/hiqlite) I stumbled about an issue with the `Batch` iterator / stream.

When I consume some sql `String` using `Batch::new()` and then iterate over the data, I end up in an endless loop if one of the statements has a syntax error. The iterator kind of "gets stuck" and with each follwing `.next()`, it will return the same syntax error over and over again until end of time, or actually until the process is OOM killed.

My solution for now is to simply `panic!` on any syntax errors, which is bad but at least way better than consuming all memory and getting killed later. The `panic` is on purpose to spot errors early.

A short example:

```rust
let mut batch = Batch::new(&conn, req.sql.as_ref());
// we can at least assume 2 statements in a batch execute
let mut res = Vec::with_capacity(2);

loop {
    match batch.next() {
        Ok(Some(mut stmt)) => {
            res.push(stmt.execute([]).map_err(Error::from));
        }
        Ok(None) => break,
        Err(err) => {
            // TODO if there is a syntax error in the batch stmt, this will loop forever
            // -> Err(_) will NOT remove the bad element from the Batch
            panic!("{}", err);
            // res.push(Err(Error::from(err)));
        }
    }
}
```

I would expect the stream / iterator to remove an item on error, or is this simply not possible because of the way it's built internally, and I would need to exit, return an error early and drop all following statements? If so, an update to the docs would be very helpful mentioning, that the iterator can never finish, if there is any error.

**Comment by gwenn** [comment]
Sorry, `Batch` should not implement `Iterator`, only `FallibleIterator`.
Because, there is no way to recover from a parsing error.
See https://github.com/sqlite/sqlite/blob/bcdb28b8f9e525429557c08ed0a03450d0fd8c57/src/parse.y#L65-L69

**Comment by sebadob** [comment]
Okay, so the solution in case of an error is to `break` the loop and return early.

Thanks!

**Comment by gwenn** [comment]
https://docs.rs/fallible-iterator/latest/fallible_iterator/
> or it may run forever if the error is returned repeatedly

**Comment by sebadob** [comment]
> or it may run forever if the error is returned repeatedly

Yes that's exactly what was happening to me, until it consumed all 64GB of memory and Linux said "okay, until here and no further" :D

**Comment by gwenn** [comment]
I will try to fix it.
But the only thing I can do is remove the `Iterator` impl and add some doc.

**Comment by sebadob** [comment]
> But the only thing I can do is remove the Iterator impl and add some doc.

That would be enough for me. When you know that it can't recover from an error and skip it, you just need to know about it. Exiting early in that case is no big deal.
