### ISSUE TITLE
Rows is not an iterator

### ISSUE THREAD

**Issue by montjoie** [rusqlite/rusqlite#1600]
Hello

I did basicly what I found on example and it do not compile

let mut stmt = conn.prepare("SELECT * FROM table");
let mut stmt = stmt.unwrap();
let mut r = stmt.query(());
for row in r {}

And I got:
error[E0277]: `Rows<'_>` is not an iterator
  --> src/main.rs:87:32
   |
87 |                     for row in r {
   |                                ^ `Rows<'_>` is not an iterator

Any help will be appreciated.

I have also tried:
let mut r = stmt.query_map([], |row|
                        {
                        Ok(row.get(0)?)
                        }
               );
And I got:
error[E0277]: the trait bound `(): FromSql` is not satisfied
   --> src/main.rs:82:32
    |
82  |                         Ok(row.get(0)?)
    |                                ^^^ the trait `FromSql` is not implemented for `()`

I am stuck, thanks in advance

**Comment by montjoie** [comment]
It dont answer my question, but I found other way to do it thanks.

**Comment by gwenn** [comment]
You mean that:
> This interface is not compatible with Rust’s Iterator trait

doesn't answer:
> error[E0277]: Rows<'_> is not an iterator
