### ISSUE TITLE
Add JSONB support for `libsqlite3-sys`?

### ISSUE THREAD

**Issue by xuehaonan27** [rusqlite/rusqlite#1614]
I am currently working on adding SQLite `jsonb` support for `diesel`. It appears that `libsqlite3-sys` version 0.30.1 does not yet support JSONB functions. I tested rusqlite version 0.32.1, and it works well. However, using it introduces an additional dependency that feels somewhat redundant. Will `libsqlite3-sys` include JSONB-related support in its next release?

More information: https://github.com/diesel-rs/diesel/pull/4388

**Comment by gwenn** [comment]
As far as I know, [JSONB](https://sqlite.org/jsonb.html) is available with SQLite >= 3.45.0 !
So I guess, you linked `libsqlite3-sys` with an older version !
Maybe the [bundled](https://github.com/rusqlite/rusqlite/blob/master/libsqlite3-sys/Cargo.toml#L16) feature is missing ?

**Comment by xuehaonan27** [comment]
Problem solved by changing `bundled-bindings` to `bundled`. You are right. Thanks very much.
