### ISSUE TITLE
Multiple readonly/immutable connections to database share page cache lock?

### ISSUE THREAD

**Issue by devnev** [rusqlite/rusqlite#1618]
I'm writing a data transform job, reading from a bunch of sqlite databases to output another database. After writing the whole thing as a single-threaded job, I rewrote it to allow any number of reader worker threads that output to a channel that is consumed by the writer worker thread.

However, this significantly reduced the performance of the program. I looked at it with a profiler, and most of the time is spent in the readers, on futex syscalls called from the sqlite page cache.

This the flamegraph from perf (run with `perf record -a -g -F 997  <cmd>`):

![flamegraph-2](https://github.com/user-attachments/assets/db5cb238-a612-4332-805c-bfd247ce6043)

If I'm interpreting this correctly, it looks like all the treads connections are using a shared lock on the page cache. However, I've applied all the options I can think of to try and avoid this - immutable, readonly, private cache. The connection code run by each reader thread looks like this:

```rust
    let connection = Connection::open_in_memory_with_flags(
        OpenFlags::SQLITE_OPEN_READ_ONLY
            | OpenFlags::SQLITE_OPEN_NO_MUTEX
            | OpenFlags::SQLITE_OPEN_URI
            | OpenFlags::SQLITE_OPEN_PRIVATE_CACHE,
    )?;
    for db in ["table1", "table1", "table3"] {
        connection.execute_batch(&format!(
            "ATTACH 'file:{}.sqlite3?immutable=1&mode=ro&nolock=1&cache=private' AS {}_db;",
            dir.join(db).to_str().unwrap(),
            db,
        ))?;

        connection.execute_batch(&format!(
            "
            PRAGMA {0}_db.query_only = true;
            PRAGMA {0}_db.synchronous = OFF;
            PRAGMA {0}_db.journal_mode = OFF;
            PRAGMA {0}_db.cache_size = -100000;
            PRAGMA {0}_db.locking_mode = EXCLUSIVE;
            ",
            db,
        ))?;
    }
```

**Comment by gwenn** [comment]
`SQLITE_OPEN_NO_MUTEX` is already applied by default: https://github.com/rusqlite/rusqlite/blob/92fdc11fea0ecea6400dfcb74c1c3ca36214a7d4/src/lib.rs#L1238
`SQLITE_OPEN_PRIVATE_CACHE` is activated by default: https://sqlite.org/c3ref/enable_shared_cache.html.
And `locking_mode = EXCLUSIVE` seems bad to me for read-only.

**Comment by devnev** [comment]
> `SQLITE_OPEN_NO_MUTEX` is already applied by default:
> 
> https://github.com/rusqlite/rusqlite/blob/92fdc11fea0ecea6400dfcb74c1c3ca36214a7d4/src/lib.rs#L1238

From what I understand of that code, because I'm passing my own set of flags, the default doesn't get applied.
 
> `SQLITE_OPEN_PRIVATE_CACHE` is activated by default: https://sqlite.org/c3ref/enable_shared_cache.html.

In that case it shouldn't make a difference, and doesn't hurt to set the bit just in case.

> And `locking_mode = EXCLUSIVE` seems bad to me for read-only.

I'll give it another go without this just to be sure. I tried a bunch of variations and none of them helped, so I don't think this will either.

**Comment by gwenn** [comment]
Indeed:
https://sqlite.org/pragma.html#pragma_locking_mode
> The first time the database is read in EXCLUSIVE mode, a shared lock is obtained and held. The first time the database is written, an exclusive lock is obtained and held.

So no impact on read-only accesses.
Tested with:
```rust
use rusqlite::{Connection, OpenFlags, Result};
use std::thread;
use std::time::Instant;

fn main() -> Result<()> {
    let path = "../../Downloads/SQLite_databases_for_learning_data_science-main/diamonds.db";
    let count = thread::available_parallelism().unwrap().get();
    println!("{}", count);

    let start = Instant::now();
    let mut handles = Vec::with_capacity(count);
    for i in 0..count {
        let p = path.to_owned();
        handles.push(thread::spawn(move || {
            let db = Connection::open_with_flags(p, OpenFlags::SQLITE_OPEN_READ_ONLY).unwrap();
            db.pragma_update(None, "locking_mode", "EXCLUSIVE").unwrap();
            let test: u32 = db
                .query_row("SELECT count(1) FROM Observation;", [], |row| row.get(0))
                .unwrap();
            println!("{} => {}", i, test)
        }));
    }
    for h in handles {
        h.join().unwrap();
    }
    println!("Time elapsed: {:?}", start.elapsed());
    Ok(())
}
```
```
# single thread:
53940
Time elapsed: 20.547839ms
# four threads:
2 => 53940
0 => 53940
1 => 53940
3 => 53940
Time elapsed: 22.412348ms
```
So both SQLite / rusqlite seems to behave correctly.

**Comment by devnev** [comment]
Thanks for the help. I've taken your exact code, and the diamonds.db from https://github.com/davidjamesknight/SQLite_databases_for_learning_data_science, and I get very different numbers between single-thread (by hardcoding `count` to `1`) and multiple threads (the code as you pasted it).


On the linux VM I was originally using, cross-compiled from my mac with the release profile:
```
1
0 => 53940
Time elapsed: 8.605188ms
```
```
16
4 => 53940
10 => 53940
11 => 53940
0 => 53940
6 => 53940
9 => 53940
8 => 53940
3 => 53940
2 => 53940
13 => 53940
14 => 53940
15 => 53940
12 => 53940
7 => 53940
5 => 53940
1 => 53940
Time elapsed: 109.59466ms
```

On my (intel) mac, with plain `cargo run`
```
1
0 => 53940
Time elapsed: 7.004834ms
```
```
8
7 => 53940
0 => 53940
3 => 53940
4 => 53940
6 => 53940
2 => 53940
1 => 53940
5 => 53940
Time elapsed: 103.662499ms
```

In case it matters, my cargo.toml has
```toml
[[package]]
name = "rusqlite"
version = "0.32.1"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "7753b721174eb8ff87a9a0e799e2d7bc3749323e773db92e0984debb00019d6e"
dependencies = [
 "bitflags",
 "chrono",
 "fallible-iterator",
 "fallible-streaming-iterator",
 "hashlink",
 "libsqlite3-sys",
 "smallvec",
]

[[package]]
name = "libsqlite3-sys"
version = "0.30.1"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "2e99fb7a497b1e3339bc746195567ed8d3e24945ecd636e3619d20b9de9e9149"
dependencies = [
 "cc",
 "pkg-config",
 "vcpkg",
]
```

**Comment by gwenn** [comment]
I didn't have to use the 'bundled' feature but maybe you should (at least temporarily to try to isolate the issue).

**Comment by devnev** [comment]
Oh, I already had the bundled feature enabled, sorry for the confusion.

I've reverted to your pasted code but with the bundled feature removed, and locally (intel mac) 1 thread takes ~10ms, while 8 threads take around 20ms.

Back on the VM, now building natively on the VM rather than cross compiling (I added the bundled feature originally to make cross-compile easier), building the release profile, with the bundled feature removed, I still see the same massive difference - ~6.5ms with a single thread, 110-120ms with a thread per core (16).

Since I'm now building natively on the VM whereas earlier in the thread I was cross-compiling, I've tried adding back the bundled feature, building with release profile. One thread, as above, ~6.5ms. Thread per core, ~120ms.

And finally, commenting out the pragma, trying both with and without the bundled feature, release profile build, roughly the same results on the VM.

**Comment by gwenn** [comment]
Rust nightly ?
```
active toolchain
----------------

nightly-x86_64-apple-darwin (default)
rustc 1.85.0-nightly (d4025ee45 2024-12-12)
```
OS ?
```
Darwin Kernel Version 20.6.0
```
This morning, I tried on Windows 10, Rust stable with mixed results (not as good as nightly / MacOS but not as bad as yours).
I am going to try on a Linux VM.

**Comment by gwenn** [comment]
Results are bad on Linux:
```
active toolchain
----------------
stable-x86_64-unknown-linux-gnu (default)
rustc 1.83.0 (90b35a623 2024-11-26)
```
```
1
0 => 53940
Time elapsed: 10.786398ms
```
vs
```
2
1 => 53940
0 => 53940
Time elapsed: 38.874609ms
```

**Comment by devnev** [comment]
So far I've been using rust stable. Darwin Kernel Version 23.5.0 and Ubuntu 24.04.1 LTS (Linux 6.8.0-1018-azure) respectively.

**Comment by devnev** [comment]
On the Linux VM, switching to nightly has not made much of a difference. I still get 
```
$ rustc --version && cargo build --release && ./target/release/issue
rustc 1.85.0-nightly (a4cb3c831 2024-12-17)
    Finished `release` profile [optimized] target(s) in 0.02s
16
1 => 53940
10 => 53940
12 => 53940
2 => 53940
0 => 53940
3 => 53940
7 => 53940
15 => 53940
11 => 53940
8 => 53940
4 => 53940
6 => 53940
9 => 53940
5 => 53940
13 => 53940
14 => 53940
Time elapsed: 105.578678ms
```

**Comment by devnev** [comment]
On local Mac (14.5, Darwin Kernel Version 23.5.0), nightly does make a noticeable improvement: 10-14ms single-threaded, 21-24ms multi-threaded.

**Comment by gwenn** [comment]
https://sqlite.org/forum/info/68a64442fa9c825e
> Another thing to do is to turn off memory statistics, either by building with -DSQLITE_DEFAULT_MEMSTATUS=0 or using "sqlite3_config(SQLITE_CONFIG_MEMSTATUS, 0);" at run time

```rust
use rusqlite::{ffi, Connection, OpenFlags, Result};
use std::thread;
use std::env;
use std::time::Instant;

fn main() -> Result<()> {
    unsafe {
        ffi::sqlite3_config(ffi::SQLITE_CONFIG_MEMSTATUS, 0);
    }
    let path = "diamonds.db";
    let count = if env::args().len() > 1 {
        1
    } else {
        thread::available_parallelism().unwrap().get()
    };
    println!("{}", count);

    let start = Instant::now();
    let mut handles = Vec::with_capacity(count);
    for i in 0..count {
        let p = path.to_owned();
        handles.push(thread::spawn(move || {
            let db = Connection::open_with_flags(p, OpenFlags::SQLITE_OPEN_READ_ONLY | OpenFlags::SQLITE_OPEN_NO_MUTEX).unwrap();
            //db.pragma_update(None, "locking_mode", "EXCLUSIVE").unwrap();
            let test: u32 = db
                .query_row("SELECT count(1) FROM Observation;", [], |row| row.get(0))
                .unwrap();
            println!("{} => {}", i, test)
        }));
    }
    for h in handles {
        h.join().unwrap();
    }
    println!("Time elapsed: {:?}", start.elapsed());
    Ok(())
}
```
On windows (bundled) stable:
```
1
0 => 53940
Time elapsed: 7.4982ms
```
```
8
2 => 53940
5 => 53940
1 => 53940
6 => 53940
7 => 53940
4 => 53940
0 => 53940
3 => 53940
Time elapsed: 30.9922ms
```
vs (without SQLITE_CONFIG_MEMSTATUS tweak)
```
8
5 => 53940
3 => 53940
7 => 53940
4 => 53940
1 => 53940
2 => 53940
0 => 53940
6 => 53940
Time elapsed: 47.3525ms
```

**Comment by gwenn** [comment]
https://sqlite.org/custombuild.html
> For multi-threaded applications that are careful about how they manage threads, SQLite supports an alternative run-time configuration that is half way between not using any mutexes and the default situation of mutexing everything in sight. This in-the-middle mutex alignment can be established as follows:
```
sqlite3_config(SQLITE_CONFIG_MULTITHREAD);
sqlite3_config(SQLITE_CONFIG_MEMSTATUS, 0);
```
gives
```
8
6 => 53940
2 => 53940
5 => 53940
3 => 53940
7 => 53940
0 => 53940
4 => 53940
1 => 53940
Time elapsed: 25.3214ms
```

**Comment by gwenn** [comment]
Back on Mac bundled / unstable:
1 thread:
![flamegraph_1_thread](https://github.com/user-attachments/assets/9efbea6d-887d-4b51-9411-9246dfbedfc7)
4 threads:
![flamegraph_4_threads](https://github.com/user-attachments/assets/673372d9-16e0-4585-a001-6762d8b27855)
If you need more help related to SQLite (not rusqlite), I suggest you ask on its dedicated [forum](https://sqlite.org/forum/forum).

**Comment by devnev** [comment]
How did you set the sqlite config options via rusqlite? Or did you modify rusqlite directly, in which case, is there any chance rusqlite could expose `sqlite3_config` and its options?

From reading the section `2.0 Configuring Or Replacing The Mutex Subsystem`, it looks like rusqlite could be setting
```
sqlite3_config(SQLITE_CONFIG_MULTITHREAD);
sqlite3_config(SQLITE_CONFIG_MEMSTATUS, 0);
```
by default, as connections and statements are not Sync.

**Comment by devnev** [comment]
I've now tried combinations with those sqlite3_config options too. On the VM, it doubles the speed of the multi-threaded version from 70ms down to 30ms, which is still a lot slower than the single-threaded 5ms. With feature=bundled removed, the sqlit3_config options bring the multi-threaded performance from 65ms down to 18ms, vs. single-threaded 4ms.

I've somewhat lost track of all the combinations I've tried, but with the original job that was having issues, I've discovered that removing features=bundled does make a big improvement. It doesn't result in as much of a throughput improvement (compared to single-threaded) as I would have liked, but it is somewhat faster than the single-threaded run. My previous testing with bundled vs non-bundled was only on the small program, I didn't test the original job. Given all the additional factors involved, I'm don't think I have the energy to dig into that any further.

I'm ok to close this issue, unless you think there's anything I can add that would help the `rusqlite` project. Thanks again for the help

**Comment by gwenn** [comment]
There is also this one:
[SQLITE_DISABLE_PAGECACHE_OVERFLOW_STATS](https://sqlite.org/compile.html#_options_to_disable_features_normally_turned_on)
> Setting this option has been shown to increase performance in high concurrency multi-threaded applications.
