### ISSUE TITLE
Jiff time support

### ISSUE THREAD

**Issue by andrewbaxter** [rusqlite/rusqlite#1619]
I think [Jiff](https://github.com/BurntSushi/jiff) is somewhat popular - I need to use it in a project and I'd like to avoid including both dependencies and converting between them for `rusqlite`.

**Comment by gwenn** [comment]
https://github.com/search?q=repo%3Arusqlite%2Frusqlite%20jiff&type=code

**Comment by andrewbaxter** [comment]
Whoops, you're right! Sorry, I thought I had already checked...
