### ISSUE TITLE
Add feature to disable thread safety in bundled build

### ISSUE THREAD

**Issue by DoumanAsh** [rusqlite/rusqlite#321]
While I do see a sense in having thread safety by default when compiling sqlite, could we maybe allow to disable thread safety via feature?

P.s. I'm windows guy so it bundled build is always nice fore me

**Comment by gwenn** [comment]
Currently, you can't disable thread safety because of [this](https://github.com/jgallagher/rusqlite/blob/master/src/lib.rs#L682) check.
Do you use `rusqlite` or `libsqlite3-sys` only ?

**Comment by DoumanAsh** [comment]
Ah... I should've been specific: I use only `libsqlite3-sys` through diesel.

**Comment by gwenn** [comment]
See https://github.com/rusqlite/rusqlite/issues/1211#issuecomment-1656027096 for custom compilation flags.
