### ISSUE TITLE
option for SQLITE_ENABLE_ICU

### ISSUE THREAD

**Issue by bedax** [rusqlite/rusqlite#531]
Hello, it would be nice if things like UPPER, LOWER, COLLATE, etc would support non-ascii characters. For this, SQLITE_ENABLE_ICU has to be enabled at compile time. I'm happy to submit a PR for this if you want the feature.

I assume the best thing to do would be to link to the system ICU. Are there any potential pitfalls that I'm missing?

**Comment by gwenn** [comment]
Why not redefine this function in Rust ?
https://docs.rs/rusqlite/0.18.0/rusqlite/functions/index.html

**Comment by bedax** [comment]
I assumed sqlite would 'get it right' compared to my attempts, particularly I thought it might be like the `LIKE` and `GLOB` functions, where sqlite only supports indexing with them if they haven't been overloaded. I suppose I need to look into it more. If that's not the case then I'll happily override the functions instead.

**Comment by bedax** [comment]
Well, for now overriding seems like a better idea. I'll go with that. Thanks

**Comment by bedax** [comment]
After looking at it some more, it still seems like it would be useful if rusqlite had unicode support. Overriding UPPER, etc doesn't seem like enough, unicode support for COLLATE seems ideal.

My use case, by the way, is case insensitive matching. I can do `UPPER(column) = UPPER(:something)` but this comes at quite a cost as apparently sqlite will no longer use the index on 'column' in this case. So `column = :something COLLATE NOCASE` would be better.

**Comment by gwenn** [comment]
See #534

**Comment by bedax** [comment]
That looks very promising, great work!
