### ISSUE TITLE
`params!` does not work with `[u8]`

### ISSUE THREAD

**Issue by e00E** [rusqlite/rusqlite#536]
Neither of following invocation of `params!` compiles:

```rust
extern crate rusqlite;

fn main() {
    let slice = [0u8; 0];
    rusqlite::params![slice];
    rusqlite::params![&slice];
}
```

```
error[E0277]: the trait bound `[u8; 0]: rusqlite::ToSql` is not satisfied
   --> src/main.rs:
    |
    |     rusqlite::params![slice];
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `rusqlite::ToSql` is not implemented for `[u8; 0]`
    |
    = help: the following implementations were found:
              <[u8] as rusqlite::ToSql>
    = note: required for the cast to the object type `dyn rusqlite::ToSql`
```

From reading the documentation (specifically of `ToSql`) it seems like it should work because a `u8` slice should be usable as an sqlite type for blobs.

I guess this is known to not work and is a limitation of the type system or the macro somehow but in this case it could be documented somewhere.

I have worked around the problem with `slice.to_vec()`.

**Comment by gwenn** [comment]
https://docs.rs/rusqlite/0.18.0/rusqlite/blob/struct.ZeroBlob.html ?

**Comment by gwenn** [comment]
Not related to `params!` macro.
```
        let slice = [0u8; 0];
        db.query_row("SELECT ?1",
        &[&slice],
            |row| row.get::<_, Vec<u8>>(0),
        ).unwrap();
```
same error...

**Comment by gwenn** [comment]
```rust
        let slice = [0u8; 0];
        db.query_row("SELECT ?1",
        &[slice.as_ref()],
            |row| row.get::<_, Vec<u8>>(0),
        ).unwrap();
```
works.

**Comment by thomcc** [comment]
I'd also expect
```rust
        let slice: &[u8] = &[];
        db.query_row("SELECT ?1",
        params![slice],
            |row| row.get::<_, Vec<u8>>(0),
        ).unwrap();
```
to work.

**Comment by e00E** [comment]
The 0 size was just for the example. This is more clear:

```rust
fn f(slice: &[u8; 10]) {
    // Does not compile.
    rusqlite::params![slice];
}
```

But while writing this I found a better solution than creating a vector:

```rust
fn g(slice: &[u8; 10]) {
    // Compiles.
    rusqlite::params![&slice[..]];
}
```

It looks like it just does not work for fixed size slices but does work for slice references. I believe this is related to the missing cost generics which cause traits for slice references to not work on fixed sice slices.

Since there is now a good solution, feel free to close this issue. It might still be helpful to document this somewhere.

**Comment by thomcc** [comment]
Yes, what you call fixed size slices are more typically called 'array references', although I think people would generally know what you mean by calling them that. That said, they aren't slices, and traits and methods that are implemented for slices are not implemented for array references. As you mention const generics may help fill this gap.

I think you'll have to close the issue though, due to the repository owner not being particularly active anymore.

**Comment by e00E** [comment]
I take it people that can approve pull requests cannot close issues - only the owner? In that case  I'll close it.

**Comment by davidbailey00** [comment]
@e00E can this be reopened now that const generics are on the horizon? Once 1.51 is out, I'm happy to write a PR to implement `[u8; N]` support, although I'm fairly new to Rust so might not make the most idiomatic solution!

**Comment by thomcc** [comment]
Hmm, fair enough. I'll reopen for me to take a look at it. I have a few changes planned that require const generics anyway (a less cludgey version of the params changes that are on master).
