### ISSUE TITLE
Serialize a database

### ISSUE THREAD

**Issue by jaybutera** [rusqlite/rusqlite#559]
I'm wanting to send databases over a network. It would be great to be able to serialize a database as specified in the C interface here: 
https://www.sqlite.org/c3ref/serialize.html

**Comment by gwenn** [comment]
This API is:
* disabled by default (https://www.sqlite.org/compile.html#enable_deserialize).
* available only since recently (https://sqlite.org/changes.html#version_3_23_0).
Why not use the [backup](https://sqlite.org/c3ref/backup_finish.html#sqlite3backupinit) API ?

**Comment by gwenn** [comment]
@link2xt Original post doesn't say that there is a space issue (and explicitly specifies which C API is expected to be used).
Also you should already be able to reimplement `sqlite3_db_dump` by using current `rusqlite` API.

**Comment by gwenn** [comment]
Fixed in version 0.30.0 (#1341)
