### ISSUE TITLE
Addition of debug formatting support to rusqlite types

### ISSUE THREAD

**Issue by l-x-u** [rusqlite/rusqlite#572]
I think this could be useful for debugging purposes -- I am interested to hear others' opinions. I have not attempted implementing this yet, I don't know how many types could just be `derive`d and how many would require actual code. If there is interest, I may start a branch.

**Comment by gwenn** [comment]
Do you mean:
```rust
pub trait FromSql: Sized+Debug {
...
}

pub trait ToSql: Debug {
...
}
```
Or
```rust
impl Debug for Backup {
...
}
```
?

**Comment by Josh-Thompson** [comment]
The second was my intention.

**Comment by billop** [comment]
It would be great if Rows for example could simply be viewed with `dbg!()` or printed out.
