### ISSUE TITLE
rusqlite with windows service

### ISSUE THREAD

**Issue by tnekic** [rusqlite/rusqlite#582]
when I try to create database from windows service (windows-service ="0.2.0") it refuses to start service (Error 1053) on let conn = Connection::open("c:\\my_data.db").unwrap();
From plain cli app works fine.

**Comment by gwenn** [comment]
Error 1053 is not an error code produced by SQLite.
Maybe the SQLite dll is missing like [here](https://forums.wxwidgets.org/viewtopic.php?t=30544) ?
If you don't provide more information, we cannot help you.
Sorry.
