### ISSUE TITLE
Typo in doc of row.rs

### ISSUE THREAD

**Issue by adrian5** [rusqlite/rusqlite#590]
> …and most callers will be better served by [`get` or `get`](https://github.com/jgallagher/rusqlite/blob/master/src/row.rs#L256).

I would have submitted a PR, but I'm new to Rusqlite and wasn't sure which other get function was meant here.

**Comment by gwenn** [comment]
It's my fault:
https://github.com/jgallagher/rusqlite/commit/6d9ae896b5e3553a31c3c0aa7648e7851f1d37ff#diff-544a3f2e4add89ae72d46f87e45bc0ee
So it should be `get` or `get_unwrap`...

**Comment by striezel** [comment]
This typo has been fixed in commit [e154ccb60630c87f28775363270d8e9afde16425](https://github.com/rusqlite/rusqlite/commit/e154ccb60630c87f28775363270d8e9afde16425#diff-24d3b409cbfcdaa05a38a56d2f5b4b480b6cb89bc9015002f643f5b7768288b8), so that this issue can be closed now.
