### ISSUE TITLE
error: couldn't read out/bindgen.rs: The system cannot find the path specified.

### ISSUE THREAD

**Issue by Boscop** [rusqlite/rusqlite#593]
I cloned this repo and tried to build `libsqlite3-sys` but I get this error:
```sh
$ cargo check
    Updating crates.io index
   Compiling libsqlite3-sys v0.17.0 (D:\3rdparty\rusqlite\libsqlite3-sys)
error: couldn't read D:\3rdparty\rusqlite\target\debug\build\libsqlite3-sys-0ac88c455badfd8a\out/bindgen.rs: The system cannot find the path specified. (os error 3)
  --> libsqlite3-sys\src\lib.rs:52:1
   |
52 | include!(concat!(env!("OUT_DIR"), "/bindgen.rs"));
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: could not compile `libsqlite3-sys`.

To learn more, run the command again with --verbose.
```
I'm on Windows 10, I have this in my `.cargo/config`:
```toml
[target.x86_64-pc-windows-msvc.sqlite3]
rustc-link-search = ['D:\_rustlibs\x64']
rustc-link-lib = ["sqlite3"]
```
When I remove this, `libsqlite3-sys` builds but for my own crate that depends on `libsqlite3-sys` (through diesel), I get:
> LINK : fatal error LNK1181: cannot open input file 'sqlite3.lib'

But when I have that part of `.cargo/config`, I get the first error when building my crate..

What's the correct way? :)
And how can I choose between static and dynamic linking?

**Comment by gwenn** [comment]
Normally, the `bindgen.rs` file is either copied or generated in a `target` directory.
But for reason unknown, it is not.

Could you please describe which [features](https://github.com/jgallagher/rusqlite/blob/master/libsqlite3-sys/Cargo.toml#L14) are used ?

I don't have access to a windows machine.
So maybe you can try to add trace (`eprintln!`) in your local copy of [build.rs](https://github.com/jgallagher/rusqlite/blob/master/libsqlite3-sys/build.rs) and debug.
Or as suggested, try the verbose mode:
> To learn more, run the command again with --verbose

You can also try to reproduce the error on appveyor: Fork this repository, edit your local copy of [appveyor.yml](https://github.com/jgallagher/rusqlite/blob/master/appveyor.yml#L34) and try to reproduce your custom build with the same features.
