### ISSUE TITLE
add colused for best_index on virtual tables

### ISSUE THREAD

**Issue by graf0** [rusqlite/rusqlite#598]
it's since 3.10.0 and later gives us colUsed in sqlite3_index_info struct - it's a bitmask of column used in query. That could potentialy improve some vtabs implementations - if I know I don't need some large/hard to compute column I can skip.

**Comment by gwenn** [comment]
Yes, there is already a TODO [here](https://github.com/jgallagher/rusqlite/blob/master/src/vtab/mod.rs#L321)

**Comment by gwenn** [comment]
See #639

**Comment by gwenn** [comment]
Version 0.28.0 released.
