### ISSUE TITLE
Separation of named/positional params lead to API duplication

### ISSUE THREAD

**Issue by thomcc** [rusqlite/rusqlite#609]
For example, all the `_named` (vs the non-`_named`) functions on https://docs.rs/rusqlite/0.21.0/rusqlite/struct.Statement.html. In mozilla/application-services, we even have a extension trait which exists/started mainly as a way to get more methods for `_named` variants (also cached) and such: https://github.com/mozilla/application-services/blob/master/components/support/sql/src/conn_ext.rs

Really this is probably my biggest complaint about rusqlite's API. I don't really have a solution (the ones I've thought of all hit coherence issues or restrict the API in ways I wouldn't want to give up), but it seems like it should have an issue on file, since its a pain for maintenance. It's probably worth investigating what other non-orm (and non-macro) SQL crates do.

**Comment by gwenn** [comment]
As far as know,
* `postgresql` does not support named parameters, only `$NNN`. So you can do `SELECT $1, $1 + 10;` 
* `JDBC` does not support named parameters, only `?`. So you must bind several times the same value.
* `SQLite` does support named parameters but [sqlite3_bind()](https://sqlite.org/c3ref/bind_blob.html) functions support only indexes. `sqlite3_bind_parameter_index()` must be used to translate a symbolic parameter name into its equivalent numeric index.

So maybe we should have only non-`_named` functions and add a single method that do the translation: `&[(&str, &dyn ToSql)]` => `IntoIterator<Item=ToSql>` ?

**Comment by thomcc** [comment]
I didn't realize that this was so uncommon, most of my professional experience has been with SQLite or MySQL (which also has them).

I'm aware that there's a cost, but my experience has definitely been that the readability gains can be substantial, and I've never seen the cost take any time compared to the query that generally follows. So I don't really like having there be a separate function for this...

Along the lines of your suggestion, something like

```rust
trait IntoParams {
    type Param: ToSql;
    // It's likely that this would be better as `Item = (i64, Self::Param)`
    // to avoid needing to reorder for named params...
    type Params: IntoIterator<Item = Self::Param>;
    fn into_params(self, stmt: &Statement) -> Self::Params;
}
```

might work (probably with more Result<T> tho). 

E.g. basically `IntoIterator<Item: ToSql>` but that passes the statement into its ctor, and each function could take `params: P) where P: IntoParams` or something (e.g. users probably would never call the trait directly).

These possibilities have coherence issues though (since it would likely need a blanket for the existing cases, which I think are important, to work)... Maybe having named params be a wrapper around the &[(&str, &dyn ToSql)]  (which get created by `named_params!`, or `.into()`...). would make it clear enough to the impl solver that the cases don't overlap. Dunno, I might poke around with it at some point.

What are your thoughts?
