### ISSUE TITLE
rustqlite not building for RPI 3B

### ISSUE THREAD

**Issue by EchedeyLR** [rusqlite/rusqlite#618]
```
echedey@debian-pi-3b:~$ git clone https://github.com/jgallagher/rusqlite
Clonando en 'rusqlite'...
remote: Enumerating objects: 53, done.
remote: Counting objects: 100% (53/53), done.
remote: Compressing objects: 100% (44/44), done.
remote: Total 6358 (delta 21), reused 20 (delta 9), pack-reused 6305
Recibiendo objetos: 100% (6358/6358), 5.09 MiB | 261.00 KiB/s, listo.
Resolviendo deltas: 100% (4507/4507), listo.
echedey@debian-pi-3b:~$ cd rusqlite/
echedey@debian-pi-3b:~/rusqlite$ cargo build
echedey@debian-pi-3b:~/rusqlite$ cargo build
    Updating crates.io index
error: process didn't exit successfully: `rustc -vV` (signal: 11, SIGSEGV: invalid memory reference)
--- stdout
rustc 1.40.0 (73528e339 2019-12-16)
binary: rustc
commit-hash: 73528e339aae0f17a15ffa49a8ac608f50c6cf14
commit-date: 2019-12-16
host: aarch64-unknown-linux-gnu
release: 1.40.0
```

**Comment by EchedeyLR** [comment]
I got it building after adding until 4GB of swap and disabling parallel compilation in the app I was compiling.

**Comment by thomcc** [comment]
That's pretty surprising -- Rusqlite under default config doesn't have a ton of deps and needing 4GB is... More than I'd expect.

That said, I don't think there's much we can do about this on this side. Sorry you had trouble here.

**Comment by EchedeyLR** [comment]
Sorry if I confused to you. 

I added 4 GB for general building in the app I was trying it. 

No idea exactly how much it takes but worked after adding additional swap, so can't be, at least, compiled with near 1GB of free memory as I tried to compile manually too, but the successful test was compiling all the dependencies in sequence (1 by 1) for the other app.

**Comment by EchedeyLR** [comment]
I mean, I reported this as suggestion by a Delta Chat contributor that asked me to try this (and other dependences of its software) to compile manually and see if it failed (what I did).

After adding swap memory I tried to compile the app together with the dependence (in sequence ofc but without any other test due to being successful) but I just forgot to solve/close this issue with what I made.
