### ISSUE TITLE
Travis CI tests don't run on PRs

### ISSUE THREAD

**Issue by thomcc** [rusqlite/rusqlite#663]
See https://github.com/jgallagher/rusqlite/pull/662 -- It actually causes (right now) the rarray tests to fail, but we have way better coverage in travis than on appveyor/github.

**Comment by thomcc** [comment]
It looks like these tests have started failing in the meantime (unrelated to that PR, actually).

Example: `cargo test --features "array bundled csvtab series vtab"`.

**Comment by thomcc** [comment]
The failing test is fixed but we should look into a way to regain coverage there on PRs.

@gwenn: When you have time, thoughts?

**Comment by gwenn** [comment]
It seems that PR #660 is the reason why travis fails.
Because everything was fine until PR #660.

**Comment by thomcc** [comment]
That makes some sense, as "`Rc<T>` which implements `ToSql`" became ambiguous. This seems fine to me, as I think generally needing to be explicit in `collect()` calls is normal.

That said, we should still get the coverage back.

**Comment by gwenn** [comment]
@jgallagher Sorry to disturb you but there is something wrong with Travis CI.
For example, I just merged some changes in #631.
Associated build (1508) is visible in https://travis-ci.org/github/jgallagher/rusqlite/pull_requests .
But not on #631 page !

**Comment by thomcc** [comment]
Fixed now, you can see in https://github.com/rusqlite/rusqlite/pull/712.
