### ISSUE TITLE
Consider implementing `FromSql` for `usize`

### ISSUE THREAD

**Issue by thomcc** [rusqlite/rusqlite#700]
From the docs:

> Note that `FromSql` and `ToSql` are defined for most integral types, but
> not `u64` or `usize`. This is intentional; SQLite returns integers as
> signed 64-bit values, which cannot fully represent the range of these
> types. Rusqlite would have to
> decide how to handle negative values: return an error or reinterpret as a
> very large postive numbers, neither of which
> is guaranteed to be correct for everyone.

I think we should just do this by returning an error for out-of-range values. This is consistent with how we handle reading all other integer types -- e.g. `sqlite3_column_int64` is the only API offered here by sqlite, and when we see out of range values of other integer types we return an error. Not sure why usize (or u64, but it's less commonly needed) should be special here.

**Comment by gwenn** [comment]
See https://github.com/rusqlite/rusqlite/commit/ebcec59969398383e925c8d87a3d90e38cf1a4e0#diff-39b0c20ec93c20560f7e0063c6ef5ced839b4ec41b5c8a64252ecd56cc42aec4R114

**Comment by gwenn** [comment]
Fixed by #823
