### ISSUE TITLE
missing link math(-lm)?

### ISSUE THREAD

**Issue by woodgear** [rusqlite/rusqlite#718]
i try to build a static linked libary (which use rusqlite) in linux
```
[lib]
crate-type = ["staticlib"]
path="src/lib.rs"
rusqlite = {version = "0.22.0",features = ["bundled"]}
```
but when other program link to this lib it report those error
```
(sqlite3.o): In function `fts5Bm25Function':
sqlite3.c:(.text.fts5Bm25Function+0x1ac): undefined reference to `log'
```
it seems that rusqlite does not static link math libary (-lm)?

**Comment by thomcc** [comment]
What OS are you on?

**Comment by woodgear** [comment]
ubuntu 18.04

**Comment by thomcc** [comment]
Ah, are you using a `musl` target, e.g. x86_64-unknown-linux-musl or i686-unknown-linux-musl?

I'm just trying to understand how to repro, or why we haven't seen this before.

**Comment by woodgear** [comment]
no,i'm using `stable-x86_64-unknown-linux-gnu (default)`

**Comment by thomcc** [comment]
Oh, I see so your steps are something like:
- make `staticlib` that uses rusqlite, e.g. libfoo.a
- try to link some c program against `libfoo.a`?

**Comment by thomcc** [comment]
I think you have to put the -lm in the downstream code. When building a static library I don't think there's a way to indicate libraries you need to link to. That's resolved at the end.

I'll look a bit though. I also think we should offer a way to turn off building in `FTS5` since right now we don't use it.

**Comment by thomcc** [comment]
Actually it gets stripped out by the linker later so it doesn't matter, I think.

For this though, if you want it to work you need to add `-lm -ldl -lpthread` when building whatever the static library is linked into. You can avoid that by using the `x86_64-unknown-linux-musl` target like:
```
$ rustup target install x86_64-unknown-linux-musl
$ sudo apt install musl musl-tools
```
Then use `cargo build --target x86_64-unknown-linux-musl`, I think?

**Comment by woodgear** [comment]
thanks a lot,it do fix my problems.

**Comment by thomcc** [comment]
In case you have other troubles or someone else finds this issue:

If I have a crate `my_rust_crate` with `crate-type=["staticlib"]`, and then use it from `my_c_program.c`:

- no musl (e.g. link with glibc)
```
$ cargo build
$ cc my_c_program.c -o my_c_program -lmy_rust_crate -Ltarget/debug -lm -ldl -lpthread
```

- use musl (e.g. standalone)
```
$ cargo build --target x86_64-unknown-linux-musl
$ musl-gcc my_c_program.c -o my_c_program -lmy_rust_crate -Ltarget/x86_64-unknown-linux-musl/debug
```
