### ISSUE TITLE
Need a way to get type for column

### ISSUE THREAD

**Issue by packetzero** [rusqlite/rusqlite#721]
Firstly, thank you for this impressive project.  I want to be able to get the type for a column (from Statement or Value or ValueRef).  It seems that value_ref mod is private, Statement.stmt is private as well, so I can't use sqlite3_column_type().  All of the examples show scenarios where the column types are known at compile time.  Am I missing something?

**Comment by thomcc** [comment]
Hmm, I guess we don't expose column_type.

[Statement::columns](https://docs.rs/rusqlite/0.22.0/rusqlite/struct.Statement.html#method.columns) and [Column::decl_type](https://docs.rs/rusqlite/0.22.0/rusqlite/struct.Column.html#method.decl_type) might help you

**Comment by gwenn** [comment]
With a `ValueRef`/`Value`, you can deduce the `sqlite3_column_type`:
```
    Null => SQLITE_NULL
    Integer(i64) => SQLITE_INTEGER
    Real(f64) => SQLITE_FLOAT
    Text(&'a [u8]) => SQLITE_TEXT
    Blob(&'a [u8]) => SQLITE_BLOB
```
[ValueRef](https://docs.rs/rusqlite/0.22.0/rusqlite/types/enum.ValueRef.html) is a dynamic type value.
And there is a [test_dynamic_type](https://github.com/rusqlite/rusqlite/blob/2a90073c1e6f2cdf01e357de79af378e817a0c9e/src/types/mod.rs#L337).

**Comment by packetzero** [comment]
When I was trying to use ValueRef, it was telling me that rusqlite::types was private.  However, it now works.  So either it changed from v0.21 to v0.22.  In any case, it works for me now. Thanks for quick response.
```
    match row.get_raw_checked(i).unwrap() {
        ValueRef::Integer(val) => {
            s += &format!("{}",i64::from(val));
        },
        ValueRef::Real(val) => {
            s += &format!("{}",f64::from(val));
        },
        ValueRef::Text(val) => {
            s += &format!("'{}'", std::str::from_utf8(val).unwrap());
        },
        _ => {}
    }
```
