### ISSUE TITLE
Add tests for 32-bit systems.

### ISSUE THREAD

**Issue by thomcc** [rusqlite/rusqlite#722]
One impediment here is that the bundled bindings include tests that only work on 64-bit systems (because they include hard-coded constants).

Probably worth removing those tests when generating the bundled bindings and including them for non-bundled cases (e.g. buildtime_bindgen).

**Comment by thomcc** [comment]
Would have caught https://github.com/rusqlite/rusqlite/pull/724 probably

**Comment by dkg** [comment]
This is actually causing [build failures on Debian](https://buildd.debian.org/status/package.php?p=rust-libsqlite3-sys)'s 32-bit architectures.  For example, [here's a failing build log for i386](https://buildd.debian.org/status/fetch.php?pkg=rust-libsqlite3-sys&arch=i386&ver=0.25.0-1&stamp=1658384082&raw=0).

I'd love to have the latest version of the libsqlite3-sys in debian, but to do that i'm probably going to need to patch out these tests if the platform is 32-bit, which is a bit disappointing.

**Comment by thomcc** [comment]
Yeah, the bindgen tests in `libsqlite3-sys` are platform-specific, unfortunately. I wrote a PR a long time ago to make bindgen generate them on the side, with the idea that we could have several, but nothing happened with it: https://github.com/rust-lang/rust-bindgen/pull/1761 (It's bitrotted quite a bit, and I probably don't have the time to fix it up either).

Either way, I don't think the tests bindgen emits help much. They basically just test that `#[repr(C)]` is implemented correctly, so I'd accept a patch removing them.

**Comment by dkg** [comment]
@thomcc wrote:
> Either way, I don't think the tests bindgen emits help much. They basically just test that `#[repr(C)]` is implemented correctly, so I'd accept a patch removing them.

#1213 is a patch to remove them from the bundled bindings.  let me know if you'd rather it looks different somehow.  thanks for maintaining rusqlite!

**Comment by thomcc** [comment]
Thanks.

**Comment by dkg** [comment]
#1214 includes removal of the tests from the different stored versions as well.

I notice that those versions don't do things like strip out `__GNUC_VA_LIST`, but i left those choices alone :)

**Comment by thomcc** [comment]
Those versions should be removed honestly. There are a lot of things I need to do to the build.rs when I find time, but haven't found it sadly.

**Comment by dkg** [comment]
i know the feeling!  I'm just reporting what i see and trying to be helpful, not trying to nag you :)

FWIW, at least one of these bundled versions is still in use during standard compilation when not using bundled libsqlite3.

i'm also looking at the code change that resulted from my regeneration of the bundled bindings in #1213, and noticing that it is significantly more transformative than the manual cut jobs in #1214.  I hope i didn't screw that up, but i'd certainly appreciate any sort of more detailed review -- if you've got feedback you want me to consider, i'd be happy to consider it.

**Comment by thomcc** [comment]
Give me a week or so and I can find time for a more detailed review. Looking again, that seems to have cut out more than it should have.

**Comment by dkg** [comment]
i've opened #1215 to try to repair the excessive cutting.  sorry about that!
