### ISSUE TITLE
Rename RowIndex to ColumnIndex

### ISSUE THREAD

**Issue by gwenn** [rusqlite/rusqlite#727]
https://docs.rs/postgres/0.17.3/postgres/row/trait.RowIndex.html
https://docs.rs/rusqlite/0.23.1/rusqlite/trait.RowIndex.html
versus
https://docs.rs/sqlx-core/0.3.4/sqlx_core/row/trait.ColumnIndex.html

**Comment by thomcc** [comment]
Sounds okay to me. On it's own I don't think it would necessarily be worth making a breaking change like this, but I have a few other changes that will breaking probably (probably will get these up next week).

**Comment by thomcc** [comment]
An argument against changing it is that we call the index into an array or slice the "array index" or "slice index".

I think the current name is fine.
