### ISSUE TITLE
Why is xUpdate None?

### ISSUE THREAD

**Issue by nhynes** [rusqlite/rusqlite#730]
Is there a particular reason why vtab [`xUpdate` is `None`](https://github.com/rusqlite/rusqlite/blob/master/src/vtab/mod.rs#L109) other than there simply not being a trait for it?

**Comment by gwenn** [comment]
[read_only_module](https://github.com/rusqlite/rusqlite/blob/master/src/vtab/mod.rs#L90) !

**Comment by nhynes** [comment]
right. I think I meant to say "why isn't there an `UpdateVTab`?" but I've [since inferred](https://github.com/rusqlite/rusqlite/compare/master...nhynes:update-vtab) that the answer is simply "because it hasn't been written yet." Slick library, though! It was really easy to modify.

**Comment by gwenn** [comment]
Version 0.28.0 released.
