### ISSUE TITLE
test doc examples

### ISSUE THREAD

**Issue by gwenn** [rusqlite/rusqlite#744]
I don't see:
```
cargo test --doc
```
in our build script.
And
```
cargo test --all-targets
```
doesn't help.

**Comment by thomcc** [comment]
Oh, huh. I thought `--all-targets` covered doctests...

**Comment by gwenn** [comment]
https://github.com/rust-lang/cargo/issues/6669

**Comment by thomcc** [comment]
Noted, thanks!
