### ISSUE TITLE
feature request: add feature flag to link with sqlite builded with -DSQLITE_OMIT_DECLTYPE

### ISSUE THREAD

**Issue by Dushistov** [rusqlite/rusqlite#751]
I have to link with sqlite3 that part of big C++ library,
and sqlite3 is build with `-DSQLITE_OMIT_DECLTYPE`,
with such explanation:

> Disable returning the declared column type from query (reduces memory usage)

Quick hack to comment out:
```
    pub fn column_decltype(&self, idx: usize) -> Option<&CStr> {
        unsafe {
            let decltype = ffi::sqlite3_column_decltype(self.ptr, idx as c_int);
            if decltype.is_null() {
                None
            } else {
                Some(CStr::from_ptr(decltype))
            }
        }
    }
```

and all usage of it, show that rusqlite "core" not depend on this feature,
so it is easy enough feature, but may be I missed something?

**Comment by thomcc** [comment]
I think I would accept a patch for this if it were reasonable. I hit it when vendoring rusqlite into Firefox, but just enabled decltype instead.
