### ISSUE TITLE
libsqlite3-sys: Wants enum whose variants are SQLite's `Extended Result Code`.

### ISSUE THREAD

**Issue by laysakura** [rusqlite/rusqlite#760]
## Current situation

Enum variant `rusqlite::Error::SqliteFailure` contains `libsqlite3_sys::Error` struct.
And it contains `libsqlite3_sys::ErrorCode`, whose variants [seem to correspond to](https://github.com/rusqlite/rusqlite/blob/6058322cca8de2363e192108c5b0991699e64889/libsqlite3-sys/src/error.rs#L67-L92) [SQLite's Primary Result Code](https://www.sqlite.org/rescode.html#primary_result_code_list).

On the other hand, [SQLite's Extended Result Code](https://www.sqlite.org/rescode.html#extended_result_code_list) is represented by `extended_code` field in `libsqlite3_sys::Error` struct.

In order to pattern-match [`(1555) SQLITE_CONSTRAINT_PRIMARYKEY`](https://www.sqlite.org/rescode.html#constraint_primarykey), for example, a magic number `1555` appears in my code:

```rust
        match self.sqlite_tx.execute("INSERT INTO ...",  NO_PARAMS) {
            Err(e @
                rusqlite::Error::SqliteFailure(
                    libsqlite3_sys::Error {
                        extended_code: 1555,  // MAGIC NUMBER
                        ..
                    },
                    _,
                ),
            ) => Err(MyError::new(..., e),
            ...
```

## Solution suggestion

Replace `extended_code` field in `libsqlite3_sys::Error` struct from `c_int` into `enum ExtendedErrorCode`.

Or adds another field like `extended_code_kind: ExtendedErrorCode` for backward compatibility.

**Comment by gwenn** [comment]
See https://github.com/rusqlite/rusqlite/issues/293
And https://github.com/rusqlite/rusqlite/blob/master/libsqlite3-sys/src/error.rs#L119

**Comment by laysakura** [comment]
Thank you so much.
I confirmed I can use the constant.
