### ISSUE TITLE
Bundled sqlcipher?

### ISSUE THREAD

**Issue by dubiousjim** [rusqlite/rusqlite#765]
I've been experimenting with a fork of this repository where I enable building a bundled version of `sqlcipher`, optionally also bundling in an `openssl`/`libressl` libcrypto. Would you be interested in, or in principle open to a PR with this functionality?

Some related issues: #219, #558.

**Comment by thomcc** [comment]
Hrmm... In principal, yes with caveats.

There are some issues around bundling crypto code being dubious in general though. Statically linking openssl/libressl is ofc a thing that happens, but it causes major problems on linuxes and such where packagers really want crypto to be dynamically linked.

That said, that's not really the important thing to me, as terrible as that sounds.

Quite selfishly, I'd have to request that it not break how I use rusqlite + sqlcipher at work. Specifically, on Firefox for Android and Firefox for iOS we use SQLCipher, linked with a patched build of NSS. It's actually pretty fragile, and I'm hoping that that would get better if more things moved into here. 

That said, an overview of the setup that I'd like to still have a story for:

1. Large workspace, some packages have feature = "sqlcipher", some feature = "bundled". Various ways of turning this workspace into shared objects. Tragically, cargo is eager to combine these two features -- in which the current build.rs for libsqlite3-sys chooses sqlcipher, which is good.

2. We use a specific local build of SQLcipher. I think we have a few custom patches, (checking again it seems possible they've all landed upstream by now, perhaps)

3.

**Comment by dubiousjim** [comment]
My changes *default to* dynamically linking against `libcrypto`, they just also provide an option for bundling that in too (if one is bundling `libsqlcipher`).

I also have some custom patches for SQLCipher. I was wondering how to integrate them into a workflow that this repo could plausibly merge. I've already added an environment variable that permits adding additional -D/-U flags to the compilation of the bundled sqlcipher and/or sqlite3. Perhaps another environment variable interpreted as pointing to a folder of patches, to be applied in alphabetic order? Then a package that depends on `libsqlite3-sys` but wants to patch the sqlcipher source could include the patches in its distribution. (As I'm imagining this, though, it would only work once, patch folders couldn't be chained.)

Re 3. I know my changes would still permit dynamically linking to `libcrypto`. I think they would also permit statically linking to it. Does NSS provide `libcrypto.so/dylib` and `libcrypto.a`?

**Comment by dubiousjim** [comment]
I'm waiting for the author of the `autotools` package to make a release with the latest master of his repo.

Then I can publish some packages `libressl`, `libressl-sys` etc that are basically just copies of [openssl](https://lib.rs/crates/openssl), [openssl-sys](https://lib.rs/crates/openssl-sys) except that when one requests feature `"vendored"`, instead of building a bundled copy of OpenSSL (using the [openssl-src](https://lib.rs/crates/openssl-src) package), they build a bundled copy of LibreSSL (using a replacement package I made, that needs the newer version of `autotools`).

I approached the maintainer of `openssl` etc asking if they were open to including this functionality in their established package, and they said no, they don't want to take on any more responsibility for supporting LibreSSL. Hence my fork. The only difference is whether when you ask to build a bundled version of the crypto + ssl libraries, LibreSSL source gets used instead of OpenSSL. One can link to pre-built system versions of either library.

Currently I use `links="openssl"` in my `libressl-sys` package, hence a Cargo.toml file can't have both `libressl-sys` and `openssl-sys` as dependencies (even if they're behind separate features).

**Comment by dubiousjim** [comment]
As I have things now:

* `features="bundled"` builds sqlite3 from bundled source and statically links that
* `features="sqlcipher"` looks for a prebuilt `libsqlcipher` and links against that
* `features="sqlcipher bundled"` builds sqlcipher from bundled source and statically links that
* `features="bundled-libressl"` is like the previous item, but also passes `feature="vendored"` to my `libressl-sys` package described above, with the result that LibreSSL is also built from bundled source and statically linked.

Re your point 1 above, I understand you to be saying you'd like to preserve the existing behavior that if one builds with `features="sqlcipher bundled"`, the "sqlcipher" is used and "bundled" is ignored. That's fine, I can do that instead. I'd just need to change the API described above. What I'm now doing with `features="sqlcipher bundled"` might instead be done with a new `feature="bundled-sqlcipher"`?

**Comment by thomcc** [comment]
> What I'm now doing with features="sqlcipher bundled" might instead be done with a new feature="bundled-sqlcipher"?

That makes sense, and hopefully is sufficient but see the rest of my comments.

I'm still concerned about the `bundled-libressl` option on linux. And... bundling `sqlcipher` for that matter. That said, I'll ask people with more experience than me about it.

I also am now wondering if supporting `openssl-sys`'s vendored flag in the same manner isn't worth doing too... 

> My changes default to dynamically linking against libcrypto

Hmm... I think this is going to be tricky. I'm inclined to say that by default should stay the same as it is now, which is to say, not link against anything additional...

Sorry, I'm a little paranoid about knocking over the precarious tower of playing cards I have built up over in https://github.com/mozilla/application-services.

(In an ideal world I'd replace our use of SQLCipher with a custom SQLite codec implementation, as SQLcipher is... not without it's downsides. If such a thing were written in Rust it could offer pluggable crypto even. That said, this may never happen, so don't hold your breath).

> I also have some custom patches for SQLCipher. I was wondering how to integrate them into a workflow that this repo could plausibly merge.

I would *strongly* prefer not to have to apply custom patches inside libsqlite3-sys. That sounds like a recipe for disaster long term. It also could easily be a security hole if there's a way to apply patches to cryptography code just by managing to write it into a directory.

I still feel like applications that need that kind of thing should use `{SQLITE3,SQLCIPHER}_{LIB,INCLUDE}_DIR` and such to point at a custom build. For SQLCipher, they might accept the patch if you accepted it upstream, I was incorrect about having any custom patches since that happened for us.

Note that `libsqlite3-sys` is also a little notorious as having a non-standard `build.rs`, and I certainly don't want to make this worse by implementing a weird custom build system for native code in it.

So, if this is required then it would probably be a no-go, sorry. What do your patches do?

> Re 3. I know my changes would still permit dynamically linking to libcrypto. I think they would also permit statically linking to it. Does NSS provide libcrypto.so/dylib and libcrypto.a?

No, it's a totally different API, SQLcipher has support for NSS if you build with `-DSQLCIPHER_CRYPTO_NSS` flag -- it uses https://github.com/sqlcipher/sqlcipher/blob/master/src/crypto_nss.c, and then it links against `libnss3.so` or whatever. (Note that linking against both `libnss3.so` and `libcrypto.so` tends to fail catastrophically, as they both offer functions with names like `SHA256_Update` but expecting totally different parameters...). It's also worth noting that NSS doesn't *really* come in a statically linked form. Or it does, just you have to do a custom build and it's technically unsupported even though it works in practice.

(Eventually we'd like to provide a public crate exposing a rust API for NSS, but it's very idiosyncratic to link against)

**Comment by thomcc** [comment]
One question I have is: Maybe the transitive bundling isn't the right way to go about it.

Maybe instead it would be better to offer features like `link_libressl` which enable an optional dep on libressl and force the link using

```rust
// Add a dependency on libressl-sys if requested, so that it
// builds prior to SQLcipher and libressl's native functions
// are available.
#[cfg(feature = "sqlcipher-link-libressl-sys")]
#[allow(unused_extern_crate)]
extern crate libressl_sys;
```

in libsqlite3-sys. Then, a library or application that wants to use libressl-sys as vendored could do:

```toml
[dependencies.libsqlite3-sys]
version = "..."
features = ["sqlcipher", "bundled-sqlcipher", "link-libressl-sys", "etc..."]

[dependencies.libressl-sys]
version = "..." 
features = ["vendored", "etc..."]
```

This would help keep the `libsqlite3-sys` crate out of trouble, which is another goal of mine :p.

I also must admit I had assumed the `libressl-sys` crate already existed... Given that it doesn't, and I have no guarantee you'll keep maintaining it long term... I think we'd probably also want to have `openssl-sys` supported in this manner too if we take this.

That said, doing so would be pretty trivial if you with this approach.

**Comment by thomcc** [comment]
One further complication is that when shipping on iOS, most users will want to use SQLcipher's use of the system crypto primitives, as I understand it can be tricky to ship custom crypto there. Tragically, Cargo doesn't let you change features based on target arch... It does let you add addition dependencies though... Hrm....

**Comment by dubiousjim** [comment]
I appreciate having this high-level discussion. Saves a lot of time versus me prepping a PR, then having the discussion and iterating.

I agree that it's best to have a path forward that doesn't depend on my (or any other single person's) continuing maintenance.

I like the idea of decoupling `libsqlite-sys` more from the (possible building and) linking of the crypto code. Let's aim for that.

When writing my earlier comments, I momentarily forgot that sqlcipher could be built against different crypto infrastructures than just (some implementation of) `libcrypto`. My changes don't affect that.

Re the possibility of bundling OpenSSL xor LibreSSL: I agree this would be desirable. At the moment, this is blocked because my `libressl-sys` also says `links="openssl"`. Very minor reason in favor of this: the build breaks if I change it, but I'm sure I can figure out the cargo incantations to support it being different. Probably some `DEP_OPENSSL_ETC` variable used elsewhere.

Stronger reason for it: as it stands, with `libressl-sys` also saying `links="openssl"`, cargo prevents a large dependency tree from trying to include both `openssl-sys` and `libressl-sys`.  If they were both included it could be a problem since they'd both be linking against (different instances of) `-lcrypto` and `-lssl`.

I'm not sure of a better way to handle this second consideration. Optimal would be if the `openssl-sys` people permitted a feature to enable building against a bundled LibreSSL instead of bundled OpenSSL, but as I said, [they're not interested in doing that](https://github.com/sfackler/rust-openssl/issues/1283).

Perhaps I should make `libressl-sys` say `links="libressl"`, and just instruct developers that no project should be built with active dependencies on both `libressl-sys` and `openssl-sys`.

**Comment by dubiousjim** [comment]
How's this for a way forward:

1. I'll push a PR that merely enables a `bundled-sqlcipher`, without any `bundled-libre/openssl`. Relies on the client developer to make sure the build process can locate an appropriate crypto library. Perhaps I should include in this PR a change I have that reads an additional environment variable with extra flags to pass to the `cc::Build` instance (`cfg`) before it `.compile()`s. That way one could override the choice of crypto library and so on.

    Currently I call this `LIBSQLITE3_FLAGS`, and it expects a space-separated `"-DSQLITE_FOO=BAR -USQLITE_QUX..."` and so on.

    We persist with having `features="sqlcipher bundled"` print some warning, and acting as if it were just `"sqlcipher"`. To get a bundled build of SQLCipher, one instead has to use the more verbose feature `"bundled-sqlcipher"`. Right?

2. After that's discussed and acceptable, we can discuss how to optionally get the crypto-providing libraries statically linked into the end product, perhaps using versions of these libraries built from some rust package elsewhere in the dependency tree. But aiming for only minimal participation of `libsqlite-sys`. Aiming also not to have any requirement of LibreSSL versus OpenSSL versus other crypto providers that SQLCipher can work with.

**Comment by dubiousjim** [comment]
I had some weird struggle getting the `libsqlite-sys/upgrade.sh` to work. When I checkout the current master and try it, it fails with all sorts of linking errors. I have it working in my fork but I've lost track of what's the minimal change needed to get it to work for me. One change I need to make is this in `build.rs`:

```
@@ -349,10 +465,14 @@ mod bindings {
         let header: String = header.into();
         let mut output = Vec::new();
         let mut bindings = bindgen::builder()
+            .trust_clang_mangling(false)
             .header(header.clone())
             .parse_callbacks(Box::new(SqliteTypeChooser))
             .rustfmt_bindings(true);
```

Maybe that's all that I needed, to get things working. My `cc` resolves to `/opt/local/bin/clang`, which is the MacPorts-installed clang. But I found that I wasn't able to get `./upgrade.sh` working by setting `CC=gcc`, either, unless I had the `.trust_clang_mangling(false)`.

But the issue isn't resolved wholly satisfactorily, because the `bindgen_bundled_version.rs` files that my process generates lacks all the `assert_eq!{...}` blocks that are in the file committed to the repo. Not sure why.

**Comment by dubiousjim** [comment]
> Maybe instead it would be better to offer features like `sqlcipher-link-libressl-sys` which enable an optional dep on libressl and force the link using
> 
> ```rust
> // Add a dependency on libressl-sys if requested, so that it
> // builds prior to SQLcipher and libressl's native functions
> // are available.
> #[cfg(feature = "sqlcipher-link-libressl-sys")]
> #[allow(unused_extern_crate)]
> extern crate libressl_sys;
> ```
> 
> in libsqlite3-sys. Then, a library or application that wants to use libressl-sys as vendored could do:
> 
> ```toml
> [dependencies.libsqlite3-sys]
> version = "..."
> features = ["sqlcipher", "bundled-sqlcipher", "sqlcipher-link-libressl-sys", "etc..."]
> 
> [dependencies.libressl-sys]
> version = "..." 
> features = ["vendored", "etc..."]
> ```
> 
> This would help keep the `libsqlite3-sys` crate out of trouble, which is another goal of mine :p.

This was very interesting. I didn't know that what you were suggesting was possible. Or at least --- what I took you to be suggesting. I thought you were saying, we could have a dependency tree like this:

```
delta
├── alpha
└── beta
    └── gamma
```

And that there could be `extern crate gamma` or `extern crate beta` directives in alpha, even though `alpha` didn't itself declare any (direct or indirect) dependencies on gamma or beta. It would just be the responsibility of delta to make sure those packages were included (and to set a feature in alpha saying it was okay to have those `extern crate` directives).

The point of those directives in alpha would just to make sure that in the build of delta, beta and gamma were built first, and thus that the artifacts they produced were available during the build of alpha.

If that were true, it would indeed make it easier to integrate my libressl-src package into the build of openssl and rusqlite. They wouldn't need any (even optional) dependency on it, but just a feature that some client of these libraries (in my example, above, they'd be alpha and the client would be delta) could request when it also was depending on libressl-src.

However, when I experiment with toy packages, I can't get anything like what I've described to work. I put a declaration `extern crate gamma` in alpha, then try to build `delta`, but it fails during the compilation of alpha with `error[E0463]: can't find crate for `gamma`.

Do you have experience doing something like this successfully? Do I need to provide a `#[link ...]` attribute or something on the `extern crate` directive?

**Comment by dubiousjim** [comment]
Even when I add a `RUSTFLAGS="--extern gamma=/path/to/delta/target/debug/deps/libgamma-xxxxxxxxxxxxxxxx.rlib"` before `cargo run` in the delta directory, I still get:


>   Compiling gamma v0.1.0 (...)
>   Compiling alpha v0.1.0 (...)
> error: extern location for gamma does not exist: .../delta/target/debug/deps/libgamma-....rlib

I think the compilation of alpha is looking for `libgamma.rlib` before it's finished compiling. So I'm understanding that the method that (I thought) you were proposing won't work. (Though it may not have been what you were proposing.)

Thus if I'm going to make it possible for clients that use the openssl and/or rusqlite packages to get their libcrypto.a from my libressl-src package, I'll have to get openssl and/or rusqlite to declare at least an optional dependency on libressl-src.

**Comment by dubiousjim** [comment]
Just pushed a PR implementing the bundling features (see also #770, takes a small fixup to merge the two PRs).

We should check with the Zetetic people if they'd be ok with us re-distributing the amalgamation files from their open-source version in this way, and whether the licensing declarations are correct. But I wanted to hand this off to you, to get another set of eyes on it.

My LibreSSL package is [here](https://github.com/dubiousjim/libressl-src). For the time being, I'm just using it as a patched-in substitute for `openssl-src`. The PR referenced above just includes the standard `openssl-sys` package, with `feature="vendored"`.

**Comment by thomcc** [comment]
I'm a bit busy at the moment, so I'm not sure when I'll have time to review this. Similar, sorry I haven't responded to your other comments here.

I'll try to get started on the review over the weekend, sorry for any issue this causes. I agree we should reach out to Zetetic. I guess I can do that, although I'll probably like to at least start reviewing the code before doing so.

**Comment by thomcc** [comment]
So, I was hit by the moz layoffs in aug. Now that I have my next job lined up, I'm getting back to these things.

What's the status here?

**Comment by dubiousjim** [comment]
Hi Thom, very glad to hear you've got the next gig lined up. I haven't changed anything on this issue since June. Can work with you to get the PR from June 25 acceptable.

My head isn't inside that PR right now, but if I remember right, I was aiming at just targeting standard openssl-sys, without any special handling for LibreSSL beyond what they already provide. So one can use a system-installed LibreSSL or OpenSSL .so, or do a vendored build only of OpenSSL.

The rust-openssl maintainers [don't want to support building with a vendored LibreSSL](https://github.com/sfackler/rust-openssl/issues/1283). Since I do want to do that, I'll just have to [resort to using \[patch.crates-io\]](https://github.com/dubiousjim/libressl-src). The needed changes to their repo are trivial, but I probably can't commit to maintaining a fork that keeps in synch with them.

Looks like rust-openssl isn't working right now with LibreSSL 3.2.1. It was formerly working with LibreSSL 3.2.0; don't know whether the current conflicts are due to the changes to LibreSSL or to rust-openssl.

**Comment by thomcc** [comment]
> My head isn't inside that PR right now, but if I remember right, I was aiming at just targeting standard openssl-sys, without any special handling for LibreSSL beyond what they already provide

Okay, cool. That certainly makes my life easier, even if it makes yours a little harder (sorry).

> The rust-openssl maintainers don't want to support building with a vendored LibreSSL. Since I do want to do that, I'll just have to resort to using [patch.crates-io]. 

You also might be able to use the `[target.<triple>.<links>]` override in `.cargo/config`, possibly.

Long term it might be worth considering if there are language or cargo changes to handle linking against different API-compatible libs better — I'd support it since the libsqlite3-sys build.rs is... frequently a headache for this reason.

**Comment by gwenn** [comment]
Version 0.26.0 released
