### ISSUE TITLE
Environment variables for statically linking libsqlite3/libsqlcipher

### ISSUE THREAD

**Issue by dubiousjim** [rusqlite/rusqlite#766]
Currently around line 200 in `libsqlite-sys/build.rs`, there is:

>         // If the user specifies SQLITE_STATIC (or SQLCIPHER_STATIC), do static
>         // linking, unless it's explicitly set to 0.
>         match &env::var(format!("{}_STATIC", env_prefix())) {

But the comment doesn't match the implementation (`env_prefix()` will be `SQLCIPHER` or `SQLITE3`, never `SQLITE`). I vote for the implementation to stay the same but for the comment to be adjusted.

**Comment by thomcc** [comment]
Nice catch. Feel free to submit a PR or I'll try to get to it some time I have free time and am in that file.

**Comment by dubiousjim** [comment]
fixed by #770
