### ISSUE TITLE
bundle vs bindgen env var override

### ISSUE THREAD

**Issue by jcgruenhage** [rusqlite/rusqlite#769]
It would be very nice for distributions, if there was an override to change the compilation mode of libsqlite3-sys, regardless of what feature is selected. Cross compilation of the `bundled` feature currently fails (at least in Void's infrastructure), and we'd prefer to dynamically link sqlite either way. However, currently, this decision is passed to the crate using libsqlite3-sys, not the distribution maintainers.

References:
https://github.com/launchbadge/sqlx/issues/191#issuecomment-649334666
https://github.com/void-linux/void-packages/pull/22534#issuecomment-649333178

**Comment by thomcc** [comment]
> It would be very nice for distributions, if there was an override to change the compilation mode of libsqlite3-sys, regardless of what feature is selected

This can be doable in some circumstances, but not others. Obviously if you want `bindgen` that has to be a compile time flag -- the whole point of that being optional is that it's a problematic dependency for some, and is slow to compile even if it wasn't a problem to depend (transitively) on LLVM.

Additionally, currently rusqlite itself wants the version of the bindings to match the version of sqlite. This should be relaxes some, however some WIP features, if enabled, would make it a memory safety issue to use a too-old version of sqlite. This is very unfortunate, but a fact of the sqlite API, and outside of our control.

See:

- https://github.com/rusqlite/rusqlite/pull/639#issuecomment-620871847
- https://github.com/rusqlite/rusqlite/pull/631#issuecomment-620874452

That said, I assume the idea would be to use a newer version of sqlite than what we compile with, which should of course, be fine. I also assume you won't need to enable buildtime-bindgen.

> Cross compilation of the bundled feature currently fails (at least in Void's infrastructure),

I'd certainly accept patches to make this work. In https://github.com/mozilla/application-services we cross-compile libsqlite3-sys but we don't use bundled, and instead provide our own build of sqlite. This seems closest to what you want to do.

I've also definitely been able to make `cc` work with cross compilation as part of working on https://github.com/mozilla/rust-android-gradle/, however it was a bit annoying: https://github.com/mozilla/rust-android-gradle/blob/master/plugin/src/main/kotlin/com/nishtahir/CargoBuildTask.kt#L167-L185.

> However, currently, this decision is passed to the crate using libsqlite3-sys, not the distribution maintainers.

For what it's worth, this is pretty standard in the Rust ecosystem...

That said, I'm pretty sympathetic to the desire to not statically link (to some extent I suspected a bug around this was going to be filed eventually), and certainly don't want the use of libsqlite3-sys to be problematic (I think fracturing the ecosystem here would be very unfortunate).

Unfortunately, I'm unsure when I'll have time to do anything around this myself. Probably not for another week or two. It should also maybe be firmed up a little bit more before someone takes a stab at it (at the moment I have low confidence I'd come up with something that solves all your problems), but if you have a concrete idea I'd certainly take a look at a patch.

**Comment by jcgruenhage** [comment]
> This can be doable in some circumstances, but not others. Obviously if you want `bindgen` that has to be a compile time flag -- the whole point of that being optional is that it's a problematic dependency for some, and is slow to compile even if it wasn't a problem to depend (transitively) on LLVM.

It definitely has to be compile time, but the way the flag is passed doesn't have to be a feature flag. Having an environment variable during compile time that overrides the feature should work, no?

> Additionally, currently rusqlite itself wants the version of the bindings to match the version of sqlite. This should be relaxes some, however some WIP features, if enabled, would make it a memory safety issue to use a too-old version of sqlite. This is very unfortunate, but a fact of the sqlite API, and outside of our control.
> That said, I assume the idea would be to use a newer version of sqlite than what we compile with, which should of course, be fine. I also assume you won't need to enable buildtime-bindgen.

Yeah, in the case of void linux it would be sqlite-3.32.3, which should be fine.

> I'd certainly accept patches to make this work, or at least filed issues. In https://github.com/mozilla/application-services we cross-compile libsqlite3-sys but we don't use bundled, and instead provide our own build of sqlite. This seems closest to what you want to do.

Yeah, this is close to what I'd want, but the problem is that sqlx requires the `bundled` feature, and disabling that as a distributor of software is *hard*. They require the `bundled` feature, because the default compilation mode, that doesn't run bindgen during buildtime, has a too old sqlite version, so it's missing some features.

> I've also definitely been able to make `cc` work with cross compilation [...]

I personally don't know much about cross compilation of C libraries. Just that with rust, it's usually easy, until C comes in :D
If you care to take a look at the error the Void CI threw at me, it's available here: https://travis-ci.org/github/void-linux/void-packages/jobs/701745377#L772

> That said, I'm pretty sympathetic to the desire to not statically link, [... but]  I'm unsure when I'll have time to do anything around this myself. Probably not for another week or two.

That's good to hear. This is not that terribly urgent, I've just set the package that prompted this to nocross, which means it won't get cross compiled by Void Linux. That's a bit unfortunate, but should be fine for now.

> if you have a concrete idea I'd certainly take a look at a patch

The only problem with a (compile time) env var override would be that old versions might cause problems, right? The spike in compile times there is obviously to be expected, but for a distribution, that's a worthwhile trade off in my opinion.

**Comment by thomcc** [comment]
> It definitely has to be compile time, but the way the flag is passed doesn't have to be a feature flag. Having an environment variable during compile time that overrides the feature should work, no?

So long as you don't want to turn on buildtime-bindgen. For that it requires additional compile-time dependencies which `cargo` needs to know about, and the only way to tell `cargo` about additional deps is via `feature`s.

That said, it doesn't seem like you need this so should be doable.

> If you care to take a look at the error the Void CI threw at me, it's available here: travis-ci.org/github/void-linux/void-packages/jobs/701745377#L772

Can I get back to you here? This looks like a bug on our part (which might just end up with me filing an issue, but it might be easy to fix -- Cross compiling to aarch64 should be totally doable).

> This is not that terribly urgent... That's a bit unfortunate, but should be fine for now.

That's also good to hear on my part :). I agree it sounds unfortunate. I don't really want libsqlite3-sys to be a problematic dependency for devs or packagers (it's already a bit problematic for some, since I gather it doesn't work with things like https://github.com/google/cargo-raze, unfortunately).

> The only problem with a (compile time) env var override would be that old versions might cause problems, right

Hmmm, I guess that's basically it. It also might require a bit of rejiggering of the way libsqlite3-sys's build.rs is configured, but might not. In a week or two when my schedule frees up a little I can take a stab at this I guess.

> The spike in compile times there is obviously to be expected

If you're using a modern version of sqlite we could probably just let you use the pregenerated bindgen file and let you link against whatever, so there actually shouldn't be a compile time spike.

**Comment by jcgruenhage** [comment]
> So long as you don't want to turn on buildtime-bindgen. For that it requires additional compile-time dependencies which `cargo` needs to know about, and the only way to tell `cargo` about additional deps is via `feature`s.

You can definitely change features in build.rs, but I'm not sure whether that might be *after* cargo determined the dependencies for that build. If so, that would be quite unfortunate.

> Can I get back to you here? This looks like a bug on our part (which might just end up with me filing an issue, but it might be easy to fix -- Cross compiling to aarch64 should be totally doable).

Sure, I'll do my best to help. Also happy to hear that this helps with finding bugs.

> If you're using a modern version of sqlite we could probably just let you use the pregenerated bindgen file and let you link against whatever, so there actually shouldn't be a compile time spike.

That wouldn't work for sqlx though, as they require a higher minimum version than what the pregenerated bindgen file offers, right?

**Comment by thomcc** [comment]
> You can definitely change features in build.rs, but I'm not sure whether that might be after cargo determined the dependencies for that build. If so, that would be quite unfortunate.

Yes, it's after -- we need bindgen to compile the build.rs, but at the point when the build.rs is run, it's already been compiled.

I also don't know that it's correct that you can change features from within a build.rs, are you sure about that?

> That wouldn't work for sqlx though, as they require a higher minimum version than what the pregenerated bindgen file offers, right?

It would work. While we ship with bindings for a few old versions of sqlite, we also ship a binding file for the most recent version of sqlite: https://github.com/rusqlite/rusqlite/blob/master/libsqlite3-sys/sqlite3/bindgen_bundled_version.rs (well, I guess this is 3.32.2 now and there's been another patch release, but close enough).

Ideally there would be more middle ground here, or the old versions wouldn't be quite so old, but yeah, either way, you wouldn't need bindgen run at build time.

**Comment by jcgruenhage** [comment]
> Yes, it's after -- we need bindgen to compile the build.rs, but at the point when the build.rs is run, it's already been compiled.

Okay, then that won't work :/

> I also don't know that it's correct that you can change features from within a build.rs, are you sure about that?

You can set arbitrary `cfg` settings, so that should include features. It might break horribly if those features are used to gate dependencies though..

> [...] we also ship a binding file for the most recent version of sqlite [...]
> Ideally there would be more middle ground here, or the old versions wouldn't be quite so old, but yeah, either way, you wouldn't need bindgen run at build time.

That sounds good. @mehcode, would that work for sqlx?

**Comment by thomcc** [comment]
> That sounds good. @mehcode, would that work for sqlx?

To be clear, this would be used when the environment var is activated. It's the same binding file we use when `bundled` is used, which I believe is the current status for sqlx.

**Comment by dubiousjim** [comment]
> I personally don't know much about cross compilation of C libraries. Just that with rust, it's usually easy, until C comes in :D
> If you care to take a look at the error the Void CI threw at me, it's available here: https://travis-ci.org/github/void-linux/void-packages/jobs/701745377#L772

These lines seem strange:

> --- stdout
> ...
> TARGET = Some("x86_64-unknown-linux-gnu")
> ...
> HOST = Some("x86_64-unknown-linux-gnu")
> CC_x86_64-unknown-linux-gnu = None
> CC_x86_64_unknown_linux_gnu = None
> HOST_CC = None
> CC = Some("aarch64-linux-gnu-gcc")

If you're cross-compiling from x86_64 to aarch64, as your `HOST` and `CC` suggest, I'd expect you'd want `TARGET` to be `"aarch64-unknown-linux-gnu"`. So instead of saying `cargo BLAH BLAH` you should be saying `cargo BLAH BLAH --target=aarch64-unknown-linux-gnu`.

**Comment by dubiousjim** [comment]
Just in case this is relevant, note that [`TARGET` and `HOST` in their Rust usage != them in their GCC/autotools usages](https://github.com/lu-zero/autotools-rs/pull/19/files#diff-b4aea3e418ccdb71239b96952d9cddb6).

**Comment by jcgruenhage** [comment]
I'm not sure what's going on there, the target *should* be set to `aarch64-unknown-linux-gnu` from what I've seen in the xbps-src scripts. Also: The package doesn't modify this, so it's behaving exactly as all the other rust packages in Void, and it works there, so I doubt this is just fundamentally wrong.

**Comment by thomcc** [comment]
I think this is because of compiling the build.rs which happens on the host machine vs compiling the actual code, no?

**Comment by jcgruenhage** [comment]
Ah, right, so that should be correct then?

**Comment by thomcc** [comment]
```
running: "aarch64-linux-gnu-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-fstack-clash-protection" "-D_FORTIFY_SOURCE=2" "-O2" "-pipe" "-march=armv8-a" "-I/usr/aarch64-linux-gnu/usr/include" "-DSQLITE_CORE" "-DSQLITE_DEFAULT_FOREIGN_KEYS=1" "-DSQLITE_ENABLE_API_ARMOR" "-DSQLITE_ENABLE_COLUMN_METADATA" "-DSQLITE_ENABLE_DBSTAT_VTAB" "-DSQLITE_ENABLE_FTS3" "-DSQLITE_ENABLE_FTS3_PARENTHESIS" "-DSQLITE_ENABLE_FTS5" "-DSQLITE_ENABLE_JSON1" "-DSQLITE_ENABLE_LOAD_EXTENSION=1" "-DSQLITE_ENABLE_MEMORY_MANAGEMENT" "-DSQLITE_ENABLE_RTREE" "-DSQLITE_ENABLE_STAT2" "-DSQLITE_ENABLE_STAT4" "-DSQLITE_SOUNDEX" "-DSQLITE_THREADSAFE=1" "-DSQLITE_USE_URI" "-DHAVE_USLEEP=1" "-DSQLITE_HAVE_ISNAN" "-o" "/builddir/rumatui-0.1.16/target/release/build/libsqlite3-sys-44b11efcd12476f6/out/sqlite3/sqlite3.o" "-c" "sqlite3/sqlite3.c"

cargo:warning=aarch64-linux-gnu-gcc: error: unrecognized command line option '-m64'
```
This looks like the actual problem to me, but I haven't had time to look really.

**Comment by juho-p** [comment]
I had the error mentioned in previous message, but at least in my case it was due to misconfigured CC and CFLAGS environment variables. I think this is just because macros need to compile for HOST instead of TARGET.

I had
```
export CFLAGS="--sysroot=$SOME_SYSROOT"
export CC=$SOME_CROSS_CC
```
But I should have had specified TARGET variables instead:
```
export TARGET_CFLAGS="--sysroot=$SOME_SYSROOT"
export TARGET_CC=$SOME_CROSS_CC
```
as documented in `cc` crate documentation https://crates.io/crates/cc

In my case this helped, maybe this is helpful to someone.

**Comment by jcgruenhage** [comment]
Quick follow-up: Has anything happened on this here? I ran into this again, looked into it and seeing that I opened an issue about this years ago and that there's nothing happening is a bit frustrating, especially when seeing that this is also something others are running into as well (see https://github.com/launchbadge/sqlx/issues/191#issuecomment-1124962206)

**Comment by thomcc** [comment]
Sorry, not really, although I have been working on it some. My current plan is to make Cargo build script overrides work https://doc.rust-lang.org/cargo/reference/build-scripts.html#overriding-build-scripts. This will require a significant change to how bundling works, since this disables the `build.rs` entirely -- so we have to function even if it is not run. That said, doing this correctly will fix a number of other issues too around versioning, and enable more use cases.

Notably, this will allow complete control of the version of SQLite that we link with, even if the bundled feature is enabled. I have most of the work done in a branch locally (it works but it also broke a number of things I need to fix). I hope to have slightly more time for this after I finish finding a job, which is what a lot of my time is currently spent on this month.

**Comment by jcgruenhage** [comment]
This has been implemented in https://github.com/rusqlite/rusqlite/pull/1317 a while ago. Setting `LIBSQLITE3_SYS_USE_PKG_CONFIG=1` does the trick now.
