### ISSUE TITLE
rarray is not documented?

### ISSUE THREAD

**Issue by peku33** [rusqlite/rusqlite#781]
I am looking for a way to make a query
```
SELECT * FROM table WHERE index IN([list of values]);
```
passing list of values directly from rust Vec.

While it looks like there is a support for that here:
https://github.com/rusqlite/rusqlite/blob/master/src/vtab/array.rs#L51

There are no:
- documentation for array module in docs: https://docs.rs/rusqlite/0.23.1/rusqlite/trait.ToSql.html?search=array - empty searach
- no information about implementing ToSql for Array type: https://docs.rs/rusqlite/0.23.1/rusqlite/trait.ToSql.html
- no examples how to make even such simple query

**Comment by gwenn** [comment]
We may add `array` to [docs.rs features](https://github.com/rusqlite/rusqlite/blob/master/Cargo.toml#L143) ?

**Comment by peku33** [comment]
Any update on this?

**Comment by gwenn** [comment]
You just want it documented on docs.rs, right ?

**Comment by peku33** [comment]
Yes, exactly
