### ISSUE TITLE
addition of #[nonexhaustive] to IndexConstraintOp is a breaking change and makes it harder to keep in sync

### ISSUE THREAD

**Issue by jrandall** [rusqlite/rusqlite#783]
In our vtable implementations, we have code that matches on `IndexConstraintOp` to handle all possible operators. We implement all of them, but we are now getting an error from the compiler because the `#[non_exhaustive]` attribute has been added to the enum (in PR #673) so that we are now being forced to add a default pattern even though we handle all of the cases. 

We considered it a feature that every time another operator was added to rusqlite, we would have to handle it in our code (we chose not to have a default pattern match on purpose as we didn't want to miss any). It seems somewhat backward to force library consumers to have a default pattern match if they would prefer to be notified of and handle breaking changes.

If you took `#[non_exhaustive]` off of this enum, consumers who want to have a default pattern match would be free to add one if  they want to be protected from future changes to the enum, but they would also be free not to do that because they _want_ to know about changes and ensure they are handling every possible case. Sometimes a default pattern makes sense, but other times it doesn't -- it is a great feature of rust that we get to decide whether or not we want the compiler to enforce complete coverage of all possible patterns, and having the `#[non_exhaustive]` attribute set takes that option away.

In some cases, a default pattern really doesn't make sense and existing code has to change dramatically to implement it (i.e. by panicking or introducing error handling where none was previously required). 

In this case, we have code in our crate to go from `IndexConstraintOp` back to an opcode (I think this is so that we can serialize them into the vtable idx_str). It looked something like this as of rusqlite `0.21.0`:

```
let opcode: u8 = match index_constraint_op {
                IndexConstraintOp::SQLITE_INDEX_CONSTRAINT_EQ => 2,
                IndexConstraintOp::SQLITE_INDEX_CONSTRAINT_GT => 4,
                IndexConstraintOp::SQLITE_INDEX_CONSTRAINT_LE => 8,
                IndexConstraintOp::SQLITE_INDEX_CONSTRAINT_LT => 16,
                IndexConstraintOp::SQLITE_INDEX_CONSTRAINT_GE => 32,
                IndexConstraintOp::SQLITE_INDEX_CONSTRAINT_MATCH => 64,
                IndexConstraintOp::SQLITE_INDEX_CONSTRAINT_LIKE => 65,
                IndexConstraintOp::SQLITE_INDEX_CONSTRAINT_GLOB => 66,
                IndexConstraintOp::SQLITE_INDEX_CONSTRAINT_REGEXP => 67,
                IndexConstraintOp::SQLITE_INDEX_CONSTRAINT_NE => 68,
                IndexConstraintOp::SQLITE_INDEX_CONSTRAINT_ISNOT => 69,
                IndexConstraintOp::SQLITE_INDEX_CONSTRAINT_ISNOTNULL => 70,
                IndexConstraintOp::SQLITE_INDEX_CONSTRAINT_ISNULL => 71,
                IndexConstraintOp::SQLITE_INDEX_CONSTRAINT_IS => 72,                                                                                                                                       
                IndexConstraintOp::SQLITE_INDEX_CONSTRAINT_FUNCTION(v) => v,
};
```

The function this is cannot fail and so it does not return a `Result`, and we generally don't allow our library to panic after initialisation. What would rusqlite have us do here? 

I guess the choices are:
 - add something like `_ => 0` (i.e. invent a special opcode to represent "unknown" - but this won't have meaning to sqlite and is likely to cause confusion in the future if it ever happens).
 - add something like `_ => {panic!("Unimplemented IndexConstraintOp has been added to rusqlite");}` - making what should be a compile-time error into a run-time panic.
 - add error handling to the entire code path where this happens, even though it is actually infallible. (and also making what should be a compile-time error into a run-time error).

These don't seem like great options. Any chance the `#[non_exhaustive]` attribute can be removed?

**Comment by thomcc** [comment]
Hrmm... I mean, I'd really like to get to a place where every rusqlite release wasn't a breaking change.

That said, that does seem like it might be a ways off...

**Comment by thomcc** [comment]
Yeah, I thought more about this and I'm sympathetic to this. I suspect rusqlite will likely not get to 1.0 (e.g. a stable releases that is unlikely to have many further changes) any time soon, although I guess if we decide we want to try to do that we could split the vtab code into a rusqlite-vtab crate or something.

Either way I'd take a patch for this or will try to do it if I remember before the next release.
