### ISSUE TITLE
Data change notifications

### ISSUE THREAD

**Issue by brettkelf** [rusqlite/rusqlite#784]
I was thinking about writing a rust program to control my swimming pool valves based on the data in an sqlite database.  Another process running on the same machine would serve webpages and change the sqlite database, and then when the aforementioned control program written in rust gets notified of a data change or when it is time for the next valve change it can update the gpio pins on the raspberry pi.  This architecture has some nice fault tolerance properties. 
 So the ideal solution would be to be able to make a rust call to this update hook function which is part of the sqlite C API but I didn't see it in rusqlite: https://www.sqlite.org/c3ref/update_hook.html.  (even if I should just call the C function directly I would appreciate any advice)

**Comment by gwenn** [comment]
https://github.com/rusqlite/rusqlite/blob/master/src/hooks.rs#L71 ?

**Comment by brettkelf** [comment]
Awesome thank you

**Comment by ratulb** [comment]
I have been trying to listen to database update notifications by attaching a update hook on to the connection and push back the notification summary back to the database(another table) on the same connection. This does not work. Used another connection wrapping in Arc<Mutex<Connection>>> - that does not work either. 

Tried to get the notifications via a channel - that does work to. I run into memory issues.

(signal: 11, SIGSEGV: invalid memory reference).
