### ISSUE TITLE
Question: implementation of a generic function that takes result from query_map directly

### ISSUE THREAD

**Issue by Rudo2204** [rusqlite/rusqlite#791]
Right now I have to write something similar to the [doc example](https://docs.rs/rusqlite/0.23.1/rusqlite/struct.Statement.html#example-4) which is to create an empty Vec, iterate `rows`, push `foo` into that vec, return it so I can finally use it to do stuff in my function.
```rust
    let mut names = Vec::new();
    for name_result in rows {
        names.push(name_result?);
    }
```
How can I implement a function directly takes the result of query_map and iterate it instead of writing `for foo in rows` everywhere like this?
Edit: typos

**Comment by gwenn** [comment]
See #642 and #756.
https://docs.rs/rusqlite/0.23.1/rusqlite/struct.Rows.html => FallibleStreamingIterator // only `while let` loop supported
https://docs.rs/rusqlite/0.23.1/rusqlite/struct.Rows.html#method.map => FallibleStreamingIterator // only `while let` loop supported
https://docs.rs/rusqlite/0.23.1/rusqlite/struct.Rows.html#method.mapped => Iterator // `for in` supported
https://docs.rs/rusqlite/0.23.1/rusqlite/struct.Rows.html#method.and_then => Iterator // `for in` possible

So you can use a `while` loop on `rows` directly ([FallibleStreamingIterator](https://docs.rs/fallible-streaming-iterator/0.1.9/fallible_streaming_iterator/index.html)).
> While these iterators cannot be used with Rust `for` loops, `while let` loops offer a similar level of ergonomics

Or you must first apply a function on `rows` before iterating with a `for in` loop.

**Comment by Rudo2204** [comment]
So it seems like there is no easy way to implement this. Thanks for answering my question! Closing.
