### ISSUE TITLE
pragma_update fails with ExecuteReturnedResults

### ISSUE THREAD

**Issue by dae** [rusqlite/rusqlite#792]
The following code works on 0.23.1, but fails in current master. Was this an unintended change, or should I change my existing code to use pragma_update_and_check()?

```rust
use rusqlite;

fn main() {
    let db = rusqlite::Connection::open_in_memory().unwrap();
    db.pragma_update(None, "locking_mode", &"exclusive")
        .unwrap();
}
```

**Comment by dae** [comment]
The behaviour changed in f37519ad513e8afa9cd10ff75ac8f6ad670c6ff7

**Comment by gwenn** [comment]
You should use `pragma_update_and_check`.
But we should fail only when `extra_check` feature is activated.

**Comment by gwenn** [comment]
See #794

**Comment by dae** [comment]
cheers
