### ISSUE TITLE
Consider making Row::stmt public

### ISSUE THREAD

**Issue by Timmmm** [rusqlite/rusqlite#802]
My motivation is that I want to provide a `Row::get_u64()` method that casts `i64` to `u64`:

```
use rusqlite::{Row, Result, RowIndex};
use std::convert::TryInto;

trait GetU64 {
  fn get_u64<I: RowIndex>(&self, idx: I) -> Result<u64>;
}

impl GetU64 for Row<'_> {
  fn get_u64<I: RowIndex>(&self, idx: I) -> Result<u64> {
    self.get::<_, i64>(idx).and_then(|s| {
      s.try_into().map_err(|_try_from_err| {
        // Unfortunately I can't see a way to get the column index since self.stmt is private.
        rusqlite::Error::IntegralValueOutOfRange(666, s)
      })
    })
  }
}
```

I would like to do 

        let idx = idx.idx(self.stmt)?;
        rusqlite::Error::IntegralValueOutOfRange(idx, s)

But `stmt` is private and I can't see any way around that (other than maybe passing it into `get_u64` which would suck.

Maybe also rename to `statement` since public types should probably not be abbreviated! (Or add a `fn statement() -> &Statement` method).

**Comment by thomcc** [comment]
I think we should just impl FromSql for u64, would that work?

I remember during my security audit some potential soundness issues if you could retrieve the statement and operate on it while a Row was still active (this has to do with the interior mutability).

**Comment by Timmmm** [comment]
Yeah that would work but there is [a comment saying it is intentionally not implemented](https://github.com/rusqlite/rusqlite/blob/master/src/types/from_sql.rs#L79). How would you handle values outside `i64`?

**Comment by thomcc** [comment]
`FromSqlError::OutOfRange`?

**Comment by Timmmm** [comment]
Yeah that seems reasonable to me. I guess it's worth checking with whoever wrote that comment why they didn't do that.
