### ISSUE TITLE
Expose progress information

### ISSUE THREAD

**Issue by pixelspark** [rusqlite/rusqlite#803]
I am using rusqlite's `execute_batch` to run database scripts. As these scripts may take a long time to complete (and sometimes lead to errors) I would like to know the current query that is executing, and possibly progress for each query. 

It would be easy to reimplement `execute_batch` myself, except for the fact that the private statement struct (`stmt`) is not accessible, which means I am unable to parse multiple statements:

````
pub fn execute_batch(&self, sql: &str) -> Result<()> {
        let mut sql = sql;
        while !sql.is_empty() {
            let stmt = self.prepare(sql)?;
            if !stmt.stmt.is_null() && stmt.step()? && cfg!(feature = "extra_check") {
                // Some PRAGMA may return rows
                return Err(Error::ExecuteReturnedResults);
            }
            let tail = stmt.stmt.tail();
            if tail == 0 || tail >= sql.len() {
                break;
            }
            sql = &sql[tail..];
        }
        Ok(())
    }
````

A solution would be to provide access to (parts of) the `RawStatement` functionality. Another solution would be to add an interface to perform the parsing (and return a `Vec<String>` or `Vec<Statement>`), after which I can execute the statements one-at-a-time myself.

To obtain progress information for an individual statement, one could use [`sqlite3_progress_handler`](https://www.sqlite.org/c3ref/progress_handler.html) which is not currently exposed either.

**Comment by gwenn** [comment]
Like https://docs.oracle.com/javase/8/docs/api/java/sql/Statement.html#getMoreResults-- ?
=> `Iterator<Statement>`

**Comment by gwenn** [comment]
I guess we need an `FnMut`:
```rust
    pub fn progress_handler<P>(
        &self,
        n: c_int,
        x_handler: P,
    ) -> Result<()>
    where
        P: FnMut() -> Result<bool> + Send + UnwindSafe + 'static
```
And an enum (`Continue` or `Interrupt`) instead of `bool` ?

**Comment by thomcc** [comment]
Reentrancy concerns here worry me, although it's probably no worse than those around create_function...
