### ISSUE TITLE
How do I print a complete SQL statement?

### ISSUE THREAD

**Issue by sniperZj** [rusqlite/rusqlite#805]

**Comment by sniperZj** [comment]
I know the
https://docs.rs/rusqlite/0.24.0/rusqlite/struct.Statement.html#method.expanded_sql

**Comment by gwenn** [comment]
Should we consider this issue as solved ?
Or would you mind explaining why `sqlite3_expanded_sql` does not fit ?

**Comment by sniperZj** [comment]
@gwenn Thank you， It's settled。
