### ISSUE TITLE
Consider moving away from the lru-cache dependency

### ISSUE THREAD

**Issue by myfreeweb** [rusqlite/rusqlite#810]
[lru-cache](https://github.com/contain-rs/lru-cache) is a project "IN MAINTENANCE MODE, DUE TO INSUFFICIENT MAINTAINER RESOURCES" which depends on [linked-hash-map](https://github.com/contain-rs/linked-hash-map), another project "IN MAINTENANCE MODE …" and with [undefined behavior issues](https://github.com/contain-rs/linked-hash-map/issues/97) that are now **[caught by the stdlib assertions](https://github.com/rust-lang/rust/issues/77585)** in nightly Rust, which makes Firefox built with nightly Rust crash.

It's probably possible to fix lru-cache by switching to [hashlink](https://github.com/kyren/hashlink), but maybe switching to a more actively maintained LRU cache library in rusqlite would be a good idea.

**Comment by RalfJung** [comment]
linked-hash-map has a fix released since May, so if you use the latest version (v0.5.3) there should be no assertions.

That said, it probably still makes sense to switch away from unmaintained crates.

**Comment by thomcc** [comment]
Yeah, I thought this was the case, since I followed this a little (but only loosely).

That said, I've thought about moving us to hashlink for a bit, since it would clean up our handling of the cache keys, I think. (OTOH it is on the heavy side, compared to lru-cache...)
