### ISSUE TITLE
Build fails on windows

### ISSUE THREAD

**Issue by m9xiuz** [rusqlite/rusqlite#817]
```
[dependencies.rusqlite]
version = "0.24.1"
features = ["bundled"]
```

```
"cl.exe" did not
 execute successfully (status code exit code: 2).
```

**Comment by m9xiuz** [comment]
After installing
The Windows SDK version 10.0.17763.0 
from https://developer.microsoft.com/en-us/windows/downloads/sdk-archive/
everything is ok.

**Comment by IamRezaMousavi** [comment]
You must have `gcc` (mingw-w64) and enable `x86_64-pc-windows-gnu`
