### ISSUE TITLE
Can you provide a configuration to enable the console to output the currently executed SQL?

### ISSUE THREAD

**Issue by sniperZj** [rusqlite/rusqlite#818]
expanded_sql  Don't apply。

**Comment by sniperZj** [comment]
I am a beginner, please include more。😺

**Comment by gwenn** [comment]
See [Connection::trace](https://docs.rs/rusqlite/0.24.1/rusqlite/struct.Connection.html#method.trace).
Which uses [sqlite3_trace](https://sqlite.org/c3ref/profile.html).

**Comment by sniperZj** [comment]
@gwenn thank you
