### ISSUE TITLE
Is SQL injection prevented?

### ISSUE THREAD

**Issue by swapsCAPS** [rusqlite/rusqlite#820]
Is SQL injection prevented by using `params![]`?
Sorry for n00b question but really new to SQL and rust :grimacing:

**Comment by gwenn** [comment]
Only if the SQL is not arbitrary (i.e. only the parameters are arbitrary).

**Comment by thomcc** [comment]
That is to say, yes, `params![]` (and `named_params!{}`) prevents SQL injection, but there are still ways you can shoot yourself in the foot (using the result of `&format!` as your SQL string).

**Comment by swapsCAPS** [comment]
Thanks for your quick response! That's reassuring.
I was trying to follow the `conn.execute()` code a bit, but could not find anything. Would definitely like to know more. Wouldn't mind getting a nudge in the right direction :grin: 
Big thanks for the lib! ❤

**Comment by gwenn** [comment]
`rusqlite` expects that `sqlite` prevents SQL injection (`rusqlite` is just a wrapper).
Except [here](https://github.com/rusqlite/rusqlite/blob/master/src/pragma.rs#L138) for PRAGMA because some PRAGMA uses parameters but SQLite does not support placeholder for all of them.
