### ISSUE TITLE
Implement ToSql/FromSql for u64

### ISSUE THREAD

**Issue by Timmmm** [rusqlite/rusqlite#821]
As discussed in #802 it is pretty awkward that `ToSql` and `FromSql` are not implemented for `u64`. The current justification is that SQLite cannot actually store integers between `i64::MAX` and `u64::MAX`, but it would be simpler just to return an error in that case (`FromSqlError::OutOfRange`, or is it `Error::IntegralValueOutOfRange`, or possibly `Error::FromSqlConversionFailure`?).

**Comment by thomcc** [comment]
Whatever is done here should be done for usize too. Patches welcome, I don't think the specific error message matters that much for ToSql, but however we handle out of range for FromSql on other integers should be respected for that one.
