### ISSUE TITLE
Implement ToSql/FromSql for f32

### ISSUE THREAD

**Issue by Timmmm** [rusqlite/rusqlite#822]
This just seems to be an oversight.

**Comment by gwenn** [comment]
https://github.com/rusqlite/rusqlite/issues/209#issuecomment-274346049

**Comment by Timmmm** [comment]
> Implementing FromSql for f32 would force us to provide a FromSql that was losing precision from the values we get from SQLite.

Yeah that's exactly the behaviour I'd expect. Also that only applies to `FromSql`, not `ToSql`. Maybe this task should be split up.

**Comment by david-bouyssie** [comment]
Sorry I don't get it. It seems to be merged, but f32 doesn't appear in latest version of the crate:
https://docs.rs/rusqlite/0.24.2/rusqlite/types/trait.FromSql.html

What's going wrong?

**Comment by thomcc** [comment]
A release hasn't been cut yet, although it should be in the near future.

**Comment by david-bouyssie** [comment]
Ok, thank you!
