### ISSUE TITLE
Use #[doc(cfg)] instead of manually indicating `feature = "blah"` in the comments

### ISSUE THREAD

**Issue by thomcc** [rusqlite/rusqlite#835]
Apparently there's a way to do this. Not exactly sure on the details, though... It's unstable, so maybe we'd need to work around that somehow too...

**Comment by gwenn** [comment]
See https://github.com/time-rs/time/search?q=__time_03_docs

**Comment by thomcc** [comment]
I think I'd rather wait till it's stabilized.

**Comment by thomcc** [comment]
That said: I don't feel that strongly. If you want to replace it everywhere, that's fine. I just think we'll have to do it again later, to change `#[cfg_attr(docsrs, doc(cfg))]` into `#[doc(cfg)]`

**Comment by gwenn** [comment]
Version 0.26.0 released
