### ISSUE TITLE
Request to add `insert_named` to the library.

### ISSUE THREAD

**Issue by selendym** [rusqlite/rusqlite#836]
Hello.

Any chance of getting `insert_named` added to the library for the sake of consistency?
Unless I've missed something, it would be as trivial as adding the following to `statement.rs`:
```rust
pub fn insert_named(&mut self, params: &[(&str, &dyn ToSql)]) -> Result<i64>
{
    let changes = self.execute_named(params)?;
    match changes {
        1 => Ok(self.conn.last_insert_rowid()),
        _ => Err(Error::StatementChangedRows(changes)),
    }
}
```

**Comment by gwenn** [comment]
Should already be solved in master branch (see #830).
