### ISSUE TITLE
How to raise an Rusqlite Error manually?

### ISSUE THREAD

**Issue by fusion2222** [rusqlite/rusqlite#843]
When inside `query_map` function, and I do some custom handling, I must raise `Rusqlite` error. Long hours of googling did not helped me... How can I raise any Rusqlite error manually? Looks like all errors provided are only for internal usage of `rusqlite`. Any thoughts? 

In my case below I would like throw `DataCorruption` error something similar.

**Example Code:**
```rust
let name = "Rob";
let mut stmt = conn.prepare("SELECT * FROM logs WHERE name = ?")?;

let mapped_results = stmt.query_map(
    params![name],  |row| {
            let id = row.get(row.column_index("id")?)?;
            let name = row.get(row.column_index("name")?)?;
            let raw_method: String = row.get(row.column_index("method")?)?;
            let http_method = Method::from_str(&raw_method).map_err(  // hyper's Method
                // Fails here... I need to throw Rusqlite Error manually, so query_map can catch it!
                |e| Error::new(e.to_string()) 
            )?;
                                
            Ok( HttpLog { id: id, http_method: http_method, name: name })
        }
    );
```

**Comment by gwenn** [comment]
You should be able to build a custom [FromSqlError](https://docs.rs/rusqlite/0.24.1/rusqlite/types/enum.FromSqlError.html#variant.Other) which can be auto-converted to an [Error](https://docs.rs/rusqlite/0.24.1/rusqlite/enum.Error.html).
Or you should be able to build an [Error](https://docs.rs/rusqlite/0.24.1/rusqlite/enum.Error.html#variant.FromSqlConversionFailure) directly.
You should not use [SqliteFailure](https://docs.rs/rusqlite/0.24.1/rusqlite/enum.Error.html#variant.SqliteFailure) (and [SQLITE_CORRUPT](https://docs.rs/libsqlite3-sys/0.20.1/libsqlite3_sys/constant.SQLITE_CORRUPT.html)) to keep a clear distinction between your application and SQLite core.

**Comment by fusion2222** [comment]
Thanks for explanation. That answers my question 🥇
