### ISSUE TITLE
Returning custom errors from `query_map` or `query_row`

### ISSUE THREAD

**Issue by Timmmm** [rusqlite/rusqlite#846]
The functions passed to `query_map` and `query_row` are required to return `rusqlite::Error`. This means if you do some stuff inside that function that might fail you have to map your error to `rusqlite::Error`. Unfortunately sometimes there's no obvious choice. It would be helpful if there were a `UserDefinedError` variant:

        UserDefinedError(Box<dyn error::Error + Send + Sync + 'static>),

**Comment by gwenn** [comment]
See [FromSqlError::Other](https://docs.rs/rusqlite/0.24.1/rusqlite/types/enum.FromSqlError.html#variant.Other) if you don't care to report which column / type causes an error.
Or [Error::FromSqlConversionFailure](https://docs.rs/rusqlite/0.24.1/rusqlite/enum.Error.html#variant.FromSqlConversionFailure).
And https://github.com/rusqlite/rusqlite/issues/843#issuecomment-726922999

**Comment by Timmmm** [comment]
But isn't `FromSqlError` the error type for converting SQL types into Rust types? What if my error isn't anything like that? And similarly `FromSqlConversionFailure` requires a column name and type which doesn't apply in all cases.

Ahh hmm it looks like you just set the column to `UNKNOWN_COLUMN` and the data type to `NULL`. I guess that's reasonable. Still something more obvious would be nice. If there were a proper `UserDefinedError` variant then you could also `impl std::convert::From` from normal errors.

**Comment by thomcc** [comment]
You likely want to use query_and_then and not query_map.

**Comment by Timmmm** [comment]
Ah that looks right. Why have both? Is `query_map` just so that you don't lose the error type if you are happy with `rusqlite::Result`?

Definitely worth clarifying that and linking them from each other in the docs!

**Comment by thomcc** [comment]
> Why have both? Is `query_map` just so that you don't lose the error type if you are happy with `rusqlite::Result`?

Yes. Often a user just wants to do a few `get()` calls inside the query_map in order to populate a struct or tuple.

> Definitely worth clarifying that and linking them from each other in the docs!

Patches welcome, as always.
