### ISSUE TITLE
Typos on Row doc comments

### ISSUE THREAD

**Issue by dubiousjim** [rusqlite/rusqlite#863]
Comments say "will be better served by `get` or `get`"... should one of those be `get_unwrap`?

* [line 306](https://github.com/rusqlite/rusqlite/blob/0a2e0b7240e42d1427936be397e139f599650cc0/src/row.rs#L306)
* [line 330](https://github.com/rusqlite/rusqlite/blob/0a2e0b7240e42d1427936be397e139f599650cc0/src/row.rs#L330)

**Comment by gwenn** [comment]
Already spotted here https://github.com/rusqlite/rusqlite/pull/838/files#diff-24d3b409cbfcdaa05a38a56d2f5b4b480b6cb89bc9015002f643f5b7768288b8
But a dedicated PR is welcome because PR #838 is the potential cause of too many troubles...

**Comment by dubiousjim** [comment]
Oh #838 sounds like a good idea to me.

**Comment by gwenn** [comment]
Should be fixed by version 0.25.0
