### ISSUE TITLE
Aggregate Function API: Expose Context in both init and finish function

### ISSUE THREAD

**Issue by phiresky** [rusqlite/rusqlite#865]
The rusqlite::functions::Aggregate<> interface adds a init() function that is not present in pure sqlite. This is nice because it means you can handle the initialisation of the user context separately from the step function. 

However, in practice this does not work that well since the init function is not passed the `sqlite3_context` so it can't create the state based on the function parameters or aux data. At least for me it just means I have to wrap stuff in more Option<>s and save a handle to the context myself: https://github.com/phiresky/sqlite-zstd/blob/aeb5466d97f23439e143dfb44b9af46859b7c2ff/src/dict_training.rs#L30

For the init function this is easy to fix:

https://github.com/phiresky/rusqlite/commit/5a2200e24d9ce6050235954ee87a7ee525c231e8

For the finish function it's somewhat unclear what the best move is, since the rusqlite context also has the args, which are not passed to the finish function. There's two possibilities here:

1. Set args to empty vec in the context passed to finish function and document that (or throw)
2. Separate the args from the context object (somewhat cleaner, but more complex and breaking)

I'll make a PR for both, but it would be good to get feedback first.

**Comment by gwenn** [comment]
Please, do a PR with your `init` function fix.
Thanks.
