### ISSUE TITLE
Support for WITH RECURSIVE

### ISSUE THREAD

**Issue by adaszek** [rusqlite/rusqlite#874]
Hi,

I try implement this: https://www.db-fiddle.com/f/2m1gLW3tRHEgyzwkLoYFhT/7 with rusqlite.
It's about transforming csv data into tree with SQL. The idea is described here: https://stackoverflow.com/a/22376973. 

The problem is that it works on db-fiddle, but not in my rust code :). The code just prints the list of columns in tree_search, like it's empty table.

Here is the minimum implementation and test csv file:
https://gist.github.com/adaszek/4a48bd14bd26cf8f9c058030a2f00af9

Does rusqlite supports WITH RECURSIVE, at all?

**Comment by thomcc** [comment]
Yes: https://github.com/mozilla/application-services/blob/2ea35a574dd7157d71f3c53221a5f1fbc8d14c12/components/places/src/storage/bookmarks.rs#L661

**Comment by gwenn** [comment]
I am not sure you can define [table constraints](https://gist.github.com/adaszek/4a48bd14bd26cf8f9c058030a2f00af9#file-main-rs-L25-L27) on a virtual table.

**Comment by adaszek** [comment]
Ok, definitely it's not an issue with rusqlite.

First of all, by mistake, I used different data for testing - ROOT node was missing so obviously table was empty. Now I'm trying to resolve an issue with sqlite interpreting empty strings as strings not NULLs and UPDATE doesn't work on on temporary virtual table created while reading CSV file.
