### ISSUE TITLE
Named params not working with strings in queries

### ISSUE THREAD

**Issue by ageofabenius** [rusqlite/rusqlite#875]
Preparing a statement from this:

```
SELECT * FROM tablename WHERE labels LIKE '%:param%'
```

And then calling `Statement.query_named(<named params>)` does not appear to be correctly parsing `'%:param%'`.  It appears to be ignoring everything within the single quotes when replacing parameters with the named params.

**Comment by ageofabenius** [comment]
It looks like this is actually an issue with the underlying SQLite C function sqlite3_bind_parameter_index().  I suppose there's also room for debate on whether or not this is a bug or intended.  If this is intended, then what is the solution in rusql to bind a named parameter to something within quotes?

**Comment by thomcc** [comment]
Yeah, this is intended behavior. You could make the :param be `format!("%{}%", thing)` and then use `SELECT * FROM tablename WHERE like(labels, :param)` also (I dont remember if you can use the operator on a non-string literal).

Note that I vaguely remember some security concerns around using LIKE like this, but I think it might just be denial-of-service related.

**Comment by ageofabenius** [comment]
Ah, this makes sense.  The point of binding the parameter is to define it entirely somewhere else, not plop it in the middle of an expression it's mean to be a part of.

Thanks for your help, I'll close this issue.

**Comment by ageofabenius** [comment]
Note - Using `WHERE LIKE(labels, :param)` with `format!("%{}%", thing)` doesn't seem to work.  However using `WHERE labels LIKE :param` ith it does.

**Comment by thomcc** [comment]
Glad you found something that works, but it's weird that like as a function didn't: https://sqlite.org/lang_corefunc.html#like

**Comment by ageofabenius** [comment]
Looks like with the `WHERE LIKE(labels, :param)` format it treats the `%` as string literals.

**Comment by thomcc** [comment]
Oh, I see the issue, it should be `LIKE(:params, labels)`.
