### ISSUE TITLE
DateTime ToSql format is not compatible with sqlite date format

### ISSUE THREAD

**Issue by nosense-cz** [rusqlite/rusqlite#885]
Sqlite supports following DateTime formats:

    TEXT as ISO8601 strings ("YYYY-MM-DD HH:MM:SS.SSS").
    REAL as Julian day numbers, the number of days since noon in Greenwich on November 24, 4714 B.C. according to the proleptic Gregorian calendar.
    INTEGER as Unix Time, the number of seconds since 1970-01-01 00:00:00 UTC. 

rusqlite uses RFC3339 timestamp ("YYYY-MM-DDTHH:MM:SS.SSS+00:00") which is not compatible with the sqlite format. 

Here is an example where the incompatible formating causes problem.
```
use rusqlite;
use chrono::prelude::*;

#[cfg(test)]
mod tests {
    use super::*;
    
    #[test]
    fn check_datetime_select() {
        let db_conn = rusqlite::Connection::open_in_memory().unwrap();
        let start_date = Utc::now();
        let test_date = start_date + chrono::Duration::seconds(15);
        db_conn.execute(" CREATE TABLE test_table (ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP);",  rusqlite::NO_PARAMS).unwrap();
        for _ in 0..30 {
            //db_conn.execute("INSERT INTO test_table (ts) VALUES (?1);",  rusqlite::params![start_date + chrono::Duration::hours(i)]).unwrap();
            db_conn.execute("INSERT into test_table default values;",  rusqlite::params![]).unwrap();
            std::thread::sleep(std::time::Duration::from_secs(1));
        }
        
        let mut statenent = db_conn.prepare("SELECT ts FROM test_table").unwrap();
        let res_iter = statenent.query_map (rusqlite::params![], |row| {
            let date_db : DateTime<Utc> = row.get(0).unwrap();
            //println!("{}", date_db);
            Ok( date_db )
        }).unwrap();
        let all: Vec<DateTime<Utc>> = res_iter.map(|itm| {itm.unwrap()}).collect();

        //let mut statenent = db_conn.prepare("SELECT ts FROM test_table").unwrap();
        let mut statenent = db_conn.prepare("SELECT ts FROM test_table where ts > ?1;").unwrap();
        let res_iter = statenent.query_map (rusqlite::params![test_date], |row| {
            let date_db : DateTime<Utc> = row.get(0).unwrap();
            //println!("{}", date_db);
            Ok( date_db )
        }).unwrap();
        let res: Vec<DateTime<Utc>> = res_iter.map(|itm| {itm.unwrap()}).collect();
        if res.len() < 10 || res.len() > 20 {
            println!("All {:?}", all);
            println!("ts > {}: {:?}", test_date, res);
            panic!("Selection using DateTime<Utc> doens't work")
        }
    }
}

```

**Comment by gwenn** [comment]
Expanded SQL is:
```sql
SELECT ts FROM test_table WHERE ts > '2021-01-28T17:47:23.556940+00:00';
```
Should be without 'T':
```sql
SELECT ts FROM test_table WHERE ts > '2021-01-28 17:47:23.556940+00:00';
```

**Comment by gwenn** [comment]
Ok, `CURRENT_TIMESTAMP` format is '%Y-%m-%d %H:%M:%S' UTC.
But `DateTime<Utc>` format is 'YYYY-MM-DDTHH:MM:SS.SSS+00:00'.
A quick fix is:
```sql
SELECT ts FROM test_table where datetime(ts) > datetime(?1);
```

**Comment by gwenn** [comment]
And you are listing only 3 formats among the 12 formats supported (which don't include formats with timezone):
https://sqlite.org/lang_datefunc.html#time_values

**Comment by gwenn** [comment]
For reference,
https://github.com/launchbadge/sqlx/blob/v0.4.2/sqlx-core/src/sqlite/types/chrono.rs#L61

**Comment by nosense-cz** [comment]
I am not expert in sqlite. So excuse me if I am wrong. In the original post I was reffering to chapter 2.2 of https://www.sqlite.org/datatype3.html. The 12 formats from https://sqlite.org/lang_datefunc.html#time_values can be used as input for sqlite's datetime functions. But the output is always in "YYYY-MM-DD HH:MM:SS.SSS" format. Also the datetime values have to be stored using the same format - to work properly with sqlite's datetime functions and also to assure compatibility with other sqlite clients. For example pysqlite in my case.

**Comment by gwenn** [comment]
See #886.
