### ISSUE TITLE
Add last_insert_rowid to Statement

### ISSUE THREAD

**Issue by malaire** [rusqlite/rusqlite#899]
Currently when wrapping `Statement` for custom API, there is no way to call `last_insert_rowid`, except by also including related `Connection` in the wrapper. Adding `last_insert_rowid` to `Statement` would make this more convenient.

**Comment by gwenn** [comment]
You should use [RETURNING](https://sqlite.org/lang_returning.html)

**Comment by malaire** [comment]
> You should use [RETURNING](https://sqlite.org/lang_returning.html)

Documentation of `RETURNING` doesn't mention anything related to `last_insert_rowid`. How would I use `RETURNING` to get `last_insert_rowid` ?

**Comment by gwenn** [comment]
https://stackoverflow.com/a/72842340/21836177
