### ISSUE TITLE
Unable to create any sort of writeable Module

### ISSUE THREAD

**Issue by LikeLakers2** [rusqlite/rusqlite#900]
Hi, I was looking at the virtual tables module of rusqlite. While the tools provided seem very useful, everything within the module seems to only serve the purposes of making a read-only module -- writeable modules are out of the question unless I directly use the FFI interface.

Are there any plans to allow read-and-write modules? Or is rusqlite staying with just read-only modules for the time being?

**Comment by gwenn** [comment]
As far as I know, there is no plan to implement writable vtab.
And we still miss some features on read-only vtab (see #639).

**Comment by gwenn** [comment]
Version 0.28.0 released.
