### ISSUE TITLE
Allow converting row data from any type into string

### ISSUE THREAD

**Issue by benco-chan** [rusqlite/rusqlite#905]
Hello `rusqlite` Developers,

SQLite is easy on data types ([link](https://www.sqlite.org/datatype3.html)):

> In order to maximize compatibility between SQLite and other database engines, and so that the example above will work on SQLite as it does on other SQL database engines, SQLite supports the concept of "type affinity" on columns. The type affinity of a column is the recommended type for data stored in that column. The important idea here is that the type is recommended, not required. Any column can still store any type of data. It is just that some columns, given the choice, will prefer to use one storage class over another. The preferred storage class for a column is called its "affinity".

In my case, I have an old database with one `NUMERIC` column, but it has texts in there. Using command line program `sqlite3`, I can extract texts from that column, without any problem.

But using `rusqlite 0.24`, it failed.

Would you please consider adding ability to get and convert any data into string?

Thank you,

**Comment by gwenn** [comment]
As fas as I know, `rusqlite` does not use [type affinity / declared type](http://sqlite.org/c3ref/column_decltype.html) but only [sqlite3_column_type](http://sqlite.org/c3ref/column_blob.html) to extract data.
> But using rusqlite 0.24, it failed.

Could you please provide a minimal example ?

> Would you please consider adding ability to get and convert any data into string?

You can already do it yourself by extracting either a [Value](https://docs.rs/rusqlite/0.24.2/rusqlite/types/enum.Value.html) or a [ValueRef](https://docs.rs/rusqlite/0.24.2/rusqlite/types/enum.ValueRef.html). And then you decide how to convert these values into string (just be careful with Blob).

Regards.

**Comment by gwenn** [comment]
Partially related to #605

**Comment by benco-chan** [comment]
I'm sorry I didn't verify my code before submitting this issue. Actually the problem is:

- Column type is `NUMERIC`.
- First row is some text -> calling `Row::get::<_, String>()` succeeds.
- Second row is some text -> calling `Row::get::<_, String>()` succeeds.
- Third row is an actual number, now calling `Row::get::<_, String>()` fails.

I understand that the content is wrong. But I inherit it from other developer  :-(

This code compiles, but fails when you run it:

```rust
use {
    rusqlite::{NO_PARAMS, Connection},
};

const SQL: &str = r#"
    begin transaction;

    create table tests (db numeric);
    insert into tests (db) values ('sqlite'), ('maria-db'), (0);

    commit;
"#;

fn main() -> rusqlite::Result<()> {
    let conn = Connection::open_in_memory()?;
    conn.execute_batch(SQL)?;

    let mut statement = conn.prepare("select db from tests;")?;
    for row in statement.query_map(NO_PARAMS, |r| r.get::<_, String>(0))? {
        println!("{}", row?);
    }

    Ok(())
}
```

Dependency is simply: `rusqlite = '0.24'`

**Comment by gwenn** [comment]
Ok,
Just replace `r.get::<_, String>(0)` by `r.get::<_, Value>(0)` and implement your own conversion logic from `Value` to `String`.

**Comment by benco-chan** [comment]
Thank you very much, that solves my problem  :-)
