### ISSUE TITLE
named_params! ToSql not implemented for (&str, &dyn ToSql)

### ISSUE THREAD

**Issue by ankhers** [rusqlite/rusqlite#906]
I have the following code

```rust
conn.execute(
  "INSERT INTO foo (bar, baz) VALUES (:bar, :baz)",
  rusqlite::named_params! { ":bar": bar, ":baz": baz }
)?;
```

and I get the following compilation error

> the trait `ToSql` is not implemented for `(&str, &dyn ToSql)`

**Comment by gwenn** [comment]
Which `rusqlite` version ?
See https://github.com/rusqlite/rusqlite/pull/830

**Comment by ankhers** [comment]
Sorry, latest version, 0.24.2

**Comment by gwenn** [comment]
So you can't use `execute` yet, only `execute_named`...

**Comment by ankhers** [comment]
I'm not sure how I missed that. Thank you!
