### ISSUE TITLE
SQLite 3.35.0

### ISSUE THREAD

**Issue by trevyn** [rusqlite/rusqlite#916]
SQLite 3.35.0 is [targeted for release around March 30th](https://sqlite.org/forum/forumpost/bd047d7107), and a beta release and [release notes](https://sqlite.org/draft/releaselog/3_35_0.html) are now available. (Personally, I'm looking forward to `ALTER TABLE DROP COLUMN`!)

@thomcc @gwenn I'm not sure if you have a process or checklist for doing `libsqlite3-sys` bundled version upgrades and testing, but I'm available to help with any necessary unglamorous work.

**Comment by trevyn** [comment]
Aaaaand they released it early.

**Comment by gwenn** [comment]
(0) Checkout this repository on a linux (virtual) machine with curl, unzip, clang, cargo, rustfmt installed
(1) Edit https://github.com/rusqlite/rusqlite/blob/master/libsqlite3-sys/upgrade.sh (like this https://github.com/rusqlite/rusqlite/pull/917/files?file-filters%5B%5D=.sh#diff-3f9e208e2bcf2810ceefec1b4019a67125d062bbef6879fcf28b63cd24acc0e7)
(2) Run `upgrade.sh` script from libsqlite3-sys folder
(3) If all is fine, commit and open a PR
