### ISSUE TITLE
"database is locked" with *separate* connections and `SQLITE_OPEN_NO_MUTEX`

### ISSUE THREAD

**Issue by darosior** [rusqlite/rusqlite#920]
I'm using rusqlite to access an SQLite database in a multi-threaded application.

I use it mainly through two helpers (one to perform a set of updates in a single DB transaction, the other to perform a query):
https://github.com/revault/revaultd/blob/438c6d1be6a108fe774541c43a00fa7627d29057/src/daemon/database/interface.rs#L36-L79
Aware of [SQLITE_THREADSAFE](https://www.sqlite.org/compile.html#threadsafe) i, by precaution for now, open a new connection at the beginning of each of these routines.

However i have a race where two thread can call the same function at the same time (which calls the writing routine to perform a set of queries and updates in a single transaction) and would surprisingly (as these are on 2 different connections) result in a
```
database is locked
```
error.

Am i misusing the API ? Something seems not quite right as i'm 100% confident these are on two separate connections.

Misc information that may help diagnose:
- This function called concurrently is "long" in that we are doing many queries and updates in a single transaction
- Stating the obvious, no external program is trying to open the DB, it's a fresh DB created for functional tests in a fresh directory in `/tmp`
-

**Comment by gwenn** [comment]
Two connections cannot access to the same DB concurrently if at least one writes (it does **not** matter if the connections are opened by different programs or threads).
(SQLITE_OPEN_NO_MUTEX is meaningless here because it applies only when **one** connection is used concurrently by multiple threads).
And I guess you are using shared cache because your error is https://sqlite.org/rescode.html#locked and not https://sqlite.org/rescode.html#busy.
There is no MVCC with SQLite (https://sqlite.org/faq.html#q5).

**Comment by gwenn** [comment]
See https://sqlite.org/unlock_notify.html and https://github.com/rusqlite/rusqlite/blob/master/Cargo.toml#L42

**Comment by darosior** [comment]
Thank you for your prompt answer.

I have to say that the SQLite is pretty [misguiding](https://sqlite.org/threadsafe.html) then.. There is mentioned all around the documentation that it does support multi-threading access but not a single time (apart in the FAQ you linked, which i should definitely *have* read) that it's exclusively for read accesses.

I guess i can close that now that it's been demonstrated i can't read a doc effectively :) Thanks again!

**Comment by trevyn** [comment]
@darosior There are a LOT of subtleties about this in SQLite. The doc you linked explains that any sort of concurrent access can be made *thread-safe*, but as you noticed, this means a different thing than what level of *database* concurrency is available. In SQLite, write transactions are always serialized — that is, there can only ever be one write transaction open at a time on the same database file. (Though there can be many read transactions open concurrent with this.)

I think the doc page you're looking for is this: https://sqlite.org/isolation.html

Specifically, in WAL mode, SQLite implements a "serializable" transaction isolation level by using the "snapshot isolation" technique. This is conceptually related to, but at a completely different level of abstraction than the question of which thread-based concurrency model is used.

If you have more questions about this, the [SQLite forum](https://sqlite.org/forum/forum) is excellent, and by asking a well-considered question, you can expect detailed technical responses from very well-informed individuals.

**Comment by EvanCarroll** [comment]
> Two connections cannot access to the same DB concurrently if at least one writes (it does **not** matter if the connections are opened by different programs or threads). (SQLITE_OPEN_NO_MUTEX is meaningless here because it applies only when **one** connection is used concurrently by multiple threads). And I guess you are using shared cache because your error is https://sqlite.org/rescode.html#locked and not https://sqlite.org/rescode.html#busy. There is no MVCC with SQLite (https://sqlite.org/faq.html#q5).

I don't believe that it true,

> immutable: The immutable parameter is a boolean query parameter that indicates that the database file is stored on read-only media. When immutable is set, SQLite assumes that the database file cannot be changed, even by a process with higher privilege, and so the database is opened read-only and all locking and change detection is disabled. Caution: Setting the immutable property on a database file that does in fact change can result in incorrect query results and/or [SQLITE_CORRUPT](https://www.sqlite.org/rescode.html#corrupt) errors. See also: [SQLITE_IOCAP_IMMUTABLE](https://www.sqlite.org/c3ref/c_iocap_atomic.html).

The way I read that is subject to potential `SQLITE_CORRUPT` errors, the database can be opened.

**Comment by gwenn** [comment]
> I don't believe that it true,

So you should ask SQLite team to rewrite https://sqlite.org/faq.html#q5

**Comment by EvanCarroll** [comment]
@gwenn good idea & done. https://fossil-scm.org/forum/forumpost/7167956348
