### ISSUE TITLE
Implementations of ToSql and FromSql for u64

### ISSUE THREAD

**Issue by tvallotton** [rusqlite/rusqlite#922]
Hi, I noticed that using u64 is not supported, since it does not implement neither ToSql, nor FromSql. I was wondering if you were planning to do it in the future or I should just stick with i64 instead. Thanks for maintaining this great crate.

**Comment by gwenn** [comment]
See #826 and #823
But not released yet...

**Comment by gwenn** [comment]
Should be fixed by version 0.25.0
