### ISSUE TITLE
how do I use sqlcipher feature

### ISSUE THREAD

**Issue by avnerbarr** [rusqlite/rusqlite#926]
I need to encrypt the db so naturally tried using the sqlcipher feature you support (I am flexible though to which ever method is suggested)

For reference I've been including the package using these features:

```
rusqlite = { version = "0.24.2", features = ["bundled", "chrono", "serde_json", "time"] }  # https://github.com/rusqlite/rusqlite#optional-features: bundled uses a bundled version of sqlite3. This is a good option for cases where linking to sqlite3 is complicated, such as Windows.
```

Per the `Readme` I tried replacing the `bundled` feature and changing to `sqlcipher`

but getting a linker error (Mac BigSur):

```
  = note: ld: library not found for -lsqlcipher
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I've gone ahead and run `brew install sqlcipher` 

i will need to also cross compile for linux/windows. 

I found this fork which is very old and not maintained which is supposedly bundling the libs:

https://github.com/mikelodder7/rusqlcipher

Is there an easier procedure for adding the sqlcipher support?

Thanks!

**Comment by thomcc** [comment]
In the next version you'll be able to use the `bundled-sqlcipher` feature which makes this much easier. Previously you needed to have it installed, and potentially manually specify the path.
