### ISSUE TITLE
Why do some non-mutating methods on `InnerConnection` take `&self` and others `&mut self`?

### ISSUE THREAD

**Issue by H2CO3** [rusqlite/rusqlite#931]
Hi there. I am trying to create lower-level, application-specific bindings to SQLite myself, and for that I'm studying the source of Rusqlite.

I am aware that it is highly non-trivial to wrap the SQLite C library in a way that respects thread safety and Rust's lifetime and aliasing rules. For this reason, I'm trying to understand when exactly one needs mutable exclusive or immutable shared access to the `sqlite3 *` connection handle.

The relevant type in Rusqlite is `InnerConnection`. Unfortunately, I do not understand why some seemingly read-only methods take `&mut self` while others simply take `&self`. The SQLite C API itself is not const-correct, so `const` arguments don't help answer this question.

As a concrete example, let's take:

```
pub fn last_insert_rowid(&self) -> i64 { … }
pub fn changes(&mut self) -> usize { … }
pub fn decode_result(&mut self, code: c_int) -> Result<()> { … }
```

Compare this to:
* `last_insert_rowid` takes `&self` and does not mutate anything, as `sqlite3_last_insert_rowid` just returns a member of the DB handle directly. So far so good.
* `changes` takes `&mut self`. However, it does not mutate anything, as `sqlite3_changes` simply returns a member of the `sqlite3` structure.
* `decode_result` takes a `&mut self` as well. It calls `sqlite3_errstr()` internally, which can indeed mutate the DB handle. It can change the text encoding of the backing `sqlite3_value` in-place. However, this function is protected by a mutex. So it looks like it might as well take `&self`.

All in all, what am I missing?

**Comment by gwenn** [comment]
See first commit:
https://github.com/rusqlite/rusqlite/blob/ca3a0f058008cff7993d092a022686c64d1a37ce/src/lib.rs#L154
https://github.com/rusqlite/rusqlite/blob/ca3a0f058008cff7993d092a022686c64d1a37ce/src/lib.rs#L182
https://github.com/rusqlite/rusqlite/blob/ca3a0f058008cff7993d092a022686c64d1a37ce/src/lib.rs#L201
For me, as the same Connection cannot be used by multiple threads at the same time, `&self` and `self.db.borrow()` should be fine.

**Comment by gwenn** [comment]
Version 0.26.0 released
