### ISSUE TITLE
Getting a clippy warning "redundant closure" when using query_row

### ISSUE THREAD

**Issue by siyopao** [rusqlite/rusqlite#938]
Hello 👋 

I tried a search for this issue but did not see it anywhere so let me add it here:

In my code I have something similar to:
```
statement.query_row(params![foo], |row| Foo::try_from(row)).optional()?;
```
about which clippy warns me of a "redundant closure". If I try to remove the redundant closure
```
statement.query_row(params![foo], Foo::try_from).optional()?;
```
 then I get an error
 ```
.query_row(params![foo], Foo::try_from)
 ^^^^^^^^^ implementation of `std::ops::FnOnce` is not general enough
```
Do you think there is anything I can do? (Besides turning off this clippy warning of course.)

Thank you!

**Comment by thomcc** [comment]
Probably file a bug in https://github.com/rust-lang/rust-clippy, I don't think there's much we can do about this.

**Comment by siyopao** [comment]
Ah, so that is a clippy error. Let me file a bug report. Thanks a lot!
