### ISSUE TITLE
Please increase the SQLITE_MAX_LENGTH in bundled mode libsqlite3-sys

### ISSUE THREAD

**Issue by hlavaatch** [rusqlite/rusqlite#945]
When I build rusqlite in bundled mode, it currently has the default SQLITE_MAX_LENGTH=1000000000 that can not be raised using the limits API.
Can you please increase the the default SQLITE_MAX_LENGTH limit to the supported maximum of 2147483647 when building libsqlite3-sys in bundled mode? It is awkward and fragile to set up build time environment variables from the project that is using rusqlite as a dependency.

There is no way to raise this hard limit, but it can be lowered using the limits API, so there should be no harm in rising the limit.

**Comment by thomcc** [comment]
I think you should be able to override this with the not-particularly-documented `LIBSQLITE3_FLAGS` environment variable: https://github.com/rusqlite/rusqlite/blob/840a6f3789f91d71599fa8fe909cc0d51b13f862/libsqlite3-sys/build.rs#L272

I don't think we want to change it everywhere.
