### ISSUE TITLE
Documentation for column type errors mentions column type rather than value type

### ISSUE THREAD

**Issue by lefth** [rusqlite/rusqlite#950]
`InvalidColumnType` is described as an error when the type requested doesn't match the column type, but in my testing it seems to only depend on the SQLite value (not the column type). For example, getting a string column as an Option<i32> is valid as long as the data is NULL. The way the docs are currently worded, a nullable column should be gotten as `Option<T>` and a non-nullable column should be gotten as `T`.

I assume "column type" was meant to refer to the column of a row (the value type rather than the type in the table schema). But that interpretation still doesn't match current behavior.

I'll make a PR to reword it.

**Comment by gwenn** [comment]
"type in the table schema" is almost meaningless for SQLite (see https://sqlite.org/datatype3.html and type affinity)...

**Comment by lefth** [comment]
I was not aware SQLite types (in the schema) were just recommendations! I'll close this PR and bug report, as the wording is not ambiguous given SQLite's dynamic typing.
