### ISSUE TITLE
How do I get the file of the database from Connection?

### ISSUE THREAD

**Issue by broccolihighkicks** [rusqlite/rusqlite#962]
```rust
pub struct Connection {
    db: RefCell<InnerConnection>,
    cache: StatementCache,
    path: Option<PathBuf>,
}
```

`path` is private, and it does not seem any of the `Connection` functions return it.

If I have a `Connection` instance, does this mean I cannot get the file path from it?

**Comment by thomcc** [comment]
Using https://sqlite.org/pragma.html#pragma_database_list would probably be more robust anyway.

**Comment by broccolihighkicks** [comment]
Thanks, I might have to execute the `PRAGMA database_list` query.

I think it would be really helpful to have a public interface to get the file path - this would prevent me having to wrap the `Connection` in a `ConnectionAndPath` struct or executing a query to get the file path.

**Comment by thomcc** [comment]
Hm, fair enough.
