### ISSUE TITLE
authorizer is public but AuthContext / Authorization are not

### ISSUE THREAD

**Issue by gwenn** [rusqlite/rusqlite#972]
https://github.com/rusqlite/rusqlite/blob/master/src/hooks.rs#L403
```rust
    pub fn authorizer&lt;'c, F&gt;(&amp;self, hook: Option&lt;F&gt;)    where        F: for&lt;'r&gt; FnMut(AuthContext&lt;'r&gt;) -&gt; Authorization + Send + RefUnwindSafe + 'static,<br class="Apple-interchange-newline">
```

**Comment by gwenn** [comment]
@nhynes For your information, PR #946 is incomplete.

**Comment by nhynes** [comment]
Thanks, that's a good catch. I can't really think of any way to prevent that kind of thing from happening again other than to have a second test crate. `#![deny(unreachable_pub)]` might have been a little useful, but not sufficient. Do you have any ideas?

**Comment by gwenn** [comment]
Don't worry.
We should have catch the issue while reviewing #946.
And I guess a doc test or an integration test should be sufficient, no need for a test crate...
