### ISSUE TITLE
Ubuntu 20.04 can't Build

### ISSUE THREAD

**Issue by caseykneale** [rusqlite/rusqlite#978]
cargo.toml
```[dependencies.rusqlite]
version = "0.25.3"
features = ["bundled"]
```
main.rs
```
the example code
```

The dump is massive but I think the most important part is at the end. Let me know if you want to see more.
```
...
          /usr/bin/ld: final link failed: bad value
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error

error: could not compile `libsqlite3-sys`

To learn more, run the command again with --verbose.
```

**Comment by caseykneale** [comment]
Should also add, I can build for windows with "bundled-windows". Without issues. Well until I try to run it...

**Comment by thomcc** [comment]
> /usr/bin/ld: final link failed: bad value

Hmm, might be https://github.com/rust-lang/rust/issues/59308 ? Can you include the whole output

> Should also add, I can build for windows with "bundled-windows". Without issues. Well until I try to run it...

Does it fail at runtime? Can you elaborate?

**Comment by thomcc** [comment]
> I can build for windows

FWIW cross-compiling for windows is tricky, you should build on that windows machine unless you're willing to set up a whole cross-compile env (not really recommended unless you know what you're doing)

**Comment by caseykneale** [comment]
Thanks for the advice. Okay, so running cargo clean solved the issue. I should probably default to that but - this was an empty project very recently. We can close this out if you want, but yea something got borked with cargo.

**Comment by thomcc** [comment]
Yep, seems like a cargo bug.
