### ISSUE TITLE
Support Virtual column type (json)

### ISSUE THREAD

**Issue by sunshine69** [rusqlite/rusqlite#980]
Hi there,

I am very new to rust so pls help if I am doing not right ...

Basically I am trying to see if the extension support all sqlite features and actually after reading several docs which usually gives pretty much common guide but not explicitly how to achieve it. For example like how to compile the extension to enable json feature etc.. Well not only this crate, but some, it might be rust culture that assume user know what to do. (I miss the golang culture here sorry to say)

back to the main proble,. I have this like in Cargo.toml. Tested with both bundle features enable or disabled, same result.

```
[dependencies.rusqlite]
version = "0.25.3"
# features = ["bundled"]
```

The code is:
```
use rusqlite::{
    params, 
    Connection, 
    Result
};

#[derive(Debug)]
struct Person {
    id: i32,
    pid: i32,
    name: String,
    data: Option<String>,
}

fn main() -> Result<()> {
    let conn = Connection::open_in_memory()?;

    conn.execute(
        "CREATE TABLE person (
                  id              INTEGER PRIMARY KEY,
                  name            TEXT NOT NULL,
                  pid INT GENERATED ALWAYS AS (json_extract(data, '$.pid')) VIRTUAL,
                  data            BLOB
                  )",
        [],
    )?;
    let me = Person {
        id: 0,
        pid: 0,
        name: "Steven".to_string(),
        data: Some("{\"id\": 123}".to_string()),
    };
    conn.execute(
        "INSERT INTO person (name, data) VALUES (?1, ?2)",
        params![me.name, me.data],
    )?;

    let mut stmt = conn.prepare("SELECT id, pid, name, data FROM person")?;
    let person_iter = stmt.query_map([], |row| {
        Ok(Person {
            id: row.get(0)?,
            pid: row.get(1)?,
            name: row.get(2)?,
            data: row.get(3)?,
        })
    })?;

    for person in person_iter {
        println!("Found person {:?}", person.unwrap());
    }
    Ok(())
}
```

And run `cargo run` saying

```
     Running `target/debug/sqlite3`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidColumnType(1, "pid", Null)', src/main.rs:49:46

```

It seems the column type VIRTUAL is not supported. 

How can I enable that sqlite3 feature in rusqlite please?

**Comment by gwenn** [comment]
Doesn't work with SQLite3 CLI:
```sh
sqlite> CREATE TABLE person (
                  id              INTEGER PRIMARY KEY,
                  name            TEXT NOT NULL,
                  pid INT GENERATED ALWAYS AS (json_extract(data, '$.pid')) VIRTUAL,
                  data            BLOB
                  );
sqlite> .schema
CREATE TABLE person (
                  id              INTEGER PRIMARY KEY,
                  name            TEXT NOT NULL,
                  pid INT GENERATED ALWAYS AS (json_extract(data, '$.pid')) VIRTUAL,
                  data            BLOB
                  );
sqlite> INSERT INTO person (name, data) VALUES ('Steven', '{"id": 123}');
sqlite> SELECT id, pid, name, data FROM person;
1||Steven|{"id": 123}
```
`pid` is `NULL` which is not a valid `i32` value...

**Comment by sunshine69** [comment]
there is a typo in there, the inserted data should be `'Steven', '{"pid": 123}'` (pid). Let me adjust in my rust code and see ...

**Comment by sunshine69** [comment]
It works. Thanks for the test leading me to the fix.
However the question remains as:
- How can I manually add the compile flags when compiling? For example add `-DSQLITE_ENABLE_JSON1` at the compile sqlit3 stage.
I read about cargo build flags and tried various and always failed. It seems rustc confused it with rust lint.

**Comment by thomcc** [comment]
The bundled build already has that flag, and several others: https://github.com/rusqlite/rusqlite/blob/master/libsqlite3-sys/build.rs#L119

If you need something extra, you can set it in an environment var `LIBSQLITE3_FLAGS`: https://github.com/rusqlite/rusqlite/blob/master/libsqlite3-sys/build.rs#L275

This is a bit annoying, since there's no automated way to do it if you don't control the build machine (e.g. with cargo install), but there's no alternative really. Our bundled build includes most things anyway.

**Comment by thomcc** [comment]
It seems like this is resolved, I'm going to close it.
