### ISSUE TITLE
Missing functions

### ISSUE THREAD

**Issue by weiznich** [rusqlite/rusqlite#981]
I've noticed that `libsqlite3-sys` is missing the following functions and constants:

* [`sqlite3_prepare_v3`](https://www.sqlite.org/c3ref/prepare.html)
* [`sqlite3_value_dup`](https://www.sqlite.org/c3ref/value_dup.html)
* [`sqlite3_value_free`](https://www.sqlite.org/c3ref/value_dup.html)
* [`SQLITE_PREPARE_PERSISTENT`](https://www.sqlite.org/c3ref/c_prepare_normalize.html#sqlitepreparepersistent)

**Comment by gwenn** [comment]
https://github.com/rusqlite/rusqlite/blob/master/libsqlite3-sys/Cargo.toml#L15

**Comment by weiznich** [comment]
Ah, right there was that thing. That another good argument for #706 for making using the current binding the default
