### ISSUE TITLE
Access to `sqlite3_db_cacheflush` via `Connection`

### ISSUE THREAD

**Issue by ShadowJonathan** [rusqlite/rusqlite#984]
I'd like to have access to [cacheflush](https://www.sqlite.org/c3ref/db_cacheflush.html), so that i can manually flush the database while `PRAGMA synchronous=OFF`.

**Comment by gwenn** [comment]
https://sqlite.org/releaselog/3_10_0.html => modern_sqlite

**Comment by gwenn** [comment]
Version 0.26.0 released
