### ISSUE TITLE
Parsing keys for SQLCipher databases

### ISSUE THREAD

**Issue by 0x2b00b1e5** [rusqlite/rusqlite#992]
Hi, I am probably just missing something but I tried to connect to a sqlcipher database but it didn't work.

I first did `conn.execute_batch("PRAGMA key = 'test123';")` and then `conn.execute_batch("SELECT count(*) FROM sqlite_master;")` as a test, but this did not decrypt the database correctly for some reason (returned message: `file is not a database`). I have tested the decryption using the `sqlcipher` CLI tool, which just worked fine.

I am using the `sqlcipher-bundled` feature.

**Comment by gwenn** [comment]
`execute_batch` should be fine but you should use:
```rust
conn.pragma_update(None, "key", &passphrase)?;
```
And do you know which kind of error is expected when the passphrase is incorrect ?
Page https://www.zetetic.net/sqlcipher/sqlcipher-api/#PRAGMA_key doesn't help.

**Comment by gwenn** [comment]
https://discuss.zetetic.net/t/file-is-not-a-database/3320
https://discuss.zetetic.net/t/error-file-is-not-a-database/4434
```rust
        let cipher_version: String = db.pragma_query_value(None, "cipher_version", |row| row.get(0))?;
```

**Comment by thomcc** [comment]
> And do you know which kind of error is expected when the passphrase is incorrect ?

It gives the error "not a database" when you try to use it (e.g. on the first query, not on the `PRAGMA key`). It is somewhat weird...

This sounds like your key is wrong to me. This wouldn't explain why it works on the CLI though.

Perhaps the page size doesn't match though (it must match for sqlcipher, and perhaps it has a different default on the CLI)...

**Comment by 0x2b00b1e5** [comment]
> `execute_batch` should be fine but you should use:
> ```rust
> conn.pragma_update(None, "key", &passphrase)?;
> ```

Tried that too, same result. 

Just to clarify that the 
```rust
conn.execute_batch("PRAGMA key = 'test123;');
```
... does succeed. The problems start when trying to touch/read/alter the database.

**Comment by 0x2b00b1e5** [comment]
> Perhaps the page size doesn't match though (it must match for sqlcipher, and perhaps it has a different default on the CLI)...

Maybe? How would I change the page size?

**Comment by 0x2b00b1e5** [comment]
Update: used the rusqlite api to create a db instead. This does work. So I guess there is indeed a pagesize/encoding issue there.
