### ISSUE TITLE
VM must run to completion for constraint violations to become visible

### ISSUE THREAD

**Issue by nhynes** [rusqlite/rusqlite#995]
This issue is about a strange interaction between `RETURNING`, rusqlite, and the way SQLite raises errors about constraint violations.

* constraints are only violated during inserts, updates, and deletes
* before `RETURNING` existed, inserts and updates would only go through `execute` and not trigger this issue
* when `RETURNING`, constraint violations are only thrown by SQLite after the VM is fully stepped
* rusqlite methods like `query_row` lead to violations being silently reverted

I'm not sure if this is actually a bug, but it might be worth noting somewhere (e.g., in this issue).

## MWE

```toml
# Cargo.toml
rusqlite = { version = "*", features = ["bundled"] }
```

```rust
// main.rs
fn main() -> Result<(), Box<dyn std::error::Error>> {
    let db = rusqlite::Connection::open_in_memory()?;

    db.execute_batch(
        "
        CREATE TABLE items (id INTEGER PRIMARY KEY);
        CREATE TABLE trades (item INTEGER REFERENCES items(id) NOT NULL);
        ",
    )?;

    let mut stmt = db.prepare_cached("INSERT INTO trades (item) VALUES (42) RETURNING *")?;

    // Works.
    {
        let mut rows = stmt.query([])?;
        assert!(rows.next().is_ok());
        assert!(rows.next().is_err());
    }

    // Doesn't work because the VM hasn't stepped to completion.
    {
        let item_id: u8 = stmt.query_row([], |row| row.get("item"))?;
        assert_eq!(item_id, 42, "huh");
    }
    // `sqlite3_reset` via `<Rows as Drop>::drop` doesn't help either.

    // However, SQLite is still enforcing the constraint.
    assert_eq!(
        db.query_row("SELECT * FROM trades", [], |_| Ok(())),
        Err(rusqlite::Error::QueryReturnedNoRows)
    );

    Ok(())
}
```

**Comment by gwenn** [comment]
[foreign key constraint enforcement](https://sqlite.org/pragma.html#pragma_foreign_keys) is enabled ?

**Comment by nhynes** [comment]
Yes, I haven't changed it from [the default](https://github.com/rusqlite/rusqlite/blob/master/libsqlite3-sys/build.rs#L112). I also put in a `PRAGMA` just to be safe, but got the same results.

**Comment by gwenn** [comment]
```sql
sqlite> PRAGMA foreign_keys;
1
sqlite> CREATE TABLE items (id INTEGER PRIMARY KEY);
sqlite> CREATE TABLE trades (item INTEGER REFERENCES items(id) NOT NULL);
sqlite> INSERT INTO trades (item) VALUES (42) RETURNING *;
42
Error: FOREIGN KEY constraint failed
```

**Comment by gwenn** [comment]
Fixed by https://www.sqlite.org/src/info/a818ba2ed635b91e
